{{
    config(
        materialized="table",
        alias="employee",
        schema="dataconsolidation"
    )
}}

with
    ukg_employee as (select * from {{ ref('employee') }}),
    states as (select * from {{ source('portal', 'states') }}),
    contractor_companies as (select * from {{ source('portal', 'contractor_companies') }}),
    countries as (select * from {{ source('portal', 'countries') }}),
    departments as (select * from {{ source('portal', 'departments') }}),
    dol_statuses as (select * from {{ source('portal', 'dol_statuses') }}),
    employee_types as (select * from {{ source('portal', 'employee_types') }}),
    entities as (select * from {{ source('portal', 'entities') }}),
    ethnic_backgrounds as (select * from {{ source('portal', 'ethnic_backgrounds') }}),
    labor_categories as (select * from {{ source('portal', 'labor_categories') }}),
    genders as (select * from {{ source('portal', 'genders') }}),
    locations_intacct as (select * from {{ source('portal', 'locations_intacct') }}),
    locations_ukg as (select * from {{ source('portal', 'locations_ukg') }}),
    locations as (select * from {{ source('portal', 'locations') }}),
    location_regions as (select * from {{ source('portal', 'location_regions') }}),
    location_continents as (select * from {{ source('portal', 'location_continents') }}),
    payroll_companies as (select * from {{ source('portal', 'payroll_companies') }}),
    pay_types as (select * from {{ source('portal', 'pay_types') }}),
    positions as (select * from {{ source('portal', 'positions') }}),
    position_families as (select * from {{ source('portal', 'position_families') }}),
    practices as (select * from {{ source('portal', 'practices') }}),
    termination_types as (select * from {{ source('portal', 'termination_types') }}),
    users_forecasts as (select * from {{ source('portal', 'users_forecasts') }})

SELECT 
    --KEYS
    UKG.KEY,
    COMPANIES.RECORD_ID AS KEY_COMPANY,
    CONTINENTS.RECORD_ID AS KEY_CONTINENT,
    CONTRACTOR_COMPANIES.RECORD_ID AS KEY_CONTRACTOR_COMPANY,
    COUNTRIES.RECORD_ID AS KEY_COUNTRY,
    DEPARTMENTS.RECORD_ID AS KEY_DEPARTMENT,
    DOL.RECORD_ID AS KEY_DOL_STATUS,
    EMPLOYEE_TYPES.RECORD_ID AS KEY_EMPLOYEE_TYPE,
    ENTITIES.RECORD_ID AS KEY_ENTITY,
    ETHNIC.RECORD_ID AS KEY_ETHNIC_BACKGROUND_ID,
    GENDERS.RECORD_ID AS KEY_GENDER,
    LABOR_CATEGORIES.RECORD_ID AS KEY_LABOR_CATEGORIES,
    LOCATIONS.RECORD_ID AS KEY_LOCATION,
    LOCATIONS_INTACCT.RECORD_ID AS KEY_LOCATION_INTACCT,
    LOCATIONS_UKG.RECORD_ID AS KEY_LOCATION_UKG,
    PAYROLL_COMPANIES.RECORD_ID AS KEY_PAYROLL_COMPANY,
    PAY_TYPES.RECORD_ID AS KEY_PAY_TYPE,
    POSITIONS.RECORD_ID AS KEY_POSITION,
    POSITION_FAMILIES.RECORD_ID AS KEY_POSITION_FAMILY,
    PRACTICES.RECORD_ID AS KEY_PRACTICE,
    REGIONS.RECORD_ID AS KEY_REGION,
    STATES.RECORD_ID AS KEY_STATE,
    SUPERVISORS.KEY AS KEY_SUPERVISOR,
    TERMINATION_TYPES.RECORD_ID AS KEY_TERMINATION_TYPE,

    -- IDS
    SFC.ACCOUNT_ID,
    POR.AZURE_ID,
    SIN.INTACCT_CONTACT_KEY,
    SIN.INTACCT_DEPARTMENT_KEY,
    SIN.INTACCT_LOCATION_KEY,
    SIN.INTACCT_EMPLOYEE_ID,
    SIN.KEY AS INTACCT_EMPLOYEE_KEY,
    POR.INTACCT_OVERRIDE_ENTITY_ID,
    UKG.NATIONAL_ID,
    UKG.NATIONAL_ID_COUNTRY,
    POR.KEY AS PORTAL_ID,
    SFC.PROFILE_ID,
    POR.REGION_ID,
    SFC.KEY AS SALESFORCE_CONTACT_ID,
    POR.SALESFORCE_USER_ID,
    POR.SALESFORCE_SANDBOX_CONTACT_ID,
    POR.SALESFORCE_SANDBOX_USER_ID,
    POR.TRACKER_RECORD_ID,
    POR.UKG_OVERRIDE_PAYROLL_COMPANY_ID,
    UKG.UKG_PERSON_ID,
    SFC.WORK_CALENDAR_ID,

--NAMES
    CONTINENTS.DISPLAY_NAME AS CONTINTENT_NAME,
    COMPANIES.DISPLAY_NAME AS COMPANY_NAME,
    CONTRACTOR_COMPANIES.DISPLAY_NAME AS CONTRACTOR_COMPANY_NAME,
    COUNTRIES.DISPLAY_NAME AS COUNTRY_NAME,
    DEPARTMENTS.DISPLAY_NAME AS DEPARTMENT_NAME,
    DOL.DISPLAY_NAME AS DOL_STATUS_NAME,
    EMPLOYEE_TYPES.DISPLAY_NAME AS EMPLOYEE_TYPE_NAME,
    ENTITIES.DISPLAY_NAME AS ENTITY_NAME,
    ETHNIC.DISPLAY_NAME AS ETHNIC_BACKGROUND_NAME,  
    GENDERS.DISPLAY_NAME AS GENDER_NAME,
    LABOR_CATEGORIES.DISPLAY_NAME AS LABOR_CATEGORY_NAME,
    LOCATIONS.DISPLAY_NAME AS LOCATION_NAME,
    LOCATIONS_INTACCT.DISPLAY_NAME AS LOCATION_NAME_INTACCT,
    LOCATIONS_UKG.DISPLAY_NAME AS LOCATION_NAME_UKG,
    PAYROLL_COMPANIES.DISPLAY_NAME AS PAYROLL_COMPANY_NAME,
    PAY_TYPES.DISPLAY_NAME AS PAY_TYPE_NAME,
    IFNULL(UKG.JOB_TITLE, POSITIONS.DISPLAY_NAME) AS POSITION_NAME,
    POSITION_FAMILIES.DISPLAY_NAME AS POSITION_FAMILY_NAME,
    PRACTICES.DISPLAY_NAME AS PRACTICE_NAME,
    REGIONS.DISPLAY_NAME AS REGION_NAME,
    STATES.DISPLAY_NAME AS STATE_NAME,
    SUPERVISORS.DISPLAY_NAME AS SUPERVISOR_NAME,
    TERMINATION_TYPES.DISPLAY_NAME AS TERMINATION_TYPE_NAME,
    TERMINATION_TYPES.ADDRESSABLE_TYPE AS TERMINATION_ADDRESSABLE_TYPE,

-- OTHER FIELDS
    UKG.ADDRESS_CITY,
    UKG.ADDRESS_COUNTRY,
    UKG.ADDRESS_POSTAL_CODE,
    UKG.ADDRESS_STATE,
    UKG.ADDRESS_STREET,
    UKG.ANNUAL_SALARY,
    UKG.BLN_EXCLUDE_FROM_RESOURCE_PLANNER,
    UKG.BLN_IS_ACTIVE,
    SIN.BLN_IS_HOURLY,
    POR.BLN_MST,
    POR.BLN_PM_QUALIFIED,
    SFC.BLN_IS_RESOURCE,
    SFC.CLOSED_WON_GOAL,
    UKG.CURRENCY_CODE,
    UKG.DISPLAY_NAME,
    UKG.DISPLAY_NAME_LF,
    UKG.DTE_BIRTH,
    SFC.DTE_OF_INDUSTRY_EXPERIENCE,
    UKG.DTE_SRC_END,
    UKG.DTE_SRC_START,
    UKG.DTS_IN_JOB,
    UKG.DTS_LAST_HIRE,
    UKG.DTS_LAST_PAID,
    UKG.EMAIL_ADDRESS_PERSONAL,
    UKG.EMAIL_ADDRESS_WORK,
    UKG.EMPL_STATUS,
    UKG.FIRST_NAME,
    UKG.FIRST_NAME_DISPLAY,
    UKG.FORMER_NAME,
    UKG.HISTORICAL_UTILIZATION_TARGET_HOURS,
    UKG.HOME_PHONE,
    UKG.HOME_PHONE_COUNTRY,
    UKG.HOURLY_PAY_RATE,
    SIN.INTACCT_CONTACT_NAME,
    UKG.JOB_SALARY_GRADE,
    UKG.JOB_TITLE,
    UKG.LAST_NAME,
    UKG.MIDDLE_NAME,
    UKG.OTHER_RATE_1,
    UKG.OTHER_RATE_2,
    UKG.OTHER_RATE_3,
    UKG.OTHER_RATE_4,
    UKG.PAY_GROUP,
    UKG.PAY_PERIOD_PAY_RATE,
    UKG.STATUS,
    UKG.TERM_TYPE,
    UKG.TERMINATION_REASON_DESCRIPTION,
    UKG.TOTAL_ANN_SALARY,
    UKG.UKG_EMPLOYEE_NUMBER,
    UKG.UKG_OVERRIDE_JOB_TITLE,
    UKG.UKG_STATUS,
    UKG.UTILIZATION_TARGET,
    UKG.UTILIZATION_TARGET_HOURS,
    UKG.WEEKLY_PAY_RATE,
    UKG.WORK_PHONE_COUNTRY,
    POR.WORK_PHONE_NUMBER,

    --TARGET BILLING DATA
    USERS_FORECASTS.BILL_RATE AS TARGET_BILL_RATE_CURRENT,
    USERS_FORECASTS.PLAN_HOURS_WEEK AS TARGET_BILL_HOURS_WEEK_CURRENT,
    USERS_FORECASTS.PLAN_HOURS_YEAR AS TARGET_BILL_HOURS_YEAR_CURRENT,
    USERS_FORECASTS.PLAN_BILL_AMOUNT_WEEK AS TARGET_BILL_AMOUNT_WEEK_CURRENT,
    USERS_FORECASTS.PLAN_BILL_AMOUNT_YEAR AS TARGET_BILL_AMOUNT_YEAR_CURRENT,
    USERS_FORECASTS_LAST_YEAR.BILL_RATE AS TARGET_BILL_RATE_LAST,
    USERS_FORECASTS_LAST_YEAR.PLAN_HOURS_WEEK AS TARGET_BILL_HOURS_WEEK_LAST,
    USERS_FORECASTS_LAST_YEAR.PLAN_HOURS_YEAR AS TARGET_BILL_HOURS_YEAR_LAST,
    USERS_FORECASTS_LAST_YEAR.PLAN_BILL_AMOUNT_WEEK AS TARGET_BILL_AMOUNT_WEEK_LAST,
    USERS_FORECASTS_LAST_YEAR.PLAN_BILL_AMOUNT_YEAR AS TARGET_BILL_AMOUNT_YEAR_LAST
FROM ukg_employee UKG 
LEFT JOIN ukg_employee SIN on UKG.LINK = SIN.link AND SIN.SRC_SYS_KEY = 'sin'
LEFT JOIN ukg_employee POR on UKG.LINK = POR.link AND POR.SRC_SYS_KEY = 'por'
LEFT JOIN ukg_employee SFC on UKG.LINK = SFC.link AND SFC.SRC_SYS_KEY = 'sfc'
LEFT JOIN states AS STATES on UKG.STATE_ID = STATES.UKG_ID
LEFT JOIN contractor_companies AS CONTRACTOR_COMPANIES on POR.CONTRACTOR_COMPANY_ID = CONTRACTOR_COMPANIES.ID
LEFT JOIN countries AS COUNTRIES on UKG.ADDRESS_COUNTRY = COUNTRIES.UKG_ID
LEFT JOIN departments AS DEPARTMENTS on UKG.DEPARTMENT_ID = DEPARTMENTS.UKG_ID
LEFT JOIN dol_statuses AS DOL on UKG.DOL_STATUS_ID = DOL.UKG_ID
LEFT JOIN employee_types AS EMPLOYEE_TYPES on UKG.EMPLOYEE_TYPE_ID = EMPLOYEE_TYPES.UKG_ID
LEFT JOIN entities AS COMPANIES on UKG.KEY_ENTITY = COMPANIES.UKG_ID
LEFT JOIN ethnic_backgrounds AS ETHNIC on UKG.ETHNIC_BACKGROUND_ID = ETHNIC.UKG_ID
LEFT JOIN entities ENTITIES on SIN.LOCATION_ID_INTACCT = ENTITIES.ID
LEFT JOIN labor_categories AS LABOR_CATEGORIES on POR.LABOR_CATEGORY_ID = LABOR_CATEGORIES.ID
LEFT JOIN genders AS GENDERS on UKG.GENDER_ID = GENDERS.UKG_ID
LEFT JOIN locations_intacct AS LOCATIONS_INTACCT on UKG.LOCATION_ID_INTACCT = LOCATIONS_INTACCT.UKG_ID
LEFT JOIN locations_ukg AS LOCATIONS_UKG on UKG.LOCATION_ID_UKG = LOCATIONS_UKG.UKG_ID
LEFT JOIN locations AS LOCATIONS on IFNULL(STATES.LOCATION_ID,COUNTRIES.LOCATION_ID) = LOCATIONS.ID
LEFT JOIN location_regions AS REGIONS on LOCATIONS.REGION_ID = REGIONS.ID
LEFT JOIN location_continents AS CONTINENTS on REGIONS.CONTINENT_ID = CONTINENTS.ID
LEFT JOIN payroll_companies AS PAYROLL_COMPANIES on UKG.PAYROLL_COMPANY_ID = PAYROLL_COMPANIES.UKG_ID
LEFT JOIN pay_types AS PAY_TYPES on UKG.PAY_TYPE_ID = PAY_TYPES.UKG_ID
LEFT JOIN positions AS POSITIONS on UKG.POSITION_ID = POSITIONS.UKG_ID
LEFT JOIN position_families AS POSITION_FAMILIES on UKG.POSITION_FAMILY_ID = POSITION_FAMILIES.UKG_ID
LEFT JOIN practices AS PRACTICES on UKG.PRACTICE_ID = PRACTICES.UKG_ID
LEFT JOIN ukg_employee AS SUPERVISORS on UKG.SUPERVISOR_ID =SUPERVISORS.KEY
LEFT JOIN termination_types AS TERMINATION_TYPES on UKG.TERMINATION_TYPE_ID = TERMINATION_TYPES.UKG_ID
LEFT JOIN users_forecasts AS USERS_FORECASTS ON POR.KEY = USERS_FORECASTS.USER_ID AND USERS_FORECASTS.TIMEFRAME_ID = YEAR(CURRENT_DATE())
LEFT JOIN users_forecasts AS USERS_FORECASTS_LAST_YEAR ON POR.KEY = USERS_FORECASTS_LAST_YEAR.USER_ID AND USERS_FORECASTS_LAST_YEAR.TIMEFRAME_ID = YEAR(CURRENT_DATE())-1
WHERE UKG.SRC_SYS_KEY = 'ukg'