{{
    config(
        schema="dataconsumption"
    )
}}

with 
    timesheet       as (select * from {{ ref('fct_timesheet')}} ),
    timesheet_entry as (select * from {{ ref('fct_timesheet_entry')}} ),
final as (
    select
        current_timestamp as dts_created_at,
        '{{ this.name }}' as created_by,
        current_timestamp as dts_updated_at,
        '{{ this.name }}' as updated_by,
        te.key,
        ts.key_location,
        ts.key_department,
        ts.key_entity,
        ts.key_employee,
        ts.department_name,
        ts.location_name,
        ts.entity_name,
        ts.employee_name,
        ts.employee_department_id,
        ts.employee_id_intacct,
        ts.employee_id,
        ts.employee_location_id,
        ts.src_created_by_id,
        ts.src_modified_by_id,
        ts.sup_doc_id,
        ts.sup_doc_key,
        ts.entity_id,
        ts.bln_cost_actual,
        ts.config,
        ts.description,
        ts.dte_gl_post,
        ts.dte_src_end,
        ts.dte_src_start,
        ts.dts_src_created,
        ts.dts_src_modified,
        ts.employee_first_name,
        ts.employee_last_name,
        ts.hours_in_day,
        ts.mega_entity_name,
        ts.method,
        ts.state_worked,
        ts.status,
        ts.uom,
        te.key_timesheet,
        te.key_practice_area,
        te.key_project,
        te.practice_area_name,
        te.project_id,
        te.project_name,
        te.currency_iso_code,
        te.employee_name_lf,
        te.billu_acct_key,
        te.customer_id,
        te.department_id,
        te.department_key,
        te.employee_earning_type_key,
        te.item_id,
        te.labor_gl_batch_key,
        te.location_id,
        te.location_key,
        te.non_billnu_acct_key,
        te.non_billu_acct_key,
        te.stat_gl_batch_key,
        te.stat_journal_key,
        te.task_id,
        te.amt_labor_gl_entry,
        te.amt_labor_glentry_trx,
        te.amt_stat_gl_entry,
        te.bill_rate,
        te.bln_billable,
        te.bln_billed,
        te.customer_name,
        te.dte_entry,
        te.dte_src_created,
        te.dte_src_modified,
        te.item_name,
        te.labor_gl_entry_cost_rate,
        te.labor_gl_entry_line_no,
        te.labor_gl_entry_offset_line_no,
        te.line_no,
        te.notes,
        te.qty,
        te.qty_salesforce,
        te.qty_approved,
        te.qty_approved_billable,
        te.qty_approved_non_billable,
        te.qty_approved_non_utilized,
        te.qty_approved_utilized,
        te.qty_billable,
        te.qty_non_billable,
        te.qty_non_utilized,
        te.qty_utilized,
        te.record_url,
        te.stat_gl_entry_line_no,
        te.state,
        te.task_key,
        te.timesheet_entry_ref,
        te.task_name
    from timesheet ts
    inner join timesheet_entry te on te.key_timesheet = ts.key
)

select * from final