{{
    config(
        materialized="view",
        schema="dataconsumption",
        alias="vw_finance_location"
    )
}}

with 
    location as (select 
        addresscountrydefault,
        businessdays,
        contactinfo_companyname,
        contactinfo_contactname,
        contactinfo_email_1,
        contactinfo_fax,
        contactinfo_mailaddress_address_1,
        contactinfo_mailaddress_address_2,
        contactinfo_mailaddress_address_3,
        contactinfo_mailaddress_city,
        contactinfo_mailaddress_country,
        contactinfo_mailaddress_countrycode,
        contactinfo_mailaddress_state,
        contactinfo_mailaddress_zip,
        contactinfo_phone_1,
        contactinfo_printas,
        contactinfo_url_1,
        contactkey,
        createdby,
        createdbyloginid,
        currency,
        custentity,
        customerid,
        customername,
        custtitle,
        entity,
        entityname,
        federalid,
        firstmonth,
        firstmonthtax,
        has_ie_relation,
        isroot,
        locationid,
        locationtype,
        modifiedby,
        modifiedbyloginid,
        name,
        parentid,
        parentkey,
        parentname,
        record_url,
        recordno,
        reportprintas,
        shipto_companyname,
        shipto_contactname,
        shipto_mailaddress_address_1,
        shipto_mailaddress_address_2,
        shipto_mailaddress_city,
        shipto_mailaddress_country,
        shipto_mailaddress_countrycode,
        shipto_mailaddress_zip,
        shipto_printas,
        shiptokey,
        startdate,
        status,
        supervisorid,
        supervisorkey,
        supervisorname,
        taxid,
        vendentity,
        vendorid,
        vendorname,
        weekends,
        weekstart,
        whencreated,
        whenmodified
    from {{ source("sage_intacct","location") }} where _fivetran_deleted = false
)

select 
    cast(location.recordno as varchar(5000)) as key,
    cast(location.contactkey as varchar(5000)) as key_contact,
    cast(location.parentkey as varchar(5000)) as key_parent,
    cast(location.shiptokey as varchar(5000)) as key_ship_to,
    cast(location.supervisorkey as varchar(5000)) as key_supervisor,
    nullif(location.customerid,'') as customer_id,
    nullif(location.federalid,'') as federal_id,
    location.locationid as location_id,
    location.locationtype as location_type_id,
    nullif(location.parentid,'') as parent_id,
    cast(location.createdby as varchar(5000)) as src_created_by,
    nullif(location.createdbyloginid,'') as src_created_by_login_id,
    cast(location.modifiedby as varchar(5000)) as src_modified_by,
    nullif(location.modifiedbyloginid,'') as src_modified_by_login_id,
    nullif(location.supervisorid,'') as supervisor_id,
    nullif(location.taxid,'') as tax_id,
    nullif(location.vendorid,'') as vendor_id,
    nullif(location.addresscountrydefault,'') as address_country_default,
    ifnull(location.has_ie_relation,false) as bln_has_ie_relation,
    ifnull(location.isroot,false) as bln_is_root,
    iff(location.status = 'active', true, false) as bln_is_active,
    nullif(location.businessdays,'') as business_days,
    nullif(location.contactinfo_mailaddress_address_1,'') as contact_address_1,
    nullif(location.contactinfo_mailaddress_address_2,'') as contact_address_2,
    nullif(location.contactinfo_mailaddress_address_3,'') as contact_address_3,
    nullif(location.contactinfo_mailaddress_city,'') as contact_address_city,
    nullif(location.contactinfo_mailaddress_country,'') as contact_address_country,
    nullif(location.contactinfo_mailaddress_countrycode,'') as contact_address_country_code,
    nullif(location.contactinfo_mailaddress_state,'') as contact_address_state,
    nullif(location.contactinfo_mailaddress_zip,'') as contact_address_zip,
    nullif(location.contactinfo_companyname,'') as contact_company_name,
    nullif(location.contactinfo_email_1,'') as contact_email,
    nullif(location.contactinfo_fax,'') as contact_fax,
    nullif(location.contactinfo_contactname,'') as contact_name,
    nullif(location.contactinfo_phone_1,'') as contact_phone,
    nullif(location.contactinfo_printas,'') as contact_print_as,
    nullif(location.contactinfo_url_1,'') as contact_url,
    nullif(location.currency,'') as currency_iso_code,
    nullif(location.custentity,'') as customer_entity,
    nullif(location.customername,'') as customer_name,
    nullif(location.custtitle,'') as customer_title,
    location.startdate as dte_start,
    location.whencreated as dts_src_created,
    location.whenmodified as dts_src_modified,
    nullif(location.entity,'') as entity,
    nullif(location.entityname,'') as entity_name,
    location.firstmonth as first_month,
    location.firstmonthtax as first_month_tax,
    case when location.locationtype = 'C' then 'Location'
        when location.locationtype = 'E' then 'Entity'
        when location.locationtype = 'N' then 'Non-Active'
        else null
    end as location_type,
    nullif(location.name,'') as name,
    nullif(location.parentname,'') as parent_name,
    nullif(location.reportprintas,'') as report_print_as,
    nullif(location.shipto_mailaddress_address_1,'') as ship_address_1,
    nullif(location.shipto_mailaddress_address_2,'') as ship_address_2,
    nullif(location.shipto_mailaddress_city,'') as ship_address_city,
    nullif(location.shipto_mailaddress_country,'') as ship_address_country,
    nullif(location.shipto_mailaddress_countrycode,'') as ship_address_country_code,
    nullif(location.shipto_mailaddress_zip,'') as ship_address_zip,
    nullif(location.shipto_companyname,'') as ship_company_name,
    nullif(location.shipto_contactname,'') as ship_contact_name,
    nullif(location.shipto_printas,'') as ship_print_as,
    nullif(location.status,'') as status,
    nullif(location.supervisorname,'') as supervisor_name,
    nullif(location.vendentity,'') as vendor_entity,
    nullif(location.vendorname,'') as vendor_name,
    nullif(location.weekends,'') as week_ends,
    location.weekstart as week_start
from location