{{
    config(
        materialized="view",
        schema="dataconsumption",
        alias="vw_finance_customers"
    )
}}

with 
    customer as (select * from {{ source("sage_intacct","customer") }} where _fivetran_deleted = false)

select 
    cast(customer.recordno as varchar(5000)) as key,
    cast(customer.accountkey as varchar(5000)) as key_account,
    cast(customer.billtokey as varchar(5000)) as key_bill_to,
    cast(customer.custrepkey as varchar(5000)) as key_customer_rep,
    cast(customer.custtypekey as varchar(5000)) as key_customer_type,
    cast(customer.displaycontactkey as varchar(5000)) as key_display_contact,
    cast(customer.offsetaccountkey as varchar(5000)) as key_offset_account,
    cast(customer.parentkey as varchar(5000)) as key_parent,
    cast(customer.shiptokey as varchar(5000)) as key_ship_to,
    cast(customer.termskey as varchar(5000)) as key_terms,
    cast(customer.totaldue as number(38,2)) as amt_total_due,
    nullif(customer.billto_mailaddress_address_1,'') as bill_to_address_1,
    nullif(customer.billto_mailaddress_city,'') as bill_to_city,
    nullif(customer.billto_companyname,'') as bill_to_company_name,
    nullif(customer.billto_contactname,'') as bill_to_contact_name,
    nullif(customer.billto_mailaddress_country,'') as bill_to_country,
    nullif(customer.billto_mailaddress_countrycode,'') as bill_to_country_code,
    nullif(customer.billto_printas,'') as bill_to_print_as,
    nullif(customer.billto_mailaddress_state,'') as bill_to_state,
    nullif(customer.billto_mailaddress_zip,'') as bill_to_zip,
    iff(status='active',true,false) as bln_is_active,
    customer.billto_taxable as bln_bill_to_taxable,
    customer.billto_visible as bln_bill_to_visible,
    customer.displaycontact_taxable as bln_display_contact_taxable,
    customer.displaycontact_visible as bln_display_contact_visible,
    customer.shipto_taxable as bln_ship_to_taxable,
    customer.shipto_visible as bln_ship_to_visible,
    nullif(customer.customerid,'') as customer_id,
    nullif(customer.custrepid,'') as customer_rep_id,
    nullif(customer.custrepname,'') as customer_rep_name,
    nullif(customer.custtype,'') as customer_type,
    nullif(customer.displaycontact_mailaddress_address_1,'') as display_contact_address_1,
    nullif(customer.displaycontact_mailaddress_address_2,'') as display_contact_address_2,
    nullif(customer.displaycontact_mailaddress_address_3,'') as display_contact_address_3,
    nullif(customer.displaycontact_cellphone,'') as display_contact_cell_phone,
    nullif(customer.displaycontact_mailaddress_city,'') as display_contact_city,
    nullif(customer.displaycontact_companyname,'') as display_contact_company_name,
    nullif(customer.displaycontact_mailaddress_country,'') as display_contact_country,
    nullif(customer.displaycontact_mailaddress_countrycode,'') as display_contact_country_code,
    nullif(customer.displaycontact_email_1,'') as display_contact_email_1,
    nullif(customer.displaycontact_email_2,'') as display_contact_email_2,
    nullif(customer.displaycontact_fax,'') as display_contact_fax,
    nullif(customer.displaycontact_firstname,'') as display_contact_first_name,
    nullif(customer.displaycontact_lastname,'') as display_contact_last_name,
    nullif(customer.displaycontact_initial,'') as display_contact_middle_initial,
    nullif(customer.displaycontact_contactname,'') as display_contact_name,
    nullif(customer.displaycontact_phone_1,'') as display_contact_phone,
    nullif(customer.displaycontact_printas,'') as display_contact_print_as,
    nullif(customer.displaycontact_mailaddress_state,'') as display_contact_state,
    nullif(customer.displaycontact_status,'') as display_contact_status,
    nullif(customer.displaycontact_taxaddress,'') as display_contact_tax_address,
    nullif(customer.displaycontact_taxcompanyname,'') as display_contact_tax_company_name,
    nullif(customer.displaycontact_taxgroup,'') as display_contact_tax_group,
    nullif(customer.displaycontact_taxid,'') as display_contact_tax_id,
    nullif(customer.displaycontact_taxschedule,'') as display_contact_tax_schedule,
    nullif(customer.displaycontact_taxsolutionid,'') as display_contact_tax_solution_id,
    nullif(customer.displaycontact_url_1,'') as display_contact_url,
    nullif(customer.displaycontact_mailaddress_zip,'') as display_contact_zip,
    customer.displaycontact_taxidvalidationdate as dte_display_contact_tax_id_validation,
    customer.last_invoicedate as dte_last_invoice,
    customer.last_statementdate as dte_statement,
    customer.whencreated as dts_src_created,
    customer.whenmodified as dts_src_modified,
    nullif(customer.entity,'') as entity,
    nullif(cast(customer.araccount as varchar(5000)),'') as gl_account_ar,
    nullif(cast(customer.offsetglaccountno as varchar(5000)),'') as gl_account_offset,
    nullif(customer.offsetglaccountnotitle,'') as gl_account_offset_title,
    nullif(customer.araccounttitle,'') as gl_account_title_ar,
    nullif(customer.ie_vat_id,'') as ie_vat_id,
    nullif(customer.india_tax_id,'') as india_tax_id,
    nullif(customer.it_vat_id,'') as it_vat_id,
    nullif(customer.name,'') as name,
    nullif(customer.nl_vat_id,'') as nl_vat_id,
    nullif(customer.parentid,'') as parent_id,
    nullif(customer.parentname,'') as parent_name,
    nullif(cast(customer.rvat_registration as varchar(5000)),'') as r_vat_registration,
    nullif(customer.shipto_mailaddress_address_1,'') as ship_to_address,
    nullif(customer.shipto_mailaddress_city,'') as ship_to_city,
    nullif(customer.shipto_companyname,'') as ship_to_company_name,
    nullif(customer.shipto_contactname,'') as ship_to_contact_name,
    nullif(customer.shipto_mailaddress_country,'') as ship_to_country,
    nullif(customer.shipto_mailaddress_countrycode,'') as ship_to_country_code,
    nullif(customer.shipto_printas,'') as ship_to_print_as,
    nullif(customer.shipto_mailaddress_state,'') as ship_to_state,
    nullif(customer.shipto_mailaddress_zip,'') as ship_to_zip,
    nullif(cast(customer.createdby as varchar(5000)),'') as src_created_by,
    nullif(cast(customer.modifiedby as varchar(5000)),'') as src_modified_by,
    nullif(customer.status,'') as status,
    nullif(customer.taxid,'') as tax_id,
    nullif(customer.taxid_country_code,'') as tax_id_country_code,
    nullif(customer.termname,'') as term_name,
    nullif(customer.termvalue,'') as term_value,
    nullif(customer.vat_number,'') as vat_number
from customer