version: 2

sources:
  - name: salesforce
    database: FIVETRAN_DATABASE
    schema: SALESFORCE
    tables:
      - name: ACCOUNT
      - name: ACCOUNT_CONTACT_RELATION
      - name: ACCOUNT_CONTACT_ROLE
      - name: ACCOUNT_TEAM_MEMBER
      - name: APPROVAL
      - name: AUTH_SESSION
      - name: CALENDAR
      - name: CAMPAIGN
      - name: CAMPAIGN_MEMBER
      - name: CONTACT
      - name: CURRENCY_TYPE
      - name: CUSTOM_PERMISSION
      - name: CX_ACTOR_C
      - name: CX_AUDIT_TRAIL_C
      - name: CX_CLIENT_C
      - name: CX_DELIVERABLE_ACTION_C
      - name: CX_DELIVERABLE_C
      - name: CX_DELIVERABLE_TEMPLATE_C
      - name: CX_DELIVERABLE_TYPE_C
      - name: CX_JUNCTION_DELIVERABLE_SYSTEM_C
      - name: CX_JUNCTION_WORKFLOW_SYSTEM_C
      - name: CX_PROJECT_C
      - name: CX_PROJECT_USER_C
      - name: CX_SUB_WORKSTREAM_C
      - name: CX_SYSTEM_C
      - name: CX_WORKFLOW_ACTION_C
      - name: CX_WORKFLOW_C
      - name: CX_WORKSTREAM_C
      - name: DASHBOARD
      - name: DATED_CONVERSION_RATE
      - name: DUPLICATE_RULE
      - name: EVENT
      - name: EXPENSE_TYPE_GLA_MAPPING_C
      - name: FIVETRAN_API_CALL
      - name: FIVETRAN_DEPENDENT_PICKLIST_RELATION
      - name: FIVETRAN_FORMULA
      - name: FIVETRAN_FORMULA_FAILURE_REASON
      - name: FIVETRAN_FORMULA_MODEL
      - name: FIVETRAN_PICKLIST_FIELD
      - name: FIVETRAN_PICKLIST_FIELD_VALUE
      - name: FIVETRAN_QUERY
      - name: FORECASTING_GROUP_ITEM
      - name: FORECASTING_ITEM
      - name: FORECASTING_QUOTA
      - name: LEAD
      - name: LEAD_SOURCE_JUNCTION_C
      - name: LOGIN_HISTORY
      - name: OBJECT_PERMISSIONS
      - name: OPPORTUNITY
      - name: OPPORTUNITY_LINE_ITEM
      - name: OPPORTUNITY_TEAM_MEMBER
      - name: PERMISSION_SET
      - name: PERMISSION_SET_ASSIGNMENT
      - name: PERMISSION_SET_GROUP
      - name: PERMISSION_SET_LICENSE
      - name: PERMISSION_SET_LICENSE_ASSIGN
      - name: PHASE_CODE_SKILL_C
      - name: PRICEBOOK_2
      - name: PRICEBOOK_ENTRY
      - name: PRODUCT_2
      - name: PROFILE
      - name: PROJECT_EXPERIENCE_C
      - name: PROJECT_MILESTONE_C
      - name: PROJECT_TASK_MILESTONE_C
      - name: PROPOSAL_APPROVAL_C
      - name: PSE_ASSIGNMENT_C
      - name: PSE_ASSIGNMENT_MILESTONE_C
      - name: PSE_ASSIGNMENT_PROJECT_PHASE_C
      - name: PSE_BUDGET_C
      - name: PSE_EST_VS_ACTUALS_C
      - name: PSE_EXPENSE_C
      - name: PSE_EXPENSE_LIMIT_RATE_C
      - name: PSE_EXPENSE_REPORT_C
      - name: PSE_EXPERIENCE_C
      - name: PSE_EXPERIENCE_SKILL_C
      - name: PSE_GRP_C
      - name: PSE_MILESTONE_C
      - name: PSE_PERMISSION_CONTROL_C
      - name: PSE_PRACTICE_ACTUALS_C
      - name: PSE_PRACTICE_C
      - name: PSE_PROJECT_TASK_ASSIGNMENT_C
      - name: PSE_PROJECT_TASK_C
      - name: PSE_PROJ_C
      - name: PSE_RATE_CARD_C
      - name: PSE_RATE_CARD_SET
      - name: PSE_RATE_CARD_SET_JUNCTION_C
      - name: PSE_REGION_C
      - name: PSE_RESOURCE_REQUEST_C
      - name: PSE_RESOURCE_SKILL_REQUEST_C
      - name: PSE_SCHEDULE_C
      - name: PSE_SKILL_C
      - name: PSE_SKILL_CERTIFICATION_RATING_C
      - name: PSE_SKILL_CERTIFICATION_ZONE_C
      - name: PSE_SKILL_SET_C
      - name: PSE_SKILL_SET_SKILL_C
      - name: PSE_TASK_TIME_C
      - name: PSE_TIMECARD
      - name: PSE_TIMECARD_HEADER_C
      - name: PSE_UTILIZATION_CALCULATION_C
      - name: PSE_UTILIZATION_DETAIL_C
      - name: PSE_UTILIZATION_ENGINE_C
      - name: PSE_WORK_CALENDAR_C
      - name: PURCHASE_ORDER_C
      - name: QUOTE
      - name: QUOTE_LINE_ITEM
      - name: RESOURCE_REQUEST_INTEREST_C
      - name: RESPONSIBILITY_C
      - name: USER
      - name: USER_LICENSE
      - name: USER_ROLE
