{{ config(
    materialized='table',
    alias="invoice"
) }}

with 
    invoice as (
        select 
key, key_customer, key_entity, bill_back_template_key, bill_to_tax_id, billto_pay_to_key, contact_tax_id, src_created_by, created_by_login_id, cust_message_id, cust_message_key, doc_hdr_key, exch_rate_type_id, entity_id, modified_by_login_id, src_modified_by, pr_batch_key, record_id, ship_to_tax_group_id, ship_to_tax_id, shiptoreturntokey, sup_doc_id, tax_solution_id, term_key, dts_au_when_created, amt_total_due, amt_total_entered, amt_total_paid, qty_total_retained, qty_total_selected, amt_trx_entity_due, qty_trx_total_discount_applied, amt_trx_total_due, amt_trx_total_entered, amt_trx_total_paid, qty_trx_total_released, qty_trx_total_retained, qty_trx_total_selected, base_currency, bill_to_cell_phone, bill_to_company_name, bill_to_contact_name, bill_to_email_1, bill_to_email_2, bill_to_fax, bill_to_first_name, bill_to_initial, bill_to_last_name, bill_to_mail_address_address_1, bill_to_mail_address_address_2, bill_to_mail_address_address_3, bill_to_mail_address_city, bill_to_mail_address_country, bill_to_mail_address_country_code, bill_to_mail_address_state, bill_to_mail_address_zip, bill_to_pay_to_contact_name, bill_to_phone_1, bill_to_phone_2, bill_to_prefix, bill_to_printas, bill_to_url_1, bln_bill_to_visible, bln_contact_visible, bln_cust_email_optin, bln_do_not_process_vat, bln_has_posted_rev_rec, bln_retain_age_released, bln_ship_to_visible, bln_system_generated, contact_cell_phone, contact_company_name, contact_contact_name, contact_email_1, contact_email_2, contact_fax, contact_first_name, contact_initial, contact_last_name, contact_mail_address_address_1, contact_mail_address_address_2, contact_mail_address_address_3, contact_mail_address_city, contact_mail_address_country, contact_mail_address_country_code, contact_mail_address_state, contact_mail_address_zip, contact_phone_1, contact_print_as, contact_tax_group, contact_url_1, country_of_ship_to_contact, currency, cust_message_message, customer_name, delivery_options, description, description_2, doc_number, dte_exch_rate, dte_when_discount, dte_when_due, dte_when_paid, dte_when_posted, dts_src_created, dts_src_modified, due_in_days, dunning_count, exchange_rate, mega_entity_name, module_key, pr_batch, raw_state, record_type, record_url, retain_age_percentage, ship_to_cell_phone, ship_to_company_name, ship_to_contact_name, ship_to_email_1, ship_to_email_2, ship_to_fax, ship_to_first_name, ship_to_initial, ship_to_last_name, ship_to_mail_address_address_1, ship_to_mail_address_address_2, ship_to_mail_address_address_3, ship_to_mail_address_city, ship_to_mail_address_country, ship_to_mail_address_country_code, ship_to_mail_address_state, ship_to_mail_address_zip, ship_to_phone_1, ship_to_prefix, ship_to_print_as, ship_to_return_to_contact_name, ship_to_tax_group_name, ship_to_url_1, status, tax_entity_number, tax_reg_id_summary, tax_reverse_status, tax_summary, term_name, term_value
        from {{ ref('invoice')}}  
        where src_sys_key='int'
    ),
    entity as (
        select record_id, id, display_name, name
        from {{ source('portal', 'entities') }}
        where _fivetran_deleted = false
    ),
    currency_conversion as (
        select 
            frm_curr, 
            to_curr, 
            date, 
            fx_rate_mul
        from {{ ref("ref_fx_rates_timeseries") }}  as cc
        where frm_curr in (select currency from {{ ref("currencies_active") }})
        and to_curr in (select currency from {{ ref("currencies_active") }})
    )
select 
    inv.key,
    inv.key_customer,
    inv.key_entity,
    inv.bill_back_template_key,
    inv.bill_to_tax_id,
    inv.billto_pay_to_key,
    inv.contact_tax_id,
    inv.src_created_by,
    inv.created_by_login_id,
    inv.cust_message_id,
    inv.cust_message_key,
    inv.doc_hdr_key,
    inv.exch_rate_type_id,
    entity.display_name as entity_id,
    inv.entity_id as int_entity_id,
    inv.key_entity as int_entity_key,
    inv.modified_by_login_id,
    inv.src_modified_by,
    inv.pr_batch_key,
    inv.record_id,
    inv.ship_to_tax_group_id,
    inv.ship_to_tax_id,
    inv.shiptoreturntokey,
    inv.sup_doc_id,
    inv.tax_solution_id,
    inv.term_key,
    inv.dts_au_when_created,
    inv.base_currency as currency_iso_code_entity,
    inv.currency as currency_iso_code_original,
    coalesce(inv.dte_exch_rate, inv.dte_when_posted) as dte_exch_rate,
    cast(ifnull(cc_to_usd.fx_rate_mul,1) as number(38,6)) as conversion_rate_usd,
    ifnull(cast(inv.amt_total_due as number(38,2)),0) as amt_total_due_entity,
    ifnull(cast(amt_total_due_entity * conversion_rate_usd as number(38,2)),0) as amt_total_due_usd,
    ifnull(cast(inv.amt_total_entered as number(38,2)),0) as amt_total_entered_entity,
    ifnull(cast(amt_total_entered_entity * conversion_rate_usd as number(38,2)),0) as amt_total_entered_usd,
    ifnull(cast(inv.amt_total_paid as number(38,2)),0) as amt_total_paid_entity,
    ifnull(cast(amt_total_paid_entity * conversion_rate_usd as number(38,2)),0) as amt_total_paid_usd,
    ifnull(cast(inv.qty_total_retained as number(38,0)),0) as qty_total_retained,
    ifnull(cast(inv.qty_total_selected as number(38,0)),0) as qty_total_selected,
    ifnull(cast(inv.amt_trx_entity_due as number(38,2)),0) as amt_trx_entity_due,
    ifnull(cast(inv.qty_trx_total_discount_applied as number(38,2)),0) as qty_trx_total_discount_applied,
    ifnull(cast(inv.amt_trx_total_due as number(38,2)),0) as amt_trx_total_due,
    ifnull(cast(inv.amt_trx_total_entered as number(38,2)),0) as amt_trx_total_entered,
    ifnull(cast(inv.amt_trx_total_paid as number(38,2)),0) as amt_trx_total_paid,
    ifnull(cast(inv.qty_trx_total_released as number(38,0)),0) as qty_trx_total_released,
    ifnull(cast(inv.qty_trx_total_retained as number(38,0)),0) as qty_trx_total_retained,
    ifnull(cast(inv.qty_trx_total_selected as number(38,0)),0) as qty_trx_total_selected,
    inv.bill_to_cell_phone,
    inv.bill_to_company_name,
    inv.bill_to_contact_name,
    inv.bill_to_email_1,
    inv.bill_to_email_2,
    inv.bill_to_fax,
    inv.bill_to_first_name,
    inv.bill_to_initial,
    inv.bill_to_last_name,
    inv.bill_to_mail_address_address_1,
    inv.bill_to_mail_address_address_2,
    inv.bill_to_mail_address_address_3,
    inv.bill_to_mail_address_city,
    inv.bill_to_mail_address_country,
    inv.bill_to_mail_address_country_code,
    inv.bill_to_mail_address_state,
    inv.bill_to_mail_address_zip,
    inv.bill_to_pay_to_contact_name,
    inv.bill_to_phone_1,
    inv.bill_to_phone_2,
    inv.bill_to_prefix,
    inv.bill_to_printas,
    inv.bill_to_url_1,
    inv.bln_bill_to_visible,
    inv.bln_contact_visible,
    inv.bln_cust_email_optin,
    inv.bln_do_not_process_vat,
    inv.bln_has_posted_rev_rec,
    inv.bln_retain_age_released,
    inv.bln_ship_to_visible,
    inv.bln_system_generated,
    inv.contact_cell_phone,
    inv.contact_company_name,
    inv.contact_contact_name,
    inv.contact_email_1,
    inv.contact_email_2,
    inv.contact_fax,
    inv.contact_first_name,
    inv.contact_initial,
    inv.contact_last_name,
    inv.contact_mail_address_address_1,
    inv.contact_mail_address_address_2,
    inv.contact_mail_address_address_3,
    inv.contact_mail_address_city,
    inv.contact_mail_address_country,
    inv.contact_mail_address_country_code,
    inv.contact_mail_address_state,
    inv.contact_mail_address_zip,
    inv.contact_phone_1,
    inv.contact_print_as,
    inv.contact_tax_group,
    inv.contact_url_1,
    inv.country_of_ship_to_contact,
    inv.cust_message_message,
    inv.customer_name,
    inv.delivery_options,
    inv.description,
    inv.description_2,
    inv.doc_number,
    
    inv.dte_when_discount,
    inv.dte_when_due,
    inv.dte_when_paid,
    inv.dte_when_posted,
    inv.dts_src_created,
    inv.dts_src_modified,
    inv.due_in_days,
    inv.dunning_count,
    inv.exchange_rate,
    entity.name as entity_name,
    inv.mega_entity_name,
    inv.module_key,
    inv.pr_batch,
    inv.raw_state,
    inv.record_type,
    inv.record_url,
    inv.retain_age_percentage,
    inv.ship_to_cell_phone,
    inv.ship_to_company_name,
    inv.ship_to_contact_name,
    inv.ship_to_email_1,
    inv.ship_to_email_2,
    inv.ship_to_fax,
    inv.ship_to_first_name,
    inv.ship_to_initial,
    inv.ship_to_last_name,
    inv.ship_to_mail_address_address_1,
    inv.ship_to_mail_address_address_2,
    inv.ship_to_mail_address_address_3,
    inv.ship_to_mail_address_city,
    inv.ship_to_mail_address_country,
    inv.ship_to_mail_address_country_code,
    inv.ship_to_mail_address_state,
    inv.ship_to_mail_address_zip,
    inv.ship_to_phone_1,
    inv.ship_to_prefix,
    inv.ship_to_print_as,
    inv.ship_to_return_to_contact_name,
    inv.ship_to_tax_group_name,
    inv.ship_to_url_1,
    inv.status,
    inv.tax_entity_number,
    inv.tax_reg_id_summary,
    inv.tax_reverse_status,
    inv.tax_summary,
    inv.term_name,
    inv.term_value
from invoice inv
left join entity on inv.key_entity = entity.id
left join currency_conversion as cc_to_usd on (
                        cc_to_usd.frm_curr = currency_iso_code_original
                        and cc_to_usd.to_curr = 'USD'
                        and cc_to_usd.date = (case
                                                when coalesce(inv.dte_exch_rate, inv.dte_when_posted) < '2016-01-02' then '2016-01-04' -- earliest date we have is 1/4/2016
                                                else coalesce(inv.dte_exch_rate, inv.dte_when_posted)
                                            end)
                    )