version: 2

sources:
  - name: ukg_pro
    database: fivetran_database
    schema: ukg_pro
    tables:
      - name: company
      - name: compensation
      - name: contact
      - name: direct_deposit
      - name: earning
      - name: earning_history_base_element
      - name: education
      - name: employee
      - name: employee_change
      - name: employee_demographic
      - name: employee_job_history
      - name: employee_multiple_job
      - name: employee_security_user
      - name: employee_status
      - name: employee_supervisor
      - name: employment
      - name: employment_field_row
      - name: general_ledger
      - name: job
      - name: location
      - name: organization_level
      - name: organization_reporting_category
      - name: pay_group
      - name: pay_register
      - name: phone_number
      - name: platform_config_employment
      - name: role
      - name: tax_group
      - name: users
      - name: user_profile
