{{
    config(
        materialized="table",
        schema="consolidation",
        alias="invoice"
    )
}}

with 
    invoices as (select * from {{ source('sage_intacct', 'ar_invoice')}} where _fivetran_deleted=false)

select 
    'int' as src_sys_key,
    cast(current_timestamp as timestamp_tz) as dts_created_at,
    'invoice' as created_by,
    cast(current_timestamp as timestamp_tz) as dts_updated_at,
    'invoice' as updated_by,
    cast(current_timestamp as timestamp_tz) as dts_eff_start,
    cast('9999-12-31' as timestamp_tz ) as dts_eff_end,
    true as bln_current,
    inv.recordno as key,
    md5(inv.recordno) as hash_key,
    inv.recordno as link,
    md5(inv.recordno) as hash_link,
    inv.customerid as key_customer,
    md5(inv.customerid) as hash_key_customer,
    cast(inv.megaentitykey as varchar(5000)) as key_entity,
    md5(inv.megaentitykey) as hash_key_entity,
    cast(inv.billbacktemplatekey as varchar(5000)) as bill_back_template_key,
    nullif(inv.billto_taxid, '') as bill_to_tax_id,
    cast(inv.billtopaytokey as varchar(5000)) as billto_pay_to_key,
    nullif(inv.contact_taxid, '') as contact_tax_id,
    cast(inv.createdby as varchar(5000)) as src_created_by,
    nullif(inv.createdbyloginid,'') as created_by_login_id,
    cast(inv.custmessageid as varchar(5000)) as cust_message_id,
    cast(inv.custmessagekey as varchar(5000)) as cust_message_key,
    cast(inv.dochdrkey as varchar(5000)) as doc_hdr_key,
    cast(inv.exch_rate_type_id as varchar(5000)) as exch_rate_type_id,
    inv.megaentityid as entity_id,
    nullif(inv.modifiedbyloginid,'') as modified_by_login_id,
    cast(inv.modifiedby as varchar(5000)) as src_modified_by,
    cast(inv.prbatchkey as varchar(5000)) as pr_batch_key,
    inv.recordid as record_id,
    cast(inv.shipto_taxgroup_recordno as varchar(5000)) as ship_to_tax_group_id,
    cast(inv.shipto_taxid as varchar(5000)) as ship_to_tax_id,
    cast(inv.shiptoreturntokey as varchar(5000)) as shiptoreturntokey,
    nullif(inv.supdocid,'') as sup_doc_id,
    nullif(inv.taxsolutionid, '') as tax_solution_id,
    cast(inv.termkey as varchar(5000)) as term_key,
    inv.auwhencreated as dts_au_when_created,
    nullif(inv.basecurr, '') as base_currency,
    nullif(inv.billto_cellphone, '') as bill_to_cell_phone,
    nullif(inv.billto_companyname, '') as bill_to_company_name,
    nullif(inv.billto_contactname, '') as bill_to_contact_name,
    nullif(inv.billto_email_1, '') as bill_to_email_1,
    nullif(inv.billto_email_2, '') as bill_to_email_2,
    nullif(inv.billto_fax, '') as bill_to_fax,
    nullif(inv.billto_firstname, '') as bill_to_first_name,
    nullif(inv.billto_initial, '') as bill_to_initial,
    nullif(inv.billto_lastname, '') as bill_to_last_name,
    nullif(inv.billto_mailaddress_address_1, '') as bill_to_mail_address_address_1,
    nullif(inv.billto_mailaddress_address_2, '') as bill_to_mail_address_address_2,
    nullif(inv.billto_mailaddress_address_3, '') as bill_to_mail_address_address_3,
    nullif(inv.billto_mailaddress_city, '') as bill_to_mail_address_city,
    nullif(inv.billto_mailaddress_country, '') as bill_to_mail_address_country,
    nullif(inv.billto_mailaddress_countrycode, '') as bill_to_mail_address_country_code,
    nullif(inv.billto_mailaddress_state, '') as bill_to_mail_address_state,
    nullif(inv.billto_mailaddress_zip, '') as bill_to_mail_address_zip,
    nullif(inv.billto_phone_1, '') as bill_to_phone_1,
    nullif(inv.billto_phone_2, '') as bill_to_phone_2,
    nullif(inv.billto_prefix, '') as bill_to_prefix,
    nullif(inv.billto_printas, '') as bill_to_printas,
    nullif(inv.billto_url_1, '') as bill_to_url_1,
    nullif(inv.billto_visible,false) as bln_bill_to_visible,
    nullif(inv.billtopaytocontactname, '') as bill_to_pay_to_contact_name,
    nullif(inv.contact_cellphone, '') as contact_cell_phone,
    nullif(inv.contact_companyname, '') as contact_company_name,
    nullif(inv.contact_contactname, '') as contact_contact_name,
    nullif(inv.contact_email_1, '') as contact_email_1,
    nullif(inv.contact_email_2, '') as contact_email_2,
    nullif(inv.contact_fax, '') as contact_fax,
    nullif(inv.contact_firstname, '') as contact_first_name,
    nullif(inv.contact_initial, '') as contact_initial,
    nullif(inv.contact_lastname, '') as contact_last_name,
    nullif(inv.contact_mailaddress_address_1, '') as contact_mail_address_address_1,
    nullif(inv.contact_mailaddress_address_2, '') as contact_mail_address_address_2,
    nullif(inv.contact_mailaddress_address_3, '') as contact_mail_address_address_3,
    nullif(inv.contact_mailaddress_city, '') as contact_mail_address_city,
    nullif(inv.contact_mailaddress_country, '') as contact_mail_address_country,
    nullif(inv.contact_mailaddress_countrycode, '') as contact_mail_address_country_code,
    nullif(inv.contact_mailaddress_state, '') as contact_mail_address_state,
    nullif(inv.contact_mailaddress_zip, '') as contact_mail_address_zip,
    nullif(inv.contact_phone_1, '') as contact_phone_1,
    nullif(inv.contact_printas, '') as contact_print_as,
    nullif(inv.contact_url_1, '') as contact_url_1,
    nullif(inv.contact_visible, false) as bln_contact_visible,
    nullif(inv.contacttaxgroup, '') as contact_tax_group,
    nullif(inv.country_of_shipto_contact, '') as country_of_ship_to_contact,
    nullif(inv.currency, '') as currency,
    nullif(inv.custemailoptin, false) as bln_cust_email_optin,
    nullif(inv.custmessage_message, '') as cust_message_message,
    nullif(inv.customername, '') as customer_name,
    nullif(inv.delivery_options, '') as delivery_options,
    nullif(inv.description, '') as description,
    nullif(inv.description_2, '') as description_2,
    nullif(inv.do_not_process_vat, false) as bln_do_not_process_vat,
    nullif(inv.docnumber, '') as doc_number,
    inv.due_in_days as due_in_days,
    inv.dunningcount as dunning_count,
    inv.exch_rate_date as dte_exch_rate,
    cast(inv.exchange_rate as number(38,17)) as exchange_rate,
    inv.haspostedrevrec as bln_has_posted_rev_rec,
    nullif(inv.megaentityname,'') as mega_entity_name,
    inv.modulekey as module_key,
    nullif(inv.prbatch,'') as pr_batch,
    nullif(inv.rawstate,'') as raw_state,
    nullif(inv.record_url,'') as record_url,
    nullif(inv.recordtype,'') as record_type,
    inv.retainagepercentage as retain_age_percentage,
    inv.retainagereleased as bln_retain_age_released,
    inv.shipto_cellphone as ship_to_cell_phone,
    nullif(inv.shipto_companyname, '') as ship_to_company_name,
    nullif(inv.shipto_contactname, '') as ship_to_contact_name,
    nullif(inv.shipto_email_1, '') as ship_to_email_1,
    nullif(inv.shipto_email_2, '') as ship_to_email_2,
    nullif(inv.shipto_fax, '') as ship_to_fax,
    nullif(inv.shipto_firstname, '') as ship_to_first_name,
    nullif(inv.shipto_initial, '') as ship_to_initial,
    nullif(inv.shipto_lastname, '') as ship_to_last_name,
    nullif(inv.shipto_mailaddress_address_1, '') as ship_to_mail_address_address_1,
    nullif(inv.shipto_mailaddress_address_2, '') as ship_to_mail_address_address_2,
    nullif(inv.shipto_mailaddress_address_3, '') as ship_to_mail_address_address_3,
    nullif(inv.shipto_mailaddress_city, '') as ship_to_mail_address_city,
    nullif(inv.shipto_mailaddress_country, '') as ship_to_mail_address_country,
    nullif(inv.shipto_mailaddress_countrycode, '') as ship_to_mail_address_country_code,
    nullif(inv.shipto_mailaddress_state, '') as ship_to_mail_address_state,
    nullif(inv.shipto_mailaddress_zip, '') as ship_to_mail_address_zip,
    nullif(inv.shipto_phone_1, '') as ship_to_phone_1,
    nullif(inv.shipto_prefix, '') as ship_to_prefix,
    nullif(inv.shipto_printas, '') as ship_to_print_as,
    nullif(inv.shipto_taxgroup_name, '') as ship_to_tax_group_name,
    nullif(inv.shipto_url_1, '') as ship_to_url_1,
    nullif(inv.shipto_visible, false) as bln_ship_to_visible,
    nullif(inv.shiptoreturntocontactname, '') as ship_to_return_to_contact_name,
    nullif(inv.state, '') as status,
    nullif(inv.systemgenerated, false) as bln_system_generated,
    nullif(inv.tax_entity_number, '') as tax_entity_number,
    nullif(inv.tax_reg_id_summary, '') as tax_reg_id_summary,
    nullif(inv.tax_reverse_status, '') as tax_reverse_status,
    nullif(inv.tax_summary, '') as tax_summary,
    nullif(inv.termname, '') as term_name,
    nullif(inv.termvalue, '') as term_value,
    cast(inv.totaldue as number(38,17)) as amt_total_due,
    cast(inv.totalentered as number(38,17)) as amt_total_entered,
    cast(inv.totalpaid as number(38,17)) as amt_total_paid,
    cast(inv.totalretained as number(38,0)) as amt_total_retained,
    cast(inv.totalselected as number(38,0)) as amt_total_selected,
    cast(inv.trx_entitydue as number(38,17)) as amt_trx_entity_due,
    cast(inv.trx_totaldiscountapplied as number(38,0)) as amt_trx_total_discount_applied,
    cast(inv.trx_totaldue as number(38,17)) as amt_trx_total_due,
    cast(inv.trx_totalentered as number(38,17)) as amt_trx_total_entered,
    cast(inv.trx_totalpaid as number(38,17)) as amt_trx_total_paid,
    cast(inv.trx_totalreleased as number(38,0)) as amt_trx_total_released,
    cast(inv.trx_totalretained as number(38,0)) as amt_trx_total_retained,
    cast(inv.trx_totalselected as number(38,0)) as amt_trx_total_selected,
    cast(inv.whencreated as timestamp_tz) as dts_src_created,
    inv.whendiscount as dte_when_discount,
    inv.whendue as dte_when_due,
    inv.whenmodified as dts_src_modified,
    inv.whenpaid as dte_when_paid,
    inv.whenposted as dte_when_posted,
from invoices inv