{{
    config(
        materialized="table",
        schema="consolidation",
        alias="sales_contact"
    )
}}

with
    sfc_contacts as (
        select * from {{ source("salesforce", "contact") }} where _fivetran_deleted = false
    ),
    final as (
        select 
            'sfc' as src_sys_key,
            cast(current_timestamp as timestamp_tz) as dts_created_at,
            '{{ this.name }}' as created_by,
            cast(current_timestamp as timestamp_tz) as dts_updated_at,
            '{{ this.name }}' as updated_by,
            cast(current_timestamp as timestamp_tz) as dts_eff_start,
            cast('9999-12-31' as timestamp_tz ) as dts_eff_end,
            true as bln_current,
            sfc.id as key,
            md5(sfc.id) as hash_key,
            sfc.id as link,
            md5(sfc.id) as hash_link,
            sfc.account_id as key_account,
            md5(sfc.account_id) as hash_key_account,
            sfc.pse_region_c as key_location,
            md5(sfc.pse_region_c) as hash_key_location,
            sfc.owner_id as key_owner,
            md5(sfc.owner_id) as hash_key_owner,
            sfc.pse_practice_c as key_practice,
            md5(sfc.pse_practice_c) as hash_key_practice,
            sfc.reports_to_id as key_supervisor,
            md5(sfc.reports_to_id) as hash_key_supervisor,
            sfc.pse_salesforce_user_c as key_user,
            md5(sfc.pse_salesforce_user_c) as hash_key_user,
            sfc.pse_actuals_last_updated_by_c as actuals_last_updated_by_id,
            sfc.external_id_c as external_id,
            sfc.master_record_id as master_record_id,
            sfc.record_type_id as record_type_id,
            sfc.created_by_id as src_created_by_id,
            sfc.last_modified_by_id as src_modified_by_id,
            sfc.pse_utilization_last_updated_by_c as utilization_last_updated_by_id,
            sfc.active_c as bln_is_active,
            sfc.base_team_c as base_team,
            sfc.billing_category_c as billing_category,
            sfc.biography_c as biography,
            sfc.pse_allow_timecards_without_assignment_c as bln_allow_timecards_without_assignment,
            sfc.do_not_call as bln_do_not_call,
            sfc.pse_exclude_from_resource_planner_c as bln_exclude_from_resource_planner,
            sfc.has_opted_out_of_email as bln_has_opted_out_of_email,
            sfc.pse_action_calculate_utilization_c as bln_is_action_calculate_utilization,
            sfc.pse_action_update_current_time_period_c as bln_is_action_update_current_time_period,
            sfc.is_email_bounced as bln_is_email_bounced,
            sfc.pse_external_resource_c as bln_is_external_resource,
            sfc.is_part_time_resource_c as bln_is_part_time_resource,
            sfc.qualified_project_manager_c as bln_is_qualified_project_manager,
            sfc.pse_is_resource_c as bln_is_resource,
            sfc.pse_is_resource_active_c as bln_is_resource_active,
            sfc.sync_to_marketo_c as bln_is_synced_to_marketo,
            sfc.blog_subscription_c as blog_subscription,
            sfc.conferenceor_show_c as conferenceor_show,
            sfc.currency_iso_code as currency_iso_code,
            sfc.department as department,
            sfc.description as description,
            sfc.last_activity_date as dte_last_activity,
            sfc.date_of_industry_experience_c as dte_of_industry_experience,
            sfc.pse_actuals_last_update_date_c as dts_actuals_last_updated,
            sfc.email_bounced_date as dts_email_bounced,
            sfc.legacy_created_date_c as dts_legacy_created,
            sfc.mkto_71_acquisition_date_c as dts_marketo_acquisition,
            sfc.created_date as dts_src_created,
            sfc.last_modified_date as dts_src_modified,
            sfc.system_modstamp as dts_system_modstamp,
            sfc.pse_utilization_last_update_date_c as dts_utilization_last_updated,
            sfc.email as email,
            sfc.email_bounced_reason as email_bounced_reason,
            sfc.employee_pay_type_c as employee_pay_type,
            sfc.employee_type_c as employee_type,
            sfc.fax as fax,
            sfc.first_name as first_name,
            cast(sfc.pse_historical_utilization_target_hours_c as number(38,17)) as historical_utilization_target_hours,
            sfc.home_phone as home_phone,
            sfc.industry_c as industry,
            sfc.pse_api_resource_correlation_id_c as intacct_employee_id,
            sfc.interested_business_areas_c as interested_business_areas,
            sfc.last_name as last_name,
            sfc.lead_source as lead_source,
            sfc.legacy_lead_source_c as legacy_lead_source,
            sfc.legal_basis_processing_data_c as legal_basis_processing_data,
            sfc.linked_in_profile_url_c as linked_in_profile_url,
            sfc.mailing_city as mailing_city,
            sfc.mailing_country as mailing_country,
            sfc.mailing_country_code as mailing_country_code,
            sfc.mailing_postal_code as mailing_postal_code,
            sfc.mailing_state as mailing_state,
            sfc.mailing_state_code as mailing_state_code,
            sfc.mailing_street as mailing_street,
            sfc.mkto_71_acquisition_program_c as marketo_acquisition_program,
            cast(sfc.mkto_71_lead_score_c as number(38,17)) as marketo_lead_score,
            sfc.middle_name as middle_name,
            sfc.mobile_phone as mobile_phone,
            sfc.name as name,
            sfc.original_source_c as original_source,
            sfc.phone as phone,
            sfc.pse_group_c as pse_group,
            sfc.pse_last_date_c as pse_last_date,
            sfc.pse_start_date_c as pse_start_date,
            sfc.pse_resource_role_c as resource_role,
            sfc.salutation as salutation,
            sfc.suffix as suffix,
            sfc.title as title,
            sfc.pse_work_calendar_c as work_calendar_id
        from sfc_contacts sfc
    )

select * from final