with
    job_history as (select * from {{ source('ukg_pro', 'employee_job_history') }} where _fivetran_deleted = false),
    company as (select * from {{ source('ukg_pro', 'company') }} where _fivetran_deleted = false)

select 
    'ukg' as src_sys_key,
    cast(current_timestamp as timestamp_tz) as dts_created_at,
    '{{ this.name }}' as created_by,
    cast(current_timestamp as timestamp_tz) as dts_updated_at,
    '{{ this.name }}' as updated_by,
    cast(current_timestamp as timestamp_tz) as dts_eff_start,
    cast('9999-12-31' as timestamp_tz ) as dts_eff_end,
    true as bln_current,
    job_history.id as key,
    md5(job_history.id) as hash_key,
    job_history.id as link,
    md5(job_history.id) as hash_link,
    job_history.employee_id as key_employee,
    md5(job_history.employee_id) as hash_key_employee,
    concat(employee_id,':',company_id) as key_employee_company,
    md5(concat(employee_id,':',company_id)) as hash_key_employee_company,
    job_history.company_id as key_company,
    md5(job_history.company_id) as hash_key_company,
    job_history.organization_level_1_id as key_practice,
    md5(job_history.organization_level_1_id) as hash_key_practice,
    job_history.organization_level_2_id as key_department,
    md5(job_history.organization_level_2_id) as hash_key_department,
    job_history.organization_level_3_id as key_base_team,
    md5(job_history.organization_level_3_id) as hash_key_base_team,
    job_history.organization_level_4_id as key_intacct_location,
    md5(job_history.organization_level_4_id) as hash_key_intacct_location,
    job_history.supervisor_id as key_supervisor,
    md5(job_history.supervisor_id) as hash_key_supervisor,
    cast(job_history.created_by_user_id as varchar(5000)) as src_created_by_id,
    company.code as company_code,
    upper(company.currency_code) as currency_code,
    job_history.employee_status as employee_status_code,
    job_history.employee_type as employee_type_id,
    job_history.home_company_id as home_company_id,
    job_history.job_id as job_id,
    job_history.location_id as location_id,
    job_history.pay_group_id as pay_group_id,
    cast(job_history.annual_salary as number(38,17)) as annual_salary,
    cast(job_history.date_time_created as timestamp_tz) as dts_src_created,
    job_history.flsa_category as flsa_category_id,
    case when job_history.full_time_or_part_time = 'F' then true else false end as bln_is_full_time,
    cast(job_history.hourly_pay_rate as number(38,17)) as hourly_pay_rate,
    cast(job_history.integration_effective_date as date) as dte_integration_effective,
    job_history.is_job_change as bln_is_job_change,
    job_history.is_orgchange as bln_is_org_change,
    job_history.is_outside_guidelines as bln_is_outside_guidelines,
    job_history.is_outside_range as bln_is_outside_range,
    job_history.is_promotion as bln_is_promotion,
    job_history.is_rate_change as bln_is_rate_change,
    job_history.is_system as bln_is_system,
    job_history.is_transfer as bln_is_transfer,
    job_history.is_viewable_by_employee as bln_is_viewable_by_employee,
    job_history._fivetran_synced as dts_last_synced,
    cast(job_history.job_effective_date as date) as dte_job_effective,
    job_history.job_title as job_title,
    job_history.notes as notes,
    cast(job_history.number_of_payments as number(38,17)) as number_of_payments,
    cast(job_history.other_rate_1 as number(38,17)) as other_rate_1,
    cast(job_history.other_rate_2 as number(38,17)) as other_rate_2,
    cast(job_history.other_rate_3 as number(38,17)) as other_rate_3,
    cast(job_history.other_rate_4 as number(38,17)) as other_rate_4,
    job_history.pay_period_code as pay_period_code,
    cast(job_history.percent_change as number(38,17)) as percent_change,
    cast(job_history.period_pay_rate as number(38,17)) as period_pay_rate,
    cast(job_history.piece_pay_rate as number(38,17)) as piece_pay_rate,
    job_history.project_code as project_code,
    job_history.reason_code as reason_code,
    job_history.salary_grade as salary_grade,
    case when job_history.salary_or_hourly = 'S' then true else false end as bln_is_salary,
    cast(job_history.scheduled_annual_hours as number(38,17)) as scheduled_annual_hours,
    cast(job_history.scheduled_full_time_equivalency as number(38,17)) as scheduled_full_time_equivalency,
    cast(job_history.scheduled_work_hours as number(38,17)) as scheduled_work_hours,
    job_history.shift_code as shift_code,
    job_history.shift_group_code as shift_group_code,
    cast(job_history.step_number as number(38,17)) as step_number,
    job_history.supervisor_name_first as supervisor_name_first,
    job_history.supervisor_name_last as supervisor_name_last,
    job_history.supervisor_not_in_list as bln_supervisor_not_in_list,
    job_history.use_pay_scales as bln_use_pay_scales,
    cast(job_history.weekly_hours as number(38,17)) as weekly_hours,
    cast(job_history.weekly_pay_rate as number(38,17)) as weekly_pay_rate
from job_history
left join company on job_history.company_id = company.id