{{
    config(
        schema="dataconsumption",
        materialized="table",
        alias="payroll",
    )
}}

with 
    timesheet       as (select * from {{ ref('dim_timesheet')}} ),
    timesheet_entry as (select * from {{ ref('dim_timesheet_entry')}} ),
    time_type_phase_codes   as (select * from {{ ref("time_type_phase_codes") }}),
    dim_employee as (select * from {{ ref("dim_employee") }}),
final as (
    select
        current_timestamp as dts_created_at,
        '{{ this.name }}' as created_by,
        current_timestamp as dts_updated_at,
        '{{ this.name }}' as updated_by,
        te.key,
        ts.key_location,
        ts.key_department,
        ts.key_entity,
        ts.key_employee,
        ts.department_name,
        ts.location_name,
        ts.entity_name,
        e.key_base_team,
        e.key_employee_type,
        ts.employee_name,
        ts.employee_department_id,
        ts.employee_id_intacct,
        ts.employee_id,
        ts.employee_location_id,
        ts.src_created_by_id,
        ts.src_modified_by_id,
        ts.sup_doc_id,
        ts.sup_doc_key,
        ts.entity_id,
        ts.bln_cost_actual,
        ts.config,
        ts.description,
        ts.dte_gl_post,
        ts.dte_src_end,
        ts.dte_src_start,
        ts.dts_src_created,
        ts.dts_src_modified,
        ts.employee_first_name,
        ts.employee_last_name,
        ts.hours_in_day,
        ts.mega_entity_name,
        ts.method,
        e.pay_type_name,
        ts.state_worked,
        ts.status,
        ts.uom,
        te.key_timesheet,
        te.key_practice_area,
        te.key_project,
        te.practice_area_name,
        te.project_id,
        te.project_name,
        te.currency_iso_code,
        te.employee_name_lf,
        te.billu_acct_key,
        te.customer_id,
        te.department_id,
        te.department_key,
        te.employee_earning_type_key,
        te.item_id,
        te.labor_gl_batch_key,
        te.location_id,
        te.location_key,
        te.non_billnu_acct_key,
        te.non_billu_acct_key,
        te.stat_gl_batch_key,
        te.stat_journal_key,
        te.task_id,
        te.amt_labor_gl_entry,
        te.amt_labor_glentry_trx,
        te.amt_stat_gl_entry,
        te.bill_rate,
        te.bln_billable,
        te.bln_billed,
        te.customer_name,
        te.dte_entry,
        te.dte_src_created,
        te.dte_src_modified,
        te.item_name,
        te.labor_gl_entry_cost_rate,
        te.labor_gl_entry_line_no,
        te.labor_gl_entry_offset_line_no,
        te.line_no,
        te.notes,
        te.qty,
        te.qty_salesforce,
        te.qty_approved,
        te.qty_approved_billable,
        te.qty_approved_non_billable,
        te.qty_approved_non_utilized,
        te.qty_approved_utilized,
        te.qty_billable,
        te.qty_non_billable,
        te.qty_non_utilized,
        te.qty_utilized,
        te.record_url,
        te.stat_gl_entry_line_no,
        te.state,
        te.task_key,
        te.timesheet_entry_ref,
        te.task_name,
        e.base_team_name,
        e.state_name,
        e.country_name,
        e.ukg_employee_number,
        e.employee_type_name,
        case when te.task_name in (select phase_code from time_type_phase_codes where time_type ='sicktime') then '1'
            when te.task_name in (select phase_code from time_type_phase_codes where time_type ='vacholtime') then '2'
            when te.task_name in (select phase_code from time_type_phase_codes where time_type ='dulltime') then '3'
            when te.task_name in (select phase_code from time_type_phase_codes where time_type ='tvltime') then '4'
            when te.task_name in (select phase_code from time_type_phase_codes where time_type ='excludepayroll') then '5'
        else '0' end as time_type_ind 
    from timesheet ts
    inner join timesheet_entry te on te.key_timesheet = ts.key
    left join dim_employee e on e.key = te.key_employee
)

select * from final