{{
    config(
        materialized="table",
        schema="consolidation",
        alias="sales_lead"
    )
}}
with 
    lead as (select * from {{ source("salesforce", "lead") }} where _fivetran_deleted = false)
select 
    'sfc' as src_sys_key,
    cast(current_timestamp as timestamp_tz) as dts_created_at,
    '{{ this.name }}' as created_by,
    cast(current_timestamp as timestamp_tz) as dts_updated_at,
    '{{ this.name }}' as updated_by,
    cast(current_timestamp as timestamp_tz) as dts_eff_start,
    cast('9999-12-31' as timestamp_tz ) as dts_eff_end,
    true as bln_current,
    lead.id as key,
    md5(lead.id) as hash_key,
    lead.id as link,
    md5(lead.id) as hash_link,
    lead.location_new_c as key_location,
    md5(lead.location_new_c) as hash_key_location,
    lead.owner_id as key_owner,
    md5(lead.owner_id) as hash_key_owner,
    lead.practice_area_c as key_practice_area,
    md5(lead.practice_area_c) as hash_key_practice_area,
    lead.converted_account_id as converted_account_id,
    lead.converted_contact_id as converted_contact_id,
    lead.converted_opportunity_id as converted_opportunity_id,
    lead.external_id_c as external_id,
    lead.created_by_id as src_created_by_id,
    lead.last_modified_by_id as src_modified_by_id,
    lead.additional_business_areas_c as additional_business_areas,
    lead.additional_lead_sources_c as additional_lead_sources,
    lead.budget_c as amt_budget,
    lead.bypass_opportunity_validation_c as bln_bypass_opportunity_validation,
    lead.convert_c as bln_convert,
    lead.currency_confirmed_c as bln_currency_confirmed,
    lead.has_opted_out_of_email as bln_has_opted_out_of_email,
    lead.is_converted as bln_is_converted,
    lead.created_from_lead_c as bln_is_created_from_lead,
    lead.marketing_qualified_lead_c as bln_is_marketing_qualified_lead,
    lead.sync_to_marketo_c as bln_is_synced_to_marketo,
    lead.is_unread_by_owner as bln_is_unread_by_owner,
    lead.city as city,
    lead.company as company,
    lead.conferenceor_show_c as conferenceor_show,
    lead.content_theme_c as content_theme,
    lead.content_title_c as content_title,
    lead.country as country,
    lead.country_code as country_code,
    lead.currency_iso_code as currency_iso_code,
    lead.data_center_primary_business_area_c as data_center_primary_business_area,
    lead.description as description,
    lead.division_c as division,
    lead.converted_date as dte_converted,
    lead.last_activity_date as dte_last_activity,
    lead.last_transfer_date as dte_last_transfer,
    lead.email_bounced_date as dts_email_bounced,
    lead.mkto_71_acquisition_date_c as dts_marketo_acquisition_date,
    lead.created_date as dts_src_created,
    lead.last_modified_date as dts_src_modified,
    lead.system_modstamp as dts_system_modstamp,
    lead.email as email,
    lead.email_bounced_reason as email_bounced_reason,
    lead.fax as fax,
    lead.first_name as first_name,
    lead.inbound_marketing_source_c as inbound_marketing_source,
    lead.industry as industry,
    lead.last_name as last_name,
    lead.lead_source as lead_source,
    lead.legal_basis_processing_data_c as legal_basis_processing_data,
    lead.lid_linked_in_member_token_c as lid_linked_in_member_token,
    lead.life_sciences_primary_business_area_c as life_sciences_primary_business_area,
    lead.linked_in_url_c as linked_in_url,
    lead.mkto_71_acquisition_program_c as marketo_acquisition_program,
    cast(lead.mkto_71_lead_score_c as number(37,18)) as marketo_lead_score,
    lead.middle_name as middle_name,
    lead.mobile_phone as mobile_phone,
    lead.name as name,
    lead.number_of_employees as number_of_employees,
    lead.or_oe_c as or_oe,
    lead.phone as phone,
    lead.postal_code as postal_code,
    lead.primary_business_area_c as primary_business_area,
    lead.rating as rating,
    lead.reference_number_c as reference_number,
    lead.salutation as salutation,
    lead.state as state,
    lead.status as status,
    lead.street as street,
    lead.subtype_c as subtype,
    lead.suffix as suffix,
    lead.title as title,
    lead.type_c as type,
    lead.website as website
from lead