cai_bi:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: OTB26825.us-east-1
      user: CICD_SVC_USER_NONPROD
      schema: CONSOLIDATION
      private_key_path: /home/runner/.ssh/snowflake_key.pem
      threads: 4

    prd:
      type: snowflake
      account: OTB26825.us-east-1
      user: CICD_SVC_USER_PROD
      schema: CONSOLIDATION
      private_key_path: /home/runner/.ssh/snowflake_key.pem
      threads: 4
