cai_bi:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: OTB26825.us-east-1
      user: gh_dbt_service_user
      database: DEV_BI_RAW
      role: SYSADMIN
      warehouse: BI_TRANSFORM_WH
      schema: CONSOLIDATION
      private_key_path: /home/runner/.ssh/snowflake_key.pem
      threads: 4

    prd:
      type: snowflake
      account: OTB26825.us-east-1
      user: gh_dbt_service_user
      database: PROD_BI_RAW
      role: SYSADMIN
      warehouse: PROD_BI_TRANSFORM_WH
      schema: CONSOLIDATION
      private_key_path: /home/runner/.ssh/snowflake_key.pem
      threads: 4
