{{
    config(
        materialized='table',
        schema='consolidation'
    )
}}

with
    si_expenses as (select * from {{ source('sage_intacct', 'eexpenses') }} where _fivetran_deleted = false ),
    si_employee as (select * from {{ source('sage_intacct', 'employee') }} where _fivetran_deleted = false ),
    sf_expenses as (select * from {{ source('salesforce', 'pse_expense_report_c') }} where _fivetran_deleted = false ),
    sf_contact  as (select * from {{ source('salesforce', 'contact') }} where _fivetran_deleted = false ),
    sf_project  as (select * from {{ source('salesforce', 'pse_proj_c') }} where _fivetran_deleted = false ),

sage_intacct as (
    select
        'int' as src_sys_key,
        current_timestamp as dts_created_at,
        '{{ this.name }}' as created_by,
        current_timestamp as dts_updated_at,
        '{{ this.name }}' as updated_by,
        current_timestamp as dts_eff_start,
        '9999-12-31' as dts_eff_end,
        true as bln_current,
        cast(si_expenses.recordno as string) as key,
        md5(si_expenses.recordno) as hash_key,
        cast(si_expenses.psa_id as string) as link,
        md5(si_expenses.psa_id) as hash_link,
        cast(si_employee.recordno as string) as key_employeee,
        md5(si_employee.recordno) as hash_key_employee,
        cast(si_expenses.megaentitykey as string) as key_entity,
        md5(si_expenses.megaentitykey) as hash_key_entity,
        null as approver_id,
        null as assignment_id,
        null as contact_id,
        cast(si_expenses.employeeid as string) as employee_id,
        cast(si_expenses.megaentityid as string) as entity_id,
        null as project_id,
        cast(si_expenses.recordid as string) as record_id,
        cast(si_expenses.createdby as string) as src_created_by,
        cast(si_expenses.modifiedby as string) as src_modified_by,
        cast(si_expenses.taxsolutionid as string) as tax_solution_id,
        null as amt_total_billable,
        null as amt_total_non_reimbursement,
        null as amt_total_reimbursement,
        null as audit_notes,
        si_expenses.basecurr as base_currency,
        null as bln_approved,
        si_expenses.prbatch_nogl as bln_pr_batch_nogl,
        si_expenses.inclusivetax as bln_inclusive_tax,
        null as bln_submitted,
        si_expenses.auwhencreated as dts_audit_when_created,
        null as dte_first_expense,
        null as dte_last_expense,
        si_expenses.whencreated as dts_src_created,
        si_expenses.whenmodified as dts_src_modified,
        si_expenses.whenpaid as dte_when_paid,
        si_expenses.whenposted as dte_when_posted,
        null as dte_when_submitted,
        si_expenses.currency as currency,
        si_expenses.description as description,
        si_expenses.ename as employee_name,
        si_expenses.firstname as first_name,
        si_expenses.lastname as last_name,
        si_expenses.megaentityname as mega_entity_name,
        si_expenses.memo as memo,
        si_expenses.prbatch as pr_batch,
        si_expenses.prbatchkey as pr_batch_key,
        si_expenses.prbatch_open as pr_batch_open,
        si_expenses.psa_url as psa_url,
        si_expenses.rawstate as raw_state,
        si_expenses.recordtype as record_type,
        si_expenses.state as state,
        null as sync_status,
        si_expenses.totaldue as total_due,
        si_expenses.totalentered as total_entered,
        si_expenses.nr_totalentered as total_nr_entered,
        si_expenses.nr_trx_totalentered as total_nr_trx_entered,
        si_expenses.totalpaid as total_paid,
        si_expenses.totalselected as total_selected,
        si_expenses.trx_totaldue as total_trx_due,
        si_expenses.trx_totalentered as total_trx_entered,
        si_expenses.trx_totalpaid as total_trx_paid
    from si_expenses
    left join si_employee on si_employee.employeeid = si_expenses.employeeid
),

salesforce as (
    select
        'sfc' as src_sys_key,
        current_timestamp as dts_created_at,
        '{{ this.name }}' as created_by,
        current_timestamp as dts_updated_at,
        '{{ this.name }}' as updated_by,
        current_timestamp as dts_eff_start,
        '9999-12-31' as dts_eff_end,
        true as bln_current,
        sf_expenses.id as key,
        md5(sf_expenses.id) as hash_key,
        sf_expenses.id as link,
        md5(sf_expenses.id) as hash_link,
        sf_expenses.pse_resource_c as key_employeee,
        md5(sf_expenses.pse_resource_c) as hash_key_employee,
        sf_project.pse_group_c as key_entity,
        md5(sf_project.pse_group_c) as hash_key_entity,
        sf_expenses.pse_approver_c as approver_id,
        sf_expenses.pse_assignment_c as assignment_id,
        sf_expenses.pse_resource_c as contact_id,
        sf_contact.pse_api_resource_correlation_id_c as employee_id,
        null as entity_id,
        sf_expenses.pse_project_c as project_id,
        sf_expenses.pse_third_party_expenses_app_report_id_c as record_id,
        sf_expenses.created_by_id as src_created_by,
        sf_expenses.last_modified_by_id as src_modified_by,
        null as tax_solution_id,
        sf_expenses.pse_total_billable_amount_c as amt_total_billable,
        sf_expenses.pse_total_non_billable_amount_c as amt_total_non_reimbursement,
        sf_expenses.pse_total_reimbursement_amount_c as amt_total_reimbursement,
        sf_expenses.pse_audit_notes_c as audit_notes,
        null as base_currency,
        sf_expenses.pse_approved_c as bln_approved,
        null as bln_pr_batch_nogl,
        null as bln_inclusive_tax,
        sf_expenses.pse_submitted_c as bln_submitted,
        null as dts_audit_when_created,
        sf_expenses.pse_first_expense_date_c as dte_first_expense,
        sf_expenses.pse_last_expense_date_c as dte_last_expense,
        sf_expenses.created_date as dts_src_created,
        sf_expenses.last_modified_date as dts_src_modified,
        sf_expenses.date_paid_c as dte_when_paid,
        sf_expenses.gl_post_date_c as dte_when_posted,
        sf_expenses.submitted_date_c as dte_when_submitted,
        sf_expenses.currency_iso_code as currency,
        sf_expenses.pse_description_c as description,
        sf_contact.name as employee_name,
        sf_contact.first_name as first_name,
        sf_contact.last_name as last_name,
        null as mega_entity_name,
        null as memo,
        null as pr_batch,
        null as pr_batch_key,
        null as pr_batch_open,
        null as psa_url,
        null as raw_state,
        null as record_type,
        sf_expenses.pse_status_c as state,
        sf_expenses.sync_status_c as sync_status,
        null as total_due,
        null as total_entered,
        null as total_nr_entered,
        null as total_nr_trx_entered,
        null as total_paid,
        null as total_selected,
        null as total_trx_due,
        null as total_trx_entered,
        null as total_trx_paid
    from sf_expenses
    left join sf_contact on sf_expenses.pse_resource_c = sf_contact.id
    left join sf_project on sf_expenses.pse_project_c = sf_project.id
),

final as (
    select
        *
    from sage_intacct
    union all
    select
        *
    from salesforce
)

select
    src_sys_key,
    cast(dts_created_at as timestamp_tz) as dts_created_at,
    created_by,
    cast(dts_updated_at as timestamp_tz) as dts_updated_at,
    updated_by,
    cast(dts_eff_start as timestamp_tz) as dts_eff_start,
    cast(dts_eff_end as timestamp_tz) as dts_eff_end,
    bln_current,
    key,
    hash_key,
    link,
    hash_link,
    key_employeee,
    hash_key_employee,
    key_entity,
    hash_key_entity,
    approver_id,
    assignment_id,
    contact_id,
    employee_id,
    entity_id,
    project_id,
    record_id,
    src_created_by,
    src_modified_by,
    tax_solution_id,
    amt_total_billable,
    amt_total_non_reimbursement,
    cast(amt_total_reimbursement as number(38, 2)) as amt_total_reimbursement,
    audit_notes,
    base_currency,
    bln_approved,
    bln_pr_batch_nogl,
    bln_inclusive_tax,
    bln_submitted,
    cast(dts_audit_when_created as timestamp_tz) as dts_audit_when_created,
    dte_first_expense,
    dte_last_expense,
    dts_src_created,
    dts_src_modified,
    cast(dte_when_paid as date) as dte_when_paid,
    cast(dte_when_posted as date) as dte_when_posted,
    cast(dte_when_submitted as date) as dte_when_submitted,
    currency,
    description,
    employee_name,
    first_name,
    last_name,
    mega_entity_name,
    memo,
    pr_batch,
    pr_batch_key,
    pr_batch_open,
    psa_url,
    raw_state,
    record_type,
    state,
    sync_status,
    cast(total_due as number(38, 2)) as total_due,
    cast(total_entered as number(38, 2)) as total_entered,
    cast(total_nr_entered as number(38, 2)) as total_nr_entered,
    cast(total_nr_trx_entered as number(38, 2)) as total_nr_trx_entered,
    cast(total_paid as number(38, 2)) as total_paid,
    cast(total_selected as number(38, 2)) as total_selected,
    cast(total_trx_due as number(38, 2)) as total_trx_due,
    cast(total_trx_entered as number(38, 2)) as total_trx_entered,
    cast(total_trx_paid as number(38, 2)) as total_trx_paid
from final
