{{
    config(
        materialized="table",
        schema="consolidation",
        alias="sales_opportunity"
    )
}}

with
    sfc_opportunity as (select * from {{ source("salesforce", "opportunity") }} where _fivetran_deleted = false),

final as (
    select
        'sfc' as src_sys_key,
        cast(current_timestamp as timestamp_tz) as dts_created_at,
        '{{ this.name }}' as created_by,
        cast(current_timestamp as timestamp_tz) as dts_updated_at,
        '{{ this.name }}' as updated_by,
        cast(current_timestamp as timestamp_tz) as dts_eff_start,
        cast('9999-12-31' as timestamp_tz ) as dts_eff_end,
        true as bln_current,
        sfc_opportunity.id as key,
        md5(sfc_opportunity.id) as hash_key,
        sfc_opportunity.id as link,
        md5(sfc_opportunity.id) as hash_link,
        sfc_opportunity.account_id as key_account,
        md5(sfc_opportunity.account_id) as hash_key_account,
        sfc_opportunity.estimate_id_c as key_estimate,
        md5(sfc_opportunity.estimate_id_c) as hash_key_estimate,
        sfc_opportunity.identified_by_c as key_identified_by,
        md5(sfc_opportunity.identified_by_c) as hash_key_identified_by,
        sfc_opportunity.owner_id as key_owner,
        md5(sfc_opportunity.owner_id) as hash_key_owner,
        sfc_opportunity.pricebook_2_id as key_price_book_entry,
        md5(sfc_opportunity.pricebook_2_id) as hash_key_price_book_entry,
        ifnull(sfc_opportunity.project_c, parent_oppty.project_c) as key_project,
        md5(ifnull(sfc_opportunity.project_c, parent_oppty.project_c)) as hash_key_project,
        sfc_opportunity.pse_parent_opportunity_c as key_parent_opportunity,
        md5(sfc_opportunity.pse_parent_opportunity_c) as hash_key_parent_opportunity,
        sfc_opportunity.pse_practice_c as key_practice,
        md5(sfc_opportunity.pse_practice_c) as hash_key_practice,
        sfc_opportunity.pse_region_c as key_location,
        md5(sfc_opportunity.pse_region_c) as hash_key_location,
        sfc_opportunity.rate_card_set_c as key_rate_card_set,
        md5(sfc_opportunity.rate_card_set_c) as hash_key_rate_card_set,
        sfc_opportunity.synced_quote_id as key_proposal,
        md5(sfc_opportunity.synced_quote_id) as hash_key_proposal,
        sfc_opportunity.campaign_id as campaign_id,
        sfc_opportunity.contact_id as contact_id,
        sfc_opportunity.estimate_id_c as estimate_id,
        sfc_opportunity.external_id_c as external_id,
        sfc_opportunity.last_amount_changed_history_id as last_amount_changed_history_id,
        sfc_opportunity.last_close_date_changed_history_id as last_close_date_changed_history_id,
        sfc_opportunity.portal_project_id_c as portal_project_id_c,
        sfc_opportunity.created_by_id as src_created_by_id,
        sfc_opportunity.last_modified_by_id as src_modified_by_id,
        sfc_opportunity.amount as amt,
        sfc_opportunity.child_opportunities_amount_c as amt_child_opportunities,
        sfc_opportunity.child_po_amount_awarded_c as amt_child_po_awarded,
        sfc_opportunity.contingency_budget_c as amt_contingency_budget,
        sfc_opportunity.expected_revenue as amt_expected_revenue,
        sfc_opportunity.labor_budget_c as amt_labor_budget,
        sfc_opportunity.other_budget_c as amt_other_budget,
        sfc_opportunity.po_amount_awarded_c as amt_po_awarded,
        sfc_opportunity.subcontractor_budget_c as amt_subcontractor_budget,
        sfc_opportunity.travel_budget_c as amt_travel_budget,
        sfc_opportunity.budget_confirmed_c as bln_budget_confirmed,
        sfc_opportunity.currency_confirmed_c as bln_currency_confirmed,
        sfc_opportunity.bypass_po_or_loi_c as bln_has_bypass_po_or_loi,
        sfc_opportunity.letter_of_intent_received_c as bln_has_letter_of_intent_received,
        sfc_opportunity.has_open_activity as bln_has_open_activity,
        sfc_opportunity.has_opportunity_line_item as bln_has_opportunity_line_item,
        sfc_opportunity.has_overdue_task as bln_has_overdue_task,
        sfc_opportunity.signed_purchase_order_c as bln_has_signed_purchase_order,
        sfc_opportunity.signed_sla_c as bln_has_signed_sla,
        sfc_opportunity.pse_is_change_request_c as bln_is_change_request,
        sfc_opportunity.is_closed as bln_is_closed,
        sfc_opportunity.converted_c as bln_is_converted,
        sfc_opportunity.is_covid_19_vaccine_c as bln_is_covid_19_vaccine,
        sfc_opportunity.created_from_lead_c as bln_is_created_from_lead,
        sfc_opportunity.mvp_c as bln_is_mvp,
        sfc_opportunity.is_on_hold_c as bln_is_on_hold,
        sfc_opportunity.is_won as bln_is_won,
        sfc_opportunity.bv_cai_proposal_no_c as bv_cai_proposal_no,
        sfc_opportunity.cai_team_engaged_in_pursuit_c as cai_team_engaged_in_pursuit,
        sfc_opportunity.closed_won_reason_c as closed_won_reason,
        sfc_opportunity.contract_type_c as contract_type,
        sfc_opportunity.currency_iso_code as currency_iso_code,
        sfc_opportunity.description as description,
        sfc_opportunity.close_date as dte_close,
        sfc_opportunity.customer_po_awarded_date_c as dte_customer_po_awarded,
        sfc_opportunity.estimated_project_end_date_c as dte_estimated_project_end,
        sfc_opportunity.estimated_project_start_date_c as dte_estimated_project_start,
        sfc_opportunity.last_activity_date as dte_last_activity,
        sfc_opportunity.proposal_submitted_date_c as dte_proposal_submitted,
        sfc_opportunity.stage_last_updated_c as dte_stage_last_updated,
        cast (sfc_opportunity.last_stage_change_date as timestamp_tz) as dts_last_stage_change,
        cast (sfc_opportunity.created_date as timestamp_tz) as dts_src_created,
        cast (sfc_opportunity.last_modified_date as timestamp_tz) as dts_src_modified,
        cast (sfc_opportunity.system_modstamp as timestamp_tz) as dts_system_modstamp,
        cast (sfc_opportunity.duration_closed_won_c as number(38,0)) as duration_closed_won,
        cast (sfc_opportunity.duration_interview_presentation_c as number(38,0)) as duration_interview_presentation,
        cast (sfc_opportunity.duration_negotiation_review_c as number(38,0)) as duration_negotiation_review,
        cast (sfc_opportunity.duration_proposal_approved_c as number(38,0)) as duration_proposal_approved,
        cast (sfc_opportunity.duration_proposal_development_c as number(38,0)) as duration_proposal_development,
        cast (sfc_opportunity.duration_proposal_submitted_c as number(38,0)) as duration_proposal_submitted,
        cast (sfc_opportunity.duration_prospecting_qualification_c as number(38,0)) as duration_prospecting_qualification,
        cast (sfc_opportunity.duration_solution_development_c as number(38,0)) as duration_solution_development,
        sfc_opportunity.fiscal as fiscal,
        sfc_opportunity.fiscal_quarter as fiscal_quarter,
        sfc_opportunity.fiscal_year as fiscal_year,
        sfc_opportunity.forecast_category as forecast_category,
        sfc_opportunity.forecast_category_name as forecast_category_name,
        sfc_opportunity.kare_c as kare,
        sfc_opportunity.lead_source as lead_source,
        sfc_opportunity.loss_reason_c as loss_reason_c,
        sfc_opportunity.loss_reason_description_c as loss_reason_description_c,
        sfc_opportunity.name as name,
        sfc_opportunity.next_step as next_step,
        sfc_opportunity.or_oe_c as or_oe_c,
        sfc_opportunity.portal_project_code_c as portal_project_code_c,
        cast(sfc_opportunity.probability as number(38,0)) as probability,
        sfc_opportunity.scope_type_c as scope_type_c,
        sfc_opportunity.stage_name as stage_name,
        sfc_opportunity.subtype_c as subtype_c,
        cast(sfc_opportunity.total_opportunity_quantity as number(38,0)) as total_opportunity_quantity,
        sfc_opportunity.type_c as type_c,
    from sfc_opportunity
    left join sfc_opportunity as parent_oppty on sfc_opportunity.pse_parent_opportunity_c = parent_oppty.id
) 
    
select * from final