with 
    compensation as (select * from {{ source('ukg_pro', 'compensation') }} where _fivetran_deleted=false),
    company as (select * from {{ source('ukg_pro', 'company') }} where _fivetran_deleted=false)

select 
    'ukg' as src_sys_key,
    cast(current_timestamp as timestamp_tz) as dts_created_at,
    '{{ this.name }}' as created_by,
    cast(current_timestamp as timestamp_tz) as dts_updated_at,
    '{{ this.name }}' as updated_by,
    cast(current_timestamp as timestamp_tz) as dts_eff_start,
    cast('9999-12-31' as timestamp_tz ) as dts_eff_end,
    true as bln_current,
    _fivetran_id as key,
    md5(_fivetran_id) as hash_key,
    concat(_fivetran_id) as link,
    md5(_fivetran_id) as hash_link,
    compensation.company_id as key_company,
    md5(compensation.company_id) as hash_key_company,
    compensation.employee_id as key_employee,
    md5(compensation.employee_id) as hash_key_employee,
    concat(employee_id,':',company_id) as key_employee_company,
    md5(concat(employee_id,':',company_id)) as hash_key_employee_company,
    company.code as company_code,
    compensation.distribution_center_code as distribution_center_code,
    compensation.empl_status as employee_status_code,
    compensation.job_change_reason_code as job_change_reason_code,
    compensation.job_salary_grade as job_salary_grade,
    compensation.primary_job_id as primary_job_id,
    compensation.primary_shift_code as primary_shift_code,
    compensation.primary_shift_group_code as primary_shift_group_code,
    cast(compensation.annual_salary as number(38,17)) as annual_salary,
    compensation.is_auto_paid as bln_is_auto_paid,
    case when compensation.full_time_or_part_time_code = 'F' then true else false end as bln_is_full_time,
    compensation.is_highly_compensated as bln_is_highly_compensated,
    case when compensation.salary_or_hourly_code = 'S' then true else false end as bln_is_salary,
    ifnull(compensation.currency_code, company.currency_code) as currency_code,
    cast(compensation.date_in_job as date) as dte_in_job,
    cast(compensation.date_last_paid as date) as dte_last_paid,
    cast(compensation.date_last_worked as date) as dte_last_worked,
    cast(compensation.date_of_next_salayr_review as date) as dte_next_salary_review,
    cast(compensation.date_paid_thru as date) as dte_paid_thru,
    compensation._fivetran_synced as dts_last_synced,
    cast(compensation.hourly_pay_rate as number(38,17)) as hourly_pay_rate,
    compensation.job_title as job_title,
    compensation.number_of_payments as number_of_payments,
    cast(compensation.other_rate_1 as number(38,17)) as other_rate_1,
    cast(compensation.other_rate_2 as number(38,17)) as other_rate_2,
    cast(compensation.other_rate_3 as number(38,17)) as other_rate_3,
    cast(compensation.other_rate_4 as number(38,17)) as other_rate_4,
    compensation.pay_group_description as pay_group_description,
    compensation.pay_group as pay_group_id,
    compensation.pay_period as pay_period,
    cast(compensation.pay_period_pay_rate as number(38,17)) as pay_period_pay_rate,
    compensation.performance_review_rating as performance_review_rating,
    compensation.performance_review_type as performance_review_type,
    cast(compensation.scheduled_annual_work_hours as number(38,17)) as scheduled_annual_work_hours,
    cast(compensation.scheduled_full_time_equivalency as number(38,17)) as scheduled_full_time_equivalency,
    cast(compensation.scheduled_period_work_hours as number(38,17)) as scheduled_period_work_hours,
    cast(compensation.total_ann_salary as number(38,17)) as total_ann_salary,
    cast(compensation.weekly_hours as number(38,17)) as weekly_hours,
    cast(compensation.weekly_pay_rate as number(38,17)) as weekly_pay_rate
from compensation
left join company on compensation.company_id = company.id