version: 3

sources:
  - name: portal
    description: Source for Portal database
    database: prod_bi_dw
    schema:  cai_portal
    tables:
      - name: base_teams
      - name: contractor_companies
      - name: countries
      - name: currencies
      - name: departments
      - name: dol_statuses
      - name: employee_types
      - name: entities
      - name: entities_benefit_rates
      - name: ethnic_backgrounds
      - name: genders
      - name: job_salary_grades
      - name: labor_categories
      - name: labor_categories_rates
      - name: locations
      - name: locations_intacct
      - name: locations_ukg
      - name: location_continents
      - name: location_regions
      - name: payroll_companies
      - name: pay_types
      - name: positions
      - name: position_families
      - name: practices
      - name: practice_areas
      - name: reporting_groups
      - name: reporting_groups_locations
      - name: states
      - name: termination_types
      - name: timeframes
      - name: users
      - name: users_forecasts
