with 
    sf_timesheetentry as (select * from {{ ref('int_sf_timesheetentry') }}),
    si_timesheetentry as (select * from {{ source('sage_intacct', 'timesheetentry') }} where _fivetran_deleted = false),
    sf_contact        as (select * from {{ source('salesforce', 'contact') }} where _fivetran_deleted = false),
    sf_project        as (select * from {{ source('salesforce', 'pse_proj_c') }} where _fivetran_deleted = false),
    sf_project_task   as (select * from {{ source('salesforce', 'pse_project_task_c') }} where _fivetran_deleted = false),
    si_filtered       as (
                            select 
                                * 
                            from si_timesheetentry
                            qualify row_number() over (
                                partition by projectid, employeeid, entrydate, taskkey 
                                order by whenmodified desc
                            ) = 1
                        ),

salesforce as (
    select
        md5(sf_timesheetentry.id || sf_timesheetentry.created_date) as pk_timesheet,
        'sfc' as src_sys_key,
        current_timestamp as dts_created_at,
        'timesheet' as created_by,
        current_timestamp as dts_updated_at,
        'timesheet' as updated_by,
        current_timestamp as dts_eff_start,
        '9999-12-31' as dts_eff_end,
        true as bln_current,
        null as billu_acct_key,
        null as customer_id,
        null as department_id,
        null as department_key,
        null as employee_earning_type_key,
        sf_contact.pse_api_resource_correlation_id_c as employee_id,
        sf_timesheetentry.pse_resource_c as employee_system_id,
        md5(sf_timesheetentry.pse_project_c) as fk_project,
        md5(sf_timesheetentry.pse_timecard_c) as fk_timesheet,
        md5(sf_timesheetentry.pse_resource_c) as fk_employee,
        null as fk_task,
        null as item_id,
        null as item_key,
        null as labor_gl_batch_key,
        null as location_id,
        null as location_key,
        null as non_billnu_acct_key,
        null as non_billu_acct_key,
        sf_project.intacct_project_id_c as project_id,
        null as project_dim_key,
        sf_timesheetentry.pse_project_c as project_system_id,
        sf_timesheetentry.created_by_id as src_created_by_id,
        sf_timesheetentry.last_modified_by_id as src_modified_by_id,
        null as stat_gl_batch_key,
        null as stat_journal_key,
        sf_timesheetentry.id as system_id,
        sf_project_task.intacct_id_c as task_id,
        sf_project_task.intacct_record_no_c as task_key,
        sf_timesheetentry.pse_timecard_c as timesheet_system_id,
        si.recordno as timesheet_entry_link_id,
        null as amt_labor_gl_entry,
        null as amt_labor_glentry_trx,
        null as amt_stat_gl_entry,
        null as bill_rate,
        null as bln_billable,
        null as bln_billed,
        null as customer_name,
        sf_contact.department as department_name,
        null as dte_entry,
        null as dte_gl_post,
        sf_timesheetentry.created_date as dte_src_created,
        sf_timesheetentry.pse_end_date_c as dte_src_end,
        sf_timesheetentry.last_modified_date as dte_src_modified,
        sf_timesheetentry.header_start_date as dte_src_start,
        sf_contact.name as employee_name,
        null as item_name,
        null as labor_gl_entry_cost_rate,
        null as labor_gl_entry_line_no,
        null as labor_gl_entry_offset_line_no,
        null as line_no,
        null as location_name,
        sf_timesheetentry.notes as notes,
        sf_project.name as project_name,
        sf_timesheetentry.qty as qty,
        null as qty_approved,
        null as qty_approved_billable,
        null as qty_approved_non_billable,
        null as qty_approved_non_utilized,
        null as qty_approved_utilized,
        null as qty_billable,
        null as qty_non_billable,
        null as qty_non_utilized,
        null as qty_utilized,
        null as record_url,
        null as stat_gl_entry_line_no,
        null as state,
        sf_timesheetentry.name as task_name
    from sf_timesheetentry
    left join sf_contact on sf_contact.id = sf_timesheetentry.pse_resource_c
    left join sf_project on sf_project.id = sf_timesheetentry.pse_project_c
    left join sf_project_task on sf_project_task.id = sf_timesheetentry.pse_project_task_c
    left join si_filtered si 
        on sf_project.intacct_project_id_c = si.projectid
        and sf_contact.pse_api_resource_correlation_id_c = si.employeeid
        and sf_timesheetentry.task_start_date = si.entrydate
        and sf_project_task.intacct_record_no_c = si.taskkey
),

sage_intacct as (
    select
        md5(recordno) as pk_timesheet,
        'sin' as src_sys_key,
        current_timestamp as dts_created_at,
        'timesheet' as created_by,
        current_timestamp as dts_updated_at,
        'timesheet' as updated_by,
        current_timestamp as dts_eff_start,
        '9999-12-31' as dts_eff_end,
        true as bln_current,
        billuacctkey as billu_acct_key,
        customerid as customer_id,
        departmentid as department_id,
        departmentkey as department_key,
        employee_earningtypekey as employee_earning_type_key,
        employeeid as employee_id,
        md5(employeedimkey) as employee_system_id,
        md5(projectid) as fk_project,
        md5(timesheetkey) as fk_timesheet,
        md5(employeeid) as fk_employee,
        null as fk_task,
        itemid as item_id,
        cast(itemkey as string) as item_key,
        cast(laborglbatchkey as string) as labor_gl_batch_key,
        locationid as location_id,
        cast(locationkey as string) as location_key,
        cast(nonbillnuacctkey as string) as non_billnu_acct_key,
        cast(nonbilluacctkey as string) as non_billu_acct_key,
        projectid as project_id,
        cast(projectdimkey as string) as project_dim_key,
        cast(projectkey as string) as project_system_id,
        cast(createdby as string) as src_created_by_id,
        cast(modifiedby as string) as src_modified_by_id,
        cast(statglbatchkey as string) as stat_gl_batch_key,
        cast(statjournalkey as string) as stat_journal_key,
        recordno as system_id,
        taskid as task_id,
        cast(taskkey as string) as task_key,
        cast(timesheetkey as string) as timesheet_system_id,
        recordno as timesheet_entry_link_id,
        laborglentryamount as amt_labor_gl_entry,
        laborglentrytrxamount as amt_labor_glentry_trx,
        statglentryamount as amt_stat_gl_entry,
        null as bill_rate,
        billable as bln_billable,
        billed as bln_billed,
        customername as customer_name,
        departmentname as department_name,
        entrydate as dte_entry,
        ts_glpostdate as dte_gl_post,
        whencreated as dte_src_created,
        ts_enddate as dte_src_end,
        whenmodified as dte_src_modified,
        ts_begindate as dte_src_start,
        employeename as employee_name,
        itemname as item_name,
        laborglentrycostrate as labor_gl_entry_cost_rate,
        laborglentrylineno as labor_gl_entry_line_no,
        laborglentryoffsetlineno as labor_gl_entry_offset_line_no,
        lineno as line_no,
        locationname as location_name,
        notes as notes,
        projectname as project_name,
        qty as qty,
        approved_qty as qty_approved,
        approved_billable_qty as qty_approved_billable,
        approved_non_billable_qty as qty_approved_non_billable,
        approved_non_utilized_qty as qty_approved_non_utilized,
        approved_utilized_qty as qty_approved_utilized,
        billable_qty as qty_billable,
        non_billable_qty as qty_non_billable,
        non_utilized_qty as qty_non_utilized,
        utilized_qty as qty_utilized,
        record_url as record_url,
        statglentrylineno as stat_gl_entry_line_no,
        state as state,
        taskname as task_name
    from si_timesheetentry
)

select * from sage_intacct
union all
select * from salesforce
