{{
    config(
        materialized="table",
        schema="consolidation"
    )
}}

with 
    si_apbillitem as (select * from {{ source("sage_intacct", "ap_bill_item") }}),

sage_intacct as (
    select
        'int' as src_sys_key,
        current_timestamp as dts_created_at,
        '{{ this.name }}' as created_by,
        current_timestamp as dts_updated_at,
        '{{ this.name }}' as updated_by,
        current_timestamp as dts_eff_start,
        '9999-12-31' as dts_eff_end,
        true as bln_current,
        recordno as key,
        md5(recordno) as hash_key,
        recordkey as key_ap_bill,
        md5(recordkey) as hash_key_ap_bill,
        -- megaentitykey as key_entity,
        -- md5(megaentitykey) as hash_key_entity,
        employeedimkey as key_employee,
        md5(employeedimkey) as hash_key_employee,
        accountkey as account_key,
        customerdimkey as customer_dim_key,
        customerid as customer_id,
        departmentid as department_id,
        detailkey as detail_key,
        employeeid as employee_id,
        exch_rate_type_id as exch_rate_type_id,
        itemdimkey as item_dim_key,
        itemid as item_id,
        locationid as location_id,
        offsetaccountkey as offset_account_key,
        projectdimkey as project_dim_key,
        projectid as project_id,
        recordid as record_id,
        createdby as src_created_by_id,
        modifiedby as src_modified_by_id,
        vendordimkey as vendor_dim_key,
        vendorid as vendor_id,
        exch_rate_date as dte_exch_rate,
        non_reclaim_vat_base_amount as amt_non_reclaim_vat_base,
        accountno as account_no,
        accounttitle as account_title,
        allocationkey as allocationkey,
        amount as amount,
        base_vat_amount as amt_base_vat,
        net_of_vat_amount as amt_net_of_vat,
        net_of_vat_base_amount as amt_net_of_vat_base,
        non_reclaim_vat_amount as amt_non_reclaim_vat,
        reclaim_vat_amount as amt_reclaim_vat,
        reclaim_vat_base_amount as amt_reclaim_vat_base,
        amountretained as amt_retained,
        reverse_txn_vat_amount as amt_reverse_txn_vat,
        reverse_txn_vat_base_amount as amt_reverse_txn_vat_base,
        totalpaid as amt_total_paid,
        trx_amount as amt_trx,
        trx_totalpaid as amt_trx_total_paid,
        basecurr as basecurr,
        baselocation as baselocation,
        manual_vat_amount as bln_amt_manual_vat,
        billable as bln_billable,
        billed as bln_billed,
        includetaxinassetcost as bln_include_tax_in_asset_cost,
        india_cgst as bln_india_cgst,
        india_igst as bln_india_igst,
        india_rcm as bln_india_rcm,
        india_sgst as bln_india_sgst,
        lineitem as bln_line_item,
        partialexempt as bln_partial_exempt,
        paymenttaxcapture as bln_payment_tax_capture,
        tax_use_ic_code as bln_tax_use_ic_code,
        cf_apbillitem_text_pesname as cf_apbillitem_text_pesname,
        currency as currency_code,
        customername as customer_name,
        departmentname as departmentname,
        cf_apbillitem_date_expamtstartdate as dte_cf_apbillitem_expamtstart,
        entry_date as dte_entry,
        entry_date as dte_src_start,
        null as dte_src_end,
        whencreated as dts_src_created,
        whenmodified as dts_src_modified,
        employeename as employee_name,
        entrydescription as entry_description,
        europe_vat_rate as europe_vat_rate,
        exchange_rate as exchange_rate,
        form_1099 as form_1099,
        form_1099_box as form_1099_box,
        form_1099_type as form_1099_type,
        gldimvat_code as gl_dim_vat_code,
        gldimline_tax_detail as gl_dimline_tax_detail,
        itemname as item_name,
        line_no as line_no,
        locationname as location_name,
        offsetglaccountno as offset_gl_account_no,
        offsetglaccounttitle as offset_gl_account_title,
        parententry as parent_entry,
        prentryoffsetaccountno as prentry_offset_account_no,
        previous_offset_account as previous_offset_account,
        projectname as project_name,
        reclaim as reclaim,
        recordtype as record_type,
        record_url as record_url,
        retainagepercentage as retain_age_percentage,
        rpec as rpec,
        rpes as rpes,
        state as state,
        vat_amount as vat_amount,
        vat_rate as vat_rate,
        vendorname as vendor_name
    from si_apbillitem 
)

select * from sage_intacct