{{
    config(
        materialized="table",
        schema="consolidation",
        alias="ap_bill_item"
    )
}}

with 
    si_apbillitem as (select * from {{ source("sage_intacct", "ap_bill_item") }}),

sage_intacct as (
    select
        'int' as src_sys_key,
        cast(current_timestamp as timestamp_tz) as dts_created_at,
        '{{ this.name }}' as created_by,
        cast(current_timestamp as timestamp_tz) as dts_updated_at,
        '{{ this.name }}' as updated_by,
        cast(current_timestamp as timestamp_tz) as dts_eff_start,
        cast('9999-12-31' as timestamp_tz) as dts_eff_end,
        true as bln_current,
        recordno as key,
        md5(recordno) as hash_key,
        recordkey as key_ap_bill,
        md5(recordkey) as hash_key_ap_bill,
        cast(employeedimkey as string) as key_employee,
        md5(employeedimkey) as hash_key_employee,
        accountkey as account_key,
        customerdimkey as customer_key,
        customerid as customer_id,
        departmentid as department_id,
        detailkey as detail_key,
        employeeid as employee_id,
        exch_rate_type_id as exch_rate_type_id,
        itemdimkey as item_key,
        itemid as item_id,
        locationid as location_id,
        offsetaccountkey as offset_account_key,
        projectdimkey as key_project,
        md5(projectdimkey) as hash_key_project,
        projectid as project_id,
        recordid as record_id,
        cast(createdby as string) as src_created_by_id,
        cast(modifiedby as string) as src_modified_by_id,
        vendordimkey as vendor_key,
        vendorid as vendor_id,
        exch_rate_date as dte_exch_rate,
        cast(non_reclaim_vat_base_amount as number(38, 2)) as amt_non_reclaim_vat_base,
        accountno as account_no,
        accounttitle as account_title,
        allocationkey as allocationkey,
        cast(amount as number(38, 2)) as amount,
        cast(base_vat_amount as number(38, 2)) as amt_base_vat,
        cast(net_of_vat_amount as number(38, 2)) as amt_net_of_vat,
        cast(net_of_vat_base_amount as number(38, 2)) as amt_net_of_vat_base,
        cast(non_reclaim_vat_amount as number(38, 2)) as amt_non_reclaim_vat,
        cast(reclaim_vat_amount as number(38, 2)) as amt_reclaim_vat,
        cast(reclaim_vat_base_amount as number(38, 2)) as amt_reclaim_vat_base,
        cast(amountretained as number(38, 2)) as amt_retained,
        cast(reverse_txn_vat_amount as number(38, 2)) as amt_reverse_txn_vat,
        cast(reverse_txn_vat_base_amount as number(38, 2)) as amt_reverse_txn_vat_base,
        cast(totalpaid as number(38, 2)) as amt_total_paid,
        cast(trx_amount as number(38, 2)) as amt_trx,
        cast(trx_totalpaid as number(38, 2)) as amt_trx_total_paid,
        basecurr as basecurr,
        baselocation as baselocation,
        manual_vat_amount as bln_amt_manual_vat,
        billable as bln_billable,
        billed as bln_billed,
        includetaxinassetcost as bln_include_tax_in_asset_cost,
        india_cgst as bln_india_cgst,
        india_igst as bln_india_igst,
        india_rcm as bln_india_rcm,
        india_sgst as bln_india_sgst,
        lineitem as bln_line_item,
        partialexempt as bln_partial_exempt,
        paymenttaxcapture as bln_payment_tax_capture,
        tax_use_ic_code as bln_tax_use_ic_code,
        cf_apbillitem_text_pesname as cf_apbillitem_text_pesname,
        currency as currency_code,
        customername as customer_name,
        departmentname as department_name,
        cf_apbillitem_date_expamtstartdate as dte_cf_apbillitem_expamtstart,
        entry_date as dte_entry,
        entry_date as dte_src_start,
        cast('9999-12-31' as date)  as dte_src_end,
        whencreated as dts_src_created,
        whenmodified as dts_src_modified,
        employeename as employee_name,
        entrydescription as entry_description,
        europe_vat_rate as europe_vat_rate,
        cast(exchange_rate as number(38, 2)) as exchange_rate,
        form_1099 as form_1099,
        form_1099_box as form_1099_box,
        form_1099_type as form_1099_type,
        gldimvat_code as gl_dim_vat_code,
        gldimline_tax_detail as gl_dimline_tax_detail,
        itemname as item_name,
        line_no as line_no,
        locationname as location_name,
        offsetglaccountno as offset_gl_account_no,
        offsetglaccounttitle as offset_gl_account_title,
        parententry as parent_entry,
        prentryoffsetaccountno as prentry_offset_account_no,
        previous_offset_account as previous_offset_account,
        projectname as project_name,
        reclaim as reclaim,
        recordtype as record_type,
        record_url as record_url,
        retainagepercentage as retain_age_percentage,
        rpec as rpec,
        rpes as rpes,
        state as state,
        cast(vat_amount as number(38, 2)) as vat_amount,
        cast(vat_rate as number(38, 2)) as vat_rate,
        vendorname as vendor_name
    from si_apbillitem 
)

select * from sage_intacct