{{
    config(
        materialized="table",
        schema="consolidation",
    )
}}

with
    si_apbill as (select * from {{ source("sage_intacct", "ap_bill") }} where _fivetran_deleted = false),

sage_intacct as (
    select
        'int' as src_sys_key,
        current_timestamp as dts_created_at,
        '{{ this.name }}' as created_by,
        current_timestamp as dts_updated_at,
        '{{ this.name }}' as updated_by,
        current_timestamp as dts_eff_start,
        '9999-12-31' as dts_eff_end,
        true as bln_current,
        recordno as key,
        md5(recordno) as hash_key,
        megaentitykey as key_entity,
        md5(megaentitykey) as hash_key_entity,
        billtopaytokey as billto_payto_key,
        createduserid as created_user_id,
        exch_rate_type_id as exch_rate_type_id,
        megaentityid as mega_entity_id,
        modulekey as module_key,
        payto_taxid as payto_tax_id,
        prbatchkey as pr_batch_key,
        recordid as record_id,
        schopkey as schop_key,
        shiptoreturntokey as ship_to_return_to_key,
        createdby as src_created_by_id,
        modifiedby as src_modified_by_id,
        supdocid as supdoc_id,
        taxsolutionid as tax_solution_id,
        termkey as term_key,
        userid as user_id,
        vendorid as vendor_id,
        vendorkey as vendor_key,
        totaldue as amt_total_due,
        totalentered as amt_total_entered,
        totalpaid as amt_total_paid,
        trx_totalentered as amt_trx_total_entered,
        trx_totalpaid as amt_trx_total_paid,
        basecurr as base_currency_code,
        billbacktemplate as bill_back_template,
        billtopaytocontactname as billto_payto_contact_name,
        do_not_process_vat as bln_do_not_process_vat,
        onhold as bln_on_hold,
        retainagereleased as bln_retain_age_released,
        systemgenerated as bln_system_generated,
        contacttaxgroup as contact_tax_group,
        currency as currency_code,
        description as description,
        description_2 as description_2,
        docnumber as doc_number,
        exch_rate_date as dte_exch_rate,
        recpaymentdate as dte_rec_payment,
        null as dte_src_end,
        whenposted as dte_src_start,
        whendiscount as dte_when_discount,
        whendue as dte_when_due,
        whenpaid as dte_when_paid,
        whenposted as dte_when_posted,
        auwhencreated as dts_au_src_created,
        whencreated as dts_src_created,
        whenmodified as dts_src_modified,
        due_in_days as due_in_days,
        exchange_rate as exchange_rate,
        financialentity as financial_entity,
        form_1099_box as form_1099_box,
        form_1099_type as form_1099_type,
        megaentityname as megaentity_name,
        paymentpriority as payment_priority,
        payto_taxgroup_name as payto_taxgroup_name,
        payto_taxgroup_recordno as payto_taxgroup_recordno,
        prbatch as pr_batch,
        rawstate as raw_state,
        record_url as record_url,
        recordtype as recordtype,
        senderemail as sender_email,
        shiptoreturntocontactname as shipto_returnto_contact_name,
        state as state,
        tax_entity_number as tax_entity_number,
        tax_reverse_status as tax_reverse_status,
        termname as term_name,
        termvalue as term_value,
        trx_entitydue as trx_entity_due,
        trx_totaldue as trx_total_due,
        vendorname as vendor_name
    from si_apbill
)

select
    src_sys_key,
    cast(dts_created_at as timestamp_tz) as dts_created_at,
    created_by,
    cast(dts_updated_at as timestamp_tz) as dts_updated_at,
    updated_by,
    cast(dts_eff_start as timestamp_tz) as dts_eff_start,
    cast(dts_eff_end as timestamp_tz) as dts_eff_end,
    bln_current,
    key,
    hash_key,
    cast(key_entity as string) as key_entity,
    hash_key_entity,
    billto_payto_key,
    created_user_id,
    exch_rate_type_id,
    mega_entity_id,
    module_key,
    payto_tax_id,
    pr_batch_key,
    record_id,
    schop_key,
    ship_to_return_to_key,
    cast(src_created_by_id as string) as src_created_by_id,
    cast(src_modified_by_id as string) as src_modified_by_id,
    supdoc_id,
    tax_solution_id,
    term_key,
    user_id,
    vendor_id,
    vendor_key,
    cast(amt_total_due as number(38, 2)) as amt_total_due,
    cast(amt_total_entered as number(38, 2)) as amt_total_entered,
    cast(amt_total_paid as number(38, 2)) as amt_total_paid,
    cast(amt_trx_total_entered as number(38, 2)) as amt_trx_total_entered,
    cast(amt_trx_total_paid as number(38, 2)) as amt_trx_total_paid,
    base_currency_code,
    bill_back_template,
    billto_payto_contact_name,
    bln_do_not_process_vat,
    bln_on_hold,
    bln_retain_age_released,
    bln_system_generated,
    contact_tax_group,
    currency_code,
    description,
    description_2,
    doc_number,
    dte_exch_rate,
    dte_rec_payment,
    cast(dte_src_end as date) as dte_src_end,
    cast(dte_src_start as date) as dte_src_start,
    dte_when_discount,
    dte_when_due,
    dte_when_paid,
    dte_when_posted,
    dts_au_src_created,
    cast(dts_src_created as timestamp_tz) as dts_src_created,
    dts_src_modified,
    due_in_days,
    cast(exchange_rate as number(38, 6)) as exchange_rate,
    financial_entity,
    form_1099_box,
    form_1099_type,
    megaentity_name,
    payment_priority,
    payto_taxgroup_name,
    payto_taxgroup_recordno,
    pr_batch,
    raw_state,
    record_url,
    recordtype,
    sender_email,
    shipto_returnto_contact_name,
    state,
    tax_entity_number,
    tax_reverse_status,
    term_name,
    term_value,
    cast(trx_entity_due as number(38, 2)) as trx_entity_due,
    cast(trx_total_due as number(38, 2)) as trx_total_due,
    vendor_name
from sage_intacct
