{{ 
    config(
        materialized="table",
        schema="consolidation"
    )
}}

with
    sf_contact          as (select * from {{ source('salesforce', 'contact') }} where _fivetran_deleted = false and record_type_id = '0124W000001bI6LQAU'),
    sf_user             as (select * from {{ source('salesforce', 'user') }} where _fivetran_deleted = false),
    si_employee         as (select * from {{ source('sage_intacct', 'employee') }} where _fivetran_deleted = false),
    si_location         as (select * from {{ source('sage_intacct', 'location') }} where _fivetran_deleted = false),
    si_contact          as (select * from {{ source('sage_intacct', 'contact') }} where _fivetran_deleted = false),
    portal_users        as (select * from {{ source('portal', 'users') }} where _fivetran_deleted = false),
    ukg_employee        as (select * from {{ source('ukg_pro', 'employee') }} where _fivetran_deleted = false),
    ukg_job             as (select * from {{ source('ukg_pro', 'job') }} where _fivetran_deleted = false),
    ukg_employee_change as (select * from {{ source('ukg_pro', 'employee_change') }} where _fivetran_deleted = false),
    ukg_employment      as (
            select 
                *
            from {{ source('ukg_pro', 'employment') }} 
            where _fivetran_deleted = false
            qualify row_number() over (
            partition by employee_id
            order by date_in_job desc
        ) = 1
    ),
    ukg_compensation    as (
    select 
        * 
    from {{ source('ukg_pro', 'compensation') }} qualify row_number() over ( partition by employee_id
    order by date_in_job desc ) = 1
    ),
    

ukg as (
    select 
        'ukg' as src_sys_key,
        current_timestamp as dts_created_at,
        '{{ this.name }}' as created_by,
        current_timestamp as dts_updated_at,
        '{{ this.name }}' as updated_by,
        current_timestamp as dts_eff_start,
        '9999-12-31' as dts_eff_end,
        true as bln_current,
        ukg_employee.id key,
        md5(ukg_employee.id) hash_key,
        ukg_employee.id as link,
        md5(ukg_employee.id) as hash_link,
        ukg_employee.company_id as key_entity,
        md5(ukg_employment.company_id) as hash_key_entity,
        ukg_employment.organization_level_3_id as key_base_team,
        md5(ukg_employment.organization_level_3_id) as hash_key_base_team,
        concat(ukg_employment.employee_id, ukg_employment.company_id) as key_employment,
        md5(concat(ukg_employment.employee_id, ukg_employment.company_id)) as hash_key_employment,
        null as account_id,
        null as azure_id,
        null as contact_id,
        null as continent_id,
        null as contractor_company_id,
        ukg_employee.address_country as country_id,
        ukg_employment.organization_level_2_id as department_id,
        ukg_employment.full_time_or_part_time_code as dol_status_id,
        ukg_employment.employee_type_code as employee_type_id,
        ukg_employee.ethnic_id_code as ethnic_background_id,
        ukg_employee.gender as gender_id,
        null as intacct_contact_key,
        null as intacct_department_key,
        null as intacct_location_key,
        null as intacct_employee_id,
        null as intacct_employee_key,
        null as intacct_override_entity_id,
        null as labor_category_id,
        null as location_id,
        ukg_employment.organization_level_4_id as location_id_intacct,
        ukg_employment.primary_work_location_id as location_id_ukg,
        ukg_employee.national_id as national_id,
        ukg_employee.national_id_country as national_id_country,
        ukg_employment.salary_or_hourly as pay_type_id,
        ukg_employment.pay_group as payroll_company_id,
        ukg_job.job_family_code as position_family_id,
        ukg_employment.primary_job_id as position_id,
        ukg_employment.organization_level_1_id as practice_id,
        null as profile_id,
        null as region_id,
        null as salesforce_sandbox_contact_id,
        null as salesforce_sandbox_user_id,
        null as salesforce_user_id,
        null as src_created_by_id,
        null as src_modified_by_id,
        ukg_employee.address_state as state_id,
        ukg_employment.supervisor_id as supervisor_id,
        ukg_employee.id as system_id,
        ukg_employment.term_reason as termination_type_id,
        null as tracker_record_id,
        null as ukg_override_payroll_company_id,
        ukg_employee.person_id as ukg_person_id,
        null as work_calendar_id,
        ukg_employee.address_city as address_city,
        ukg_employee.address_country as address_country,
        ukg_employee.address_zip_code as address_postal_code,
        ukg_employee.address_state as address_state,
        ukg_employee.address_line_1 as address_street,
        ukg_compensation.annual_salary as annual_salary,
        null as bln_exclude_from_resource_planner,
        case when ukg_employment.employee_status_code in ('A', 'L', 'O') then true else false end as bln_is_active,
        null as bln_is_hourly,
        null as bln_mst,
        null as bln_pm_qualified,
        null as bln_is_resource,
        null as closed_won_goal,
        ukg_compensation.currency_code as currency_code,
        coalesce(ukg_employee.preferred_name, ukg_employee.first_name) || ' ' || ukg_employee.last_name as display_name,
        concat(ukg_employee.last_name, ', ', ukg_employee.preferred_name, ukg_employee.first_name) as display_name_lf,
        cast(ukg_employee.date_of_birth as timestamp_tz) as dte_birth,
        null as dte_of_industry_experience,
        cast(ukg_employment.date_of_termination as timestamp_tz) as dte_src_end,
        cast(ukg_employment.original_hire_date as timestamp_tz) as dte_src_start,
        cast(ukg_compensation.date_in_job as timestamp_tz) as dts_in_job,
        cast(ukg_employment.last_hire_date as timestamp_tz) as dts_last_hire,
        cast(ukg_compensation.date_last_paid as timestamp_tz) as dts_last_paid,
        cast(ukg_employee.date_time_created as timestamp_tz) as dts_src_created,
        cast(ukg_employee.date_time_changed as timestamp_tz) as dts_src_modified,
        ukg_employee.email_address_alternate as email_address_personal,
        ukg_employee.email_address as email_address_work,
        ukg_compensation.empl_status as empl_status,
        ukg_employee.first_name as first_name,
        concat(ukg_employee.preferred_name, ' ', ukg_employee.first_name) as first_name_display,
        ukg_employee.former_name as former_name,
        null as historical_utilization_target_hours,
        ukg_employee.home_phone as home_phone,
        ukg_employee.home_phone_country as home_phone_country,
        ukg_compensation.hourly_pay_rate as hourly_pay_rate,
        null as intacct_contact_name,
        ukg_compensation.job_salary_grade as job_salary_grade,
        ukg_employment.job_title as job_title,
        ukg_employee.last_name as last_name,
        ukg_employee.middle_name as middle_name,
        ukg_compensation.other_rate_1 as other_rate_1,
        ukg_compensation.other_rate_2 as other_rate_2,
        ukg_compensation.other_rate_3 as other_rate_3,
        ukg_compensation.other_rate_4 as other_rate_4,
        ukg_compensation.pay_group as pay_group,
        ukg_compensation.pay_period_pay_rate as pay_period_pay_rate,
        ukg_employment.employee_status_code as status,
        ukg_employment.term_type as term_type,
        ukg_employment.termination_reason_description as termination_reason_description,
        ukg_compensation.total_ann_salary as total_ann_salary,
        ukg_employee_change.employee_number as ukg_employee_number,
        ukg_employment.job_title as ukg_override_job_title,
        ukg_employment.employee_status_code as ukg_status,
        null as utilization_target,
        null as utilization_target_hours,
        ukg_compensation.weekly_pay_rate as weekly_pay_rate,
        ukg_employment.work_phone_country as work_phone_country,
        null as work_phone_number
    from ukg_employee
    left join ukg_employment on ukg_employee.id = ukg_employment.employee_id
    left join ukg_job on ukg_employment.primary_job_id = ukg_job.id
    left join ukg_compensation on ukg_compensation.employee_id = ukg_employee.id and ukg_compensation.company_id = ukg_employee.company_id
    left join ukg_employee_change on ukg_employee_change.employee_id = ukg_employee.id 
        and ukg_employee_change.company_id = ukg_employee.company_id
),
portal as (
    select
        'por' as src_sys_key,
        current_timestamp as dts_created_at,
        '{{ this.name }}' as created_by,
        current_timestamp as dts_updated_at,
        '{{ this.name }}' as updated_by,
        current_timestamp as dts_eff_start,
        '9999-12-31' as dts_eff_end,
        true as bln_current,
        id as key,
        md5(id) as hash_key,
        ukg_id as link,
        md5(ukg_id) as hash_link,
        entity_id as key_entity,
        md5(entity_id) as hash_key_entity,
        baseteam_id as key_base_team,
        md5(baseteam_id) as hash_key_base_team,
        concat(ukg_id, entity_id) as key_employment,
        md5(concat(ukg_id, entity_id)) as hash_key_employment,
        null as account_id,
        azure_id as azure_id,
        salesforce_contact_id as contact_id,
        continent_id as continent_id,
        contractor_company_id as contractor_company_id,
        country_id as country_id,
        department_id as department_id,
        dol_status_id as dol_status_id,
        employee_type_id as employee_type_id,
        ethnic_background_id as ethnic_background_id,
        gender_id as gender_id,
        intacct_contact_record_no as intacct_contact_key,
        intacct_department_record_no as intacct_department_key,
        intacct_location_record_no as intacct_location_key,
        intacct_employee_id as intacct_employee_id,
        intacct_employee_record_no as intacct_employee_key,
        intacct_override_entity_id as intacct_override_entity_id,
        labor_category_id as labor_category_id,
        location_id as location_id,
        location_id_intacct as location_id_intacct,
        location_id_ukg as location_id_ukg,
        null as national_id,
        null as national_id_country,
        pay_type_id as pay_type_id,
        payroll_company_id as payroll,
        position_family_id as position_family_id,
        position_id as position_id,
        practice_id as practice_id,
        null as profile_id,
        region_id as region_id,
        salesforce_sandbox_contact_id as salesforce_sandbox_contact_id,
        salesforce_sandbox_user_id as salesforce_sandbox_user_id,
        salesforce_user_id as salesforce_user_id,
        null as src_created_by_id,
        null as src_modified_by_id,
        state_id as state_id,
        supervisor_id as supervisor_id,
        id as system_id,
        termination_type_id as termination_type_id,
        tracker_record_id as tracker_record_id,
        ukg_override_payroll_company_id as ukg_override_payroll_company_id,
        ukg_person_id as ukg_person_id,
        null as work_calendar_id,
        address_city as address_city,
        address_country as address_country,
        address_postal_code as address_postal_code,
        address_state as address_state,
        address_street as address_street,
        null as annual_salary,
        null as bln_exclude_from_resource_planner,
        null as bln_is_active,
        null as bln_is_hourly,
        is_mst as bln_mst,
        is_pm_qualified as bln_pm_qualified,
        null as bln_is_resource,
        null as closed_won_goal,
        currency_id as currency_code,
        display_name as display_name,
        display_name_lf as display_name_lf,
        null as dte_birth,
        null as dte_of_industry_experience,
        cast(end_date as timestamp_tz) as dte_src_end,
        cast(start_date as timestamp_tz) as dte_src_start,
        null as dts_in_job,
        cast(last_hire_date as timestamp_tz) as dts_last_hire,
        null as dts_last_paid,
        null as dts_src_created,
        null as dts_src_modified,
        email_address_personal as email_address_personal,
        email_address_work as email_address_work,
        null as empl_status,
        first_name as first_name,
        first_name_display as first_name_display,
        null as former_name,
        null as historical_utilization_target_hours,
        phone_number_personal as home_phone,
        null as home_phone_country,
        null as hourly_pay_rate,
        intacct_contact_name as intacct_contact_name,
        null as job_salary_grade,
        null as job_title,
        last_name as last_name,
        middle_name as middle_name,
        null as other_rate_1,
        null as other_rate_2,
        null as other_rate_3,
        null as other_rate_4,
        null as pay_group,
        null as pay_period_pay_rate,
        status as status,
        null as term_type,
        null as term_reason_description,
        null as total_ann_salary,
        ukg_employee_number as ukg_employee_number,
        ukg_override_job_title as ukg_override_job_title,
        ukg_status as ukg_status,
        null as utilization_target,
        null as utilization_target_hours,
        null as weekly_pay_rate,
        null as work_phone_country,
        phone_number_work as work_phone_number
    from portal_users
),

sage_intacct as (
    select 
        'int' as src_sys_key,
        current_timestamp as dts_created_at,
        '{{ this.name }}' as created_by,
        current_timestamp as dts_updated_at,
        '{{ this.name }}' as updated_by,
        current_timestamp as dts_eff_start,
        '9999-12-31' as dts_eff_end,
        true as bln_current,
        cast(si_employee.recordno as string) as key,
        md5(si_employee.recordno) as hash_key,
        cast(si_employee.payroll_ee_id as string) as link,
        md5(si_employee.payroll_ee_id) as hash_link,
        concat(si_location.parentkey, si_location.locationid) as key_entity,
        md5(concat(si_location.parentkey, si_location.locationid)) as hash_key_entity,
        si_employee.home_region as key_base_team,
        md5(si_employee.home_region) as hash_key_base_team,
        concat(si_employee.payroll_ee_id, concat(si_location.parentkey, si_location.locationid)) as key_employment,
        md5(concat(si_employee.payroll_ee_id, concat(si_location.parentkey, si_location.locationid))) as hash_key_employment,
        null as account_id,
        null as azure_id,
        null as contact_id,
        null as continent_id,
        null as contractor_company_id,
        si_contact.mailaddress_country as country_id,
        cast(si_employee.departmentid as string) as department_id,
        null as dol_status_id,
        si_employee.employeetype as employee_type_id,
        null as ethnic_background_id,
        si_employee.gender as gender_id,
        cast(si_employee.contactkey as string) as intacct_contact_key,
        cast(si_employee.departmentkey as string) as intacct_department_key, 
        cast(si_employee.locationkey as string) as intacct_location_key,
        cast(si_employee.employeeid as string) as intacct_employee_id,
        cast(si_employee.recordno as string) as intacct_employee_key,
        null as intacct_override_entity_id,
        null as labor_category_id,
        null as location_id,
        cast(si_employee.locationkey as string) as location_id_intacct,
        null as location_id_ukg,
        null as national_id,
        null as national_id_country,
        null as pay_type_id,
        null as payroll_company_id,
        null as position_family_id,
        null as position_id,
        null as practice_id,
        null as profile_id,
        null as region_id,
        null as salesforce_sandbox_contact_id,
        null as salesforce_sandbox_user_id,
        null as salesforce_user_id,
        cast(si_employee.createdby as string) as src_created_by_id,
        cast(si_employee.modifiedby as string) as src_modified_by_id,
        si_contact.mailaddress_state as state_id,
        cast(si_employee.supervisorid as string) as supervisor_id,
        cast(si_employee.employeeid as string) as system_id,
        null as termination_type_id,
        null as tracker_record_id,
        null as ukg_override_payroll_company_id,
        cast(si_employee.payroll_person_id as string) as ukg_person_id,
        null as work_calendar_id,
        si_contact.mailaddress_city as address_city,
        null as address_country,
        si_contact.mailaddress_zip as address_postal_code,
        null as address_state,
        si_contact.mailaddress_address_1 as address_street,
        null as annual_salary,
        null as bln_exclude_from_resource_planner,
        null as bln_is_active,
        si_employee.hourly_payroll as bln_is_hourly,
        null as bln_mst,
        null as bln_pm_qualified,
        null as bln_is_resource,
        null as closed_won_goal,
        si_employee.currency as currency_code,
        si_contact.printas as display_name,
        si_contact.contactname as display_name_lf,
        null as dte_birth,
        null as dte_of_industry_experience,
        cast(si_employee.enddate as timestamp_tz) as dte_src_end,
        cast(si_employee.startdate as timestamp_tz) as dte_src_start,
        null as dts_in_job,
        null as dts_last_hire,
        null as dts_last_paid,
        cast(si_employee.whencreated as timestamp_tz) as dts_src_created,
        cast(si_employee.whenmodified as timestamp_tz) as dts_src_modified,
        si_contact.email_2 as email_address_personal,
        si_contact.email_1 as email_address_work,
        null as empl_status,
        si_contact.firstname as first_name,
        si_contact.firstname as first_name_display,
        null as former_name,
        null as historical_utilization_target_hours,
        null as home_phone,
        null as home_phone_country,
        null as hourly_pay_rate,
        si_employee.personalinfo_contactname as intacct_contact_name,
        null as job_salary_grade,
        null as job_title,
        si_contact.lastname as last_name,
        null as middle_name,
        null as other_rate_1,
        null as other_rate_2,
        null as other_rate_3,
        null as other_rate_4,
        null as pay_group,
        null as pay_period_pay_rate,
        si_contact.status as status,
        null as term_type,
        null as term_reason_description,
        null as total_ann_salary,
        cast(si_employee.payroll_ee_no as string) as ukg_employee_number,
        null as ukg_override_job_title,
        null as ukg_status,
        null as utilization_target,
        null as utilization_target_hours,
        null as weekly_pay_rate,
        null as work_phone_country,
        si_contact.phone_1 as work_phone_number
    from si_employee
    left join si_location on si_employee.locationkey = si_location.recordno
    left join si_contact on si_contact.recordno = si_employee.contactkey
),
salesforce as (
    select
        'sfc' as src_sys_key,
        current_timestamp as dts_created_at,
        '{{ this.name }}' as created_by,
        current_timestamp as dts_updated_at,
        '{{ this.name }}' as updated_by,
        current_timestamp as dts_eff_start,
        '9999-12-31' as dts_eff_end,
        true as bln_current,
        sf_contact.id as key,
        md5(sf_contact.id) as hash_key,
        sf_user.ukg_employee_id_c as link,
        md5(sf_user.ukg_employee_id_c) as hash_link,
        sf_contact.pse_group_c as key_entity,
        md5(sf_contact.pse_group_c) as hash_key_entity,
        sf_contact.base_team_c as key_base_team,
        md5(sf_contact.base_team_c) as hash_key_base_team,
        concat(sf_user.ukg_employee_id_c, sf_contact.pse_group_c) as key_employment,
        md5(concat(sf_user.ukg_employee_id_c, sf_contact.pse_group_c)) as hash_key_employment,
        sf_contact.account_id as account_id,
        null as azure_id,
        sf_contact.id as contact_id,
        null as continent_id,
        null as contractor_company_id,
        sf_contact.mailing_country_code as country_id,
        sf_contact.department as department_id,
        null as dol_status_id,
        sf_contact.employee_type_c as employee_type_id,
        null as ethnic_background_id,
        null as gender_id,
        null as intacct_contact_key,
        null as intacct_department_key,
        null as intacct_location_key,
        sf_contact.pse_api_resource_correlation_id_c as intacct_employee_id,
        null as intacct_employee_key,
        null as intacct_override_entity_id,
        sf_contact.billing_category_c as labor_category_id,
        sf_contact.pse_region_c as location_id,
        null as location_id_intacct,
        null as location_id_ukg,
        null as national_id,
        null as national_id_country,
        sf_contact.employee_pay_type_c as pay_type_id,
        sf_contact.pse_group_c as payroll_company_id,
        null as position_family_id,
        null as position_id,
        sf_contact.pse_practice_c as practice_id,
        sf_user.profile_id as profile_id,
        null as region_id,
        null as salesforce_sandbox_contact_id,
        null as salesforce_sandbox_user_id,
        sf_contact.pse_salesforce_user_c as salesforce_user_id,
        sf_contact.created_by_id as src_created_by_id,
        sf_contact.last_modified_by_id as src_modified_by_id,
        sf_contact.mailing_state as state_id,
        sf_user.manager_id as supervisor_id,
        sf_contact.id as system_id,
        null as termination_type_id,
        null as tracker_record_id,
        null as ukg_override_payroll_company_id,
        sf_user.ukg_person_id_c as ukg_person_id,
        sf_contact.pse_work_calendar_c as work_calendar_id,
        null as address_city,
        null as address_country,
        null as address_postal_code,
        null as address_state,
        null as address_street,
        null as annual_salary,
        sf_contact.pse_exclude_from_resource_planner_c as bln_exclude_from_resource_planner,
        sf_contact.pse_is_resource_active_c as bln_is_active,
        null as bln_is_hourly,
        null as bln_mst,
        sf_contact.qualified_project_manager_c as bln_pm_qualified,
        sf_contact.pse_is_resource_c as bln_is_resource,
        sf_user.closed_won_goal_c as closed_won_goal,
        sf_contact.currency_iso_code as currency_code,
        sf_user.community_nickname as display_name,
        null as display_name_lf,
        null as dte_birth,
        sf_contact.date_of_industry_experience_c as dte_of_industry_experience,
        sf_contact.pse_last_date_c as dte_src_end,
        sf_contact.pse_start_date_c as dte_src_start,
        null as dts_in_job,
        null as dts_last_hire,
        null as dts_last_paid,
        sf_contact.created_date as dts_src_created,
        sf_contact.last_modified_date as dts_src_modified,
        null as email_address_personal,
        sf_contact.email as email_address_work,
        null as empl_status,
        sf_contact.first_name as first_name,
        sf_contact.first_name as first_name_display,
        null as former_name,
        sf_contact.pse_historical_utilization_target_hours_c as historical_utilization_target_hours,
        null as home_phone,
        null as home_phone_country,
        null as hourly_pay_rate,
        null as intacct_contact_name,
        null as job_salary_grade,
        sf_contact.title as job_title,
        sf_contact.last_name as last_name,
        null as middle_name,
        null as other_rate_1,
        null as other_rate_2,
        null as other_rate_3,
        null as other_rate_4,
        null as pay_group,
        null as pay_period_pay_rate,
        null as status,
        null as term_type,
        null as term_reason_description,
        null as total_ann_salary,
        sf_user.ukg_employee_number_c as ukg_employee_number,
        sf_contact.title as ukg_override_job_title,
        null as ukg_status,
        sf_contact.pse_utilization_target_c as utilization_target,
        sf_contact.pse_utilization_target_hours_c as utilization_target_hours,
        null as weekly_pay_rate,
        null as work_phone_country,
        sf_contact.mobile_phone as work_phone_number
    from sf_contact
    left join sf_user on sf_user.id = sf_contact.pse_salesforce_user_c
),
final as (
    select * from ukg
    union all
    select * from portal
    union all
    select * from sage_intacct
    union all
    select * from salesforce
)
select * from final