{{
    config(
        materialized="table",
        schema="consolidation",
        alias="expense_item"
    )
}}

with
    si_expenseitem   as (select * from {{ source('sage_intacct', 'eexpenses_item')}}),
    sf_expense       as (select * from {{ source('salesforce', 'pse_expense_c')}} where _fivetran_deleted = false),
    sf_expensetype   as (select * from {{ source('salesforce', 'expense_type_gla_mapping_c')}} where _fivetran_deleted = false),
    sf_project       as (select * from {{ source('salesforce', 'pse_proj_c')}} where _fivetran_deleted = false),
    sf_contact       as (select * from {{ source('salesforce', 'contact')}} where _fivetran_deleted = false),
    sf_expensereport as (select * from {{ source('salesforce', 'pse_expense_report_c')}} where _fivetran_deleted = false),

sage_intacct as (
    select
        'int' as src_sys_key,
        current_timestamp as dts_created_at,
        '{{ this.name }}' as created_by,
        current_timestamp as dts_updated_at,
        '{{ this.name }}' as updated_by,
        current_timestamp as dts_eff_start,
        '9999-12-31' as dts_eff_end,
        true as bln_current,
        cast(si_expenseitem.recordno as string) as key,
        md5(si_expenseitem.recordno) as hash_key,
        cast(si_expenseitem.psa_id as string) as link,
        md5(si_expenseitem.psa_id) as hash_link,
        cast(si_expenseitem.recordkey as string) as key_expense,
        md5(si_expenseitem.recordkey) as hash_key_expense,
        cast(si_expenseitem.employeedimkey as string) as key_employee,
        md5(si_expenseitem.employeedimkey) as hash_key_employee,
        cast(si_expenseitem.projectdimkey as string) as key_project,
        md5(si_expenseitem.projectdimkey) as hash_key_project,
        cast(si_expenseitem.accountkey as string) as account_key,
        cast(si_expenseitem.accountlabelkey as string) as account_label_key,
        cast(si_expenseitem.customerdimkey as string) as customer_key,
        cast(si_expenseitem.customerid as string) as customer_id,
        cast(si_expenseitem.departmentid as string) as department_id,
        cast(si_expenseitem.detailkey as string) as detail_key,
        cast(si_expenseitem.employeeid as string) as employee_id,
        cast(si_expenseitem.recordid as string) as expense_item_id,
        cast(si_expenseitem.exppmttypekey as string) as exp_pmt_type_key,
        cast(si_expenseitem.itemdimkey as string) as item_key,
        cast(si_expenseitem.itemid as string) as item_id,
        cast(si_expenseitem.locationid as string) as location_id,
        null as milestone_id,
        cast(si_expenseitem.projectid as string) as project_id,
        cast(si_expenseitem.createdby as string) as src_created_by,
        cast(si_expenseitem.modifiedby as string) as src_modified_by,
        si_expenseitem.vendordimkey as vendor_key,
        cast(si_expenseitem.vendorid as string) as vendor_id,
        si_expenseitem.accountlabel as account_label,
        cast(si_expenseitem.accountno as string) as account_no,
        si_expenseitem.amount as amt,
        si_expenseitem.base_vat_amount as amt_base_vat,
        si_expenseitem.gl_posting_amount as amt_gl_posting,
        si_expenseitem.manual_vat_amount as amt_manual_vat,
        si_expenseitem.net_of_vat_amount as amt_net_of_vat,
        si_expenseitem.net_of_vat_base_amount as amt_net_of_vat_base,
        si_expenseitem.non_reclaim_vat_amount as amt_non_reclaim_vat_base_amount,
        si_expenseitem.nr_amount as amt_nr,
        si_expenseitem.nr_trx_amount as amt_trx_nr,
        si_expenseitem.reclaim_vat_amount as amt_reclaim_vat,
        si_expenseitem.reclaim_vat_base_amount as amt_reclaim_vat_base,
        si_expenseitem.reverse_txn_vat_amount as amt_reverse_txn_vat,
        si_expenseitem.reverse_txn_vat_base_amount as amt_reverse_txn_vat_base,
        si_expenseitem.vat_amount as amt_vat,
        si_expenseitem.baselocation as base_location,
        si_expenseitem.billable as bln_billable,
        si_expenseitem.billed as bln_billed,
        null as currency_iso_code,
        si_expenseitem.customername as customer_name,
        si_expenseitem.departmentname as department_name,
        si_expenseitem.description as description,
        si_expenseitem.description_2 as description_2,
        null as distance,
        si_expenseitem.entry_date as dte_entry,
        si_expenseitem.employeename as employee_name,
        si_expenseitem.expensedetail_reporting_category as expense_detail_reporting_category,
        null as expense_type_detail_c,
        si_expenseitem.form_1099 as form_1099,
        cast(si_expenseitem.glaccountno as string) as gl_account_no,
        si_expenseitem.glaccounttitle as gl_account_title,
        si_expenseitem.gldimline_tax_detail as gl_dim_line_tax_detail,
        si_expenseitem.gldimvat_code as gl_dim_vat_code,
        si_expenseitem.itemname as item_name,
        si_expenseitem.lineitem as line_item,
        cast(si_expenseitem.line_no as string) as line_no,
        si_expenseitem.locationname as location_name,
        si_expenseitem.non_reclaim_vat_base_amount as non_reclaim_vat_base_amount,
        si_expenseitem.nonreimbursable as non_reimbursable,
        si_expenseitem.org_amount as org_amount,
        si_expenseitem.org_currency as org_currency,
        si_expenseitem.org_exchrate as org_exchrate,
        si_expenseitem.org_exchratedate as org_exchratedate,
        si_expenseitem.org_exchratetype as org_exchratetype,
        cast(si_expenseitem.projectname as string) as projectname,
        si_expenseitem.psa_url as psa_url,
        null as pse_assignment_c,
        null as pse_audit_notes_c,
        null as pse_lost_receipt_c,
        null as pse_notes_c,
        null as pse_reimbursement_amount_in_project_currency_c,
        null as pse_reimbursement_currency_c,
        null as pse_type_c,
        si_expenseitem.quantity as quantity,
        si_expenseitem.reclaim as reclaim,
        si_expenseitem.recordtype as record_type,
        si_expenseitem.record_url as record_url,
        si_expenseitem.state as state,
        si_expenseitem.tax_use_ic_code as tax_use_ic_code,
        si_expenseitem.totalpaid as total_paid,
        si_expenseitem.totalselected as total_selected,
        si_expenseitem.trx_amount as trx_amount,
        si_expenseitem.trx_totalpaid as trx_total_paid,
        si_expenseitem.trx_totalselected as trx_total_selected,
        cast(si_expenseitem.unitrate as string) as unit_rate,
        si_expenseitem.user_exchrate as user_exch_rate,
        si_expenseitem.vat_rate as vat_rate,
        si_expenseitem.vendorname as vendor_name
    from si_expenseitem
),

salesforce as (
    select
        'sfc' as src_sys_key,
        current_timestamp as dts_created_at,
        '{{ this.name }}' as created_by,
        current_timestamp as dts_updated_at,
        '{{ this.name }}' as updated_by,
        current_timestamp as dts_eff_start,
        '9999-12-31' as dts_eff_end,
        true as bln_current,
        sf_expense.id as key,
        md5(sf_expense.id) as hash_key,
        sf_expense.id as link,
        md5(sf_expense.id) as hash_link,
        sf_expense.pse_expense_report_c as key_expense,
        md5(sf_expense.pse_expense_report_c) as hash_key_expense,
        sf_expensereport.pse_resource_c as key_employee,
        md5(sf_expensereport.pse_resource_c) as hash_key_employee,
        sf_project.intacct_record_no_c as key_project,
        md5(sf_project.intacct_record_no_c) as hash_key_project,
        null as account_key,
        null as account_label_key,
        null as customer_key,
        null as customer_id,
        null as department_id,
        null as detail_key,
        null as employee_id,
        null as expense_item_id,
        null as exp_pmt_type_key,
        null as item_key,
        sf_expensetype.intacct_item_id_c as item_id,
        sf_project.intacct_location_id_c as location_id,
        sf_expense.pse_milestone_c as milestone_id,
        sf_project.intacct_project_id_c as project_id,
        sf_expensereport.created_by_id as src_created_by,
        sf_expensereport.last_modified_by_id as src_modified_by,
        null as vendor_key,
        null as vendor_id,
        null as account_label,
        null as account_no,
        sf_expense.pse_amount_c as amt,
        null as amt_base_vat,
        null as amt_gl_posting,
        null as amt_manual_vat,
        null as amt_net_of_vat,
        null as amt_net_of_vat_base,
        null as amt_non_reclaim_vat_base_amount,
        null as amt_nr,
        null as amt_trx_nr,
        null as amt_reclaim_vat,
        null as amt_reclaim_vat_base,
        null as amt_reverse_txn_vat,
        null as amt_reverse_txn_vat_base,
        null as amt_vat,
        null as base_location,
        sf_expense.pse_billable_c as bln_billable,
        sf_expense.pse_billed_c as bln_billed,
        sf_expense.currency_iso_code as currency_iso_code,
        null as customer_name,
        null as department_name,
        sf_expense.pse_description_c as description,
        null as description_2,
        sf_expense.z_distance_c as distance,
        sf_expense.pse_expense_date_c as dte_entry,
        sf_contact.name as employee_name,
        null as expense_detail_reporting_category,
        sf_expense.expense_type_detail_c as expense_type_detail_c,
        null as form_1099,
        sf_expensetype.gl_account_c as gl_account_no,
        sf_expensetype.name as gl_account_title,
        null as gl_dim_line_tax_detail,
        null as gl_dim_vat_code,
        null as item_name,
        null as line_item,
        null as line_no,
        null as location_name,
        null as non_reclaim_vat_base_amount,
        null as non_reimbursable,
        null as org_amount,
        null as org_currency,
        null as org_exchrate,
        null as org_exchratedate,
        null as org_exchratetype,
        sf_project.name as projectname,
        null as psa_url,
        sf_expense.pse_assignment_c as pse_assignment_c,
        sf_expense.pse_audit_notes_c as pse_audit_notes_c,
        sf_expense.pse_lost_receipt_c as pse_lost_receipt_c,
        sf_expense.pse_notes_c as pse_notes_c,
        sf_expense.pse_reimbursement_amount_in_project_currency_c as pse_reimbursement_amount_in_project_currency_c,
        sf_expense.pse_reimbursement_currency_c as pse_reimbursement_currency_c,
        sf_expense.pse_type_c as pse_type_c,
        sf_expense.pse_distance_c as quantity,
        null as reclaim,
        null as record_type,
        null as record_url,
        sf_expense.pse_status_c as state,
        null as tax_use_ic_code,
        null as total_paid,
        null as total_selected,
        null as trx_amount,
        null as trx_total_paid,
        null as trx_total_selected,
        sf_expense.pse_rate_unit_c as unit_rate,
        null as user_exch_rate,
        null as vat_rate,
        null as vendor_name
    from sf_expense
    left join sf_contact on sf_expense.pse_resource_c = sf_contact.id
    left join sf_expensetype on sf_expense.gla_mapping_c = sf_expensetype.id
    left join sf_project on sf_expense.pse_project_c = sf_project.id
    left join sf_expensereport on sf_expensereport.id = sf_expense.pse_expense_report_c
),

final as (
    select * from sage_intacct
    union all
    select * from salesforce
)

select
    src_sys_key,
    cast(dts_created_at as timestamp_tz) as dts_created_at,
    created_by,
    cast(dts_updated_at as timestamp_tz) as dts_updated_at,
    updated_by,
    cast(dts_eff_start as timestamp_tz) as dts_eff_start,
    cast(dts_eff_end as timestamp_tz) as dts_eff_end,
    bln_current,
    key,
    hash_key,
    link,
    hash_link,
    key_expense,
    hash_key_expense,
    key_employee,
    hash_key_employee,
    key_project,
    hash_key_project,
    account_key,
    account_label_key,
    customer_key,
    customer_id,
    department_id,
    detail_key,
    employee_id,
    expense_item_id,
    exp_pmt_type_key,
    item_key,
    item_id,
    location_id,
    milestone_id,
    project_id,
    src_created_by,
    src_modified_by,
    cast(vendor_key as string) as vendor_key,
    vendor_id,
    account_label,
    account_no,
    cast(amt as number(38, 2)) as amt,
    amt_base_vat,
    cast(amt_gl_posting as number(38, 2)) as amt_gl_posting,
    cast(amt_manual_vat as number(38, 2)) as amt_manual_vat,
    cast(amt_net_of_vat as number(38, 2)) as amt_net_of_vat,
    cast(amt_net_of_vat_base as number(38, 2)) as amt_net_of_vat_base,
    amt_non_reclaim_vat_base_amount,
    amt_nr,
    amt_trx_nr,
    amt_reclaim_vat,
    amt_reclaim_vat_base,
    amt_reverse_txn_vat,
    amt_reverse_txn_vat_base,
    cast(amt_vat as number(38, 2)) as amt_vat,
    cast(base_location as string) as base_location,
    bln_billable,
    bln_billed,
    currency_iso_code,
    customer_name,
    department_name,
    description,
    description_2,
    cast(distance as number(38, 2)) as distance,
    dte_entry,
    employee_name,
    expense_detail_reporting_category,
    expense_type_detail_c as expense_type_detail,
    cast(form_1099 as string) as form_1099,
    gl_account_no,
    gl_account_title,
    cast(gl_dim_line_tax_detail as string) as gl_dim_line_tax_detail,
    cast(gl_dim_vat_code as string) as gl_dim_vat_code,
    item_name,
    line_item as bln_line_item,
    line_no,
    location_name,
    cast(non_reclaim_vat_base_amount as string) as non_reclaim_vat_base_amount,
    non_reimbursable as bln_non_reimbursable,
    cast(org_amount as number(38, 2)) as amt_org,
    org_currency,
    cast(org_exchrate as number(38, 6)) as org_exchrate,
    org_exchratedate as dte_org_exchrate,
    cast(org_exchratetype as string) as org_exchratetype,
    projectname,
    psa_url,
    pse_assignment_c as assignment_id,
    pse_audit_notes_c as audit_notes,
    pse_lost_receipt_c as bln_lost_receipt,
    pse_notes_c as notes,
    cast(pse_reimbursement_amount_in_project_currency_c as number(38, 2)) as amt_reimbursement_in_project_currency,
    pse_reimbursement_currency_c as reimbursement_currency,
    pse_type_c as type,
    cast(quantity as number(38, 2)) as qty,
    cast(reclaim as boolean) as reclaim,
    record_type,
    record_url,
    state,
    cast(tax_use_ic_code as string) as tax_use_ic_code,
    cast(total_paid as number(38, 2)) as amt_total_paid,
    cast(total_selected as number(38, 2)) as amt_total_selected,
    cast(trx_amount as number(38, 2)) as amt_trx,
    cast(trx_total_paid as number(38, 2)) as amt_trx_total_paid,
    cast(trx_total_selected as number(38, 2)) as amt_trx_total_selected,
    unit_rate,
    cast(user_exch_rate as number(38, 6)) as user_exch_rate,
    cast(vat_rate as number(38, 6)) as vat_rate,
    vendor_name
from final