{{ config(
    materialized = 'table'
)}}

with 
    si_project        as (select * from {{ source('sage_intacct', 'project') }} where _fivetran_deleted = false),
    sf_project        as (select * from {{ source('salesforce', 'pse_proj_c') }} where _fivetran_deleted = false),
    sf_pse_grp        as (select * from {{ source('salesforce', 'pse_grp_c') }} where _fivetran_deleted = false),
    sf_account        as (select * from {{ source('salesforce', 'account') }} where _fivetran_deleted = false),
    opportunity       as (select * from {{ source('salesforce', 'opportunity') }} where _fivetran_deleted = false),
    practice          as (select * from {{ source('salesforce', 'pse_practice_c') }} where _fivetran_deleted = false),
    psatools_projects as (select * from {{ source('psatools', 'projects') }} where _fivetran_deleted = false),
    sf_contact        as (select * from {{ source('salesforce', 'contact') }} where _fivetran_deleted = false),

sage_intacct as (
    select 
        'int' as src_sys_key,
        cast(current_timestamp as timestamp_tz) as dts_created_at,
        '{{ this.name }}' as created_by,
        cast(current_timestamp as timestamp_tz) as dts_updated_at,
        '{{ this.name }}' as updated_by,
        cast(current_timestamp as timestamp_tz) as dts_eff_start,
        cast('9999-12-31' as timestamp_tz) as dts_eff_end,
        true as bln_current,
        cast(recordno as string) as key,
        md5(recordno) as hash_key,
        cast(recordno as string) as link,
        md5(recordno) as hash_link,
        cast(megaentitykey as string) as key_entity,
        md5(megaentitykey) as hash_key_entity,
        null as account_id,
        null as assistant_project_manager_id,
        billtokey as billto_key,
        parentid as client_site_id,
        null as client_manager_id,
        null as client_manager_name,
        contactkey as contact_key,
        customerid as customer_id,
        customerkey as customer_key,
        departmentid as department_id,
        null as estimate_id,
        null as group_id,
        cast(locationid as string) as location_id,
        cast(locationid as string) as location_id_intacct,
        managerkey as manager_key,
        megaentityid as entity_id,
        null as opportunity_id,
        null as owner_id,
        parentkey as parent_key,
        null as portal_project_id,
        null as practice_id,
        null as practice_id_intacct,
        projectdeptkey as project_dept_key,
        cast(projectid as string) as project_id,
        projectlocationkey as project_location_key,
        managerid as project_manager_id,
        projecttypekey as project_type_key,
        null as purchase_order_id,
        rootparentid as root_parent_id,
        rootparentkey as root_parent_key,
        shiptokey as ship_to_key,
        cast(createdby as string) as src_created_by_id,
        cast(modifiedby as string) as src_modified_by_id,
        termskey as term_key,
        actualqty as qty_actual,
        null as amt_total_billable,
        null as amt_total_budget,
        null as assistant_project_manager_name,
        billingovermax as billing_over_max,
        billingtype as billing_type,
        null as bln_allow_expenses_without_assignments,
        null as bln_allow_time_without_assignments,
        null as bln_daily_timecard_notes_required,
        null as bln_exclude_from_project_planner,
        null as bln_is_active,
        null as bln_is_billable,
        billableappodefault as bln_is_billable_ap_po,
        billableexpdefault as bln_is_billable_expense,
        null as bln_pse_closed_for_expense_entry,
        null as bln_pse_closed_for_time_entry,
        null as bln_top_concern,
        null as bln_travel_prohibited,
        null as concern_type,
        coalesce(billto_contactname, shipto_contactname) as contact_name,
        null as contract_type,
        null as cost_expense,
        null as cost_total_awarded,
        currency as currency_iso_code,
        customername as customer_name,
        departmentname as department_name,
        enddate as dte_src_end,
        begindate as dte_src_start,
        null as dts_int_last_assignment_sync,
        null as dts_int_last_phase_code_sync,
        null as dts_int_last_project_sync,
        null as dts_last_resource_plan_review,
        null as dts_pmo_data_migration,
        null as dts_sfc_last_assignment_sync,
        null as dts_sfc_last_phase_code_sync,
        null as dts_sfc_last_project_sync,
        null as dts_sfc_last_task_sync,
        whencreated as dts_src_created,
        whenmodified as dts_src_modified,
        null as group_name,
        invoicecurrency as invoice_currency,
        null as last_resource_plan_review_by,
        null as last_synced_status,
        locationname as location_name,
        project_memo as memo,
        parentname as parent_name,
        null as pmo_comments,
        null as pnm_notes,
        null as pnm_revision,
        poamount as amt_po,
        ponumber as po_number,
        null as portal_project_code,
        projectcategory as project_category,
        description as project_description,
        name as project_name,
        projectstatus as project_status,
        projecttype as project_type,
        null as risk_rating,
        rootparentname as root_parent_name,
        null as sharepoint_url,
        status as status,
        termname as term_name,
        null as total_earned_value,
        null as total_number_of_tasks,
        null as travel_rate
    from si_project
),

salesforce as (
    select
        'sfc' as src_sys_key,
        current_timestamp as dts_created_at,
        '{{ this.name }}' as created_by,
        current_timestamp as dts_updated_at,
        '{{ this.name }}' as updated_by,
        current_timestamp as dts_eff_start,
        '9999-12-31' as dts_eff_end,
        true as bln_current,
        sf_project.id as key,
        md5(sf_project.id) as hash_key,
        sf_project.intacct_record_no_c as link,
        md5(sf_project.intacct_record_no_c) as hash_link,
        null as key_entity,
        null as hash_key_entity,
        sf_project.pse_account_c as account_id,
        null as assistant_project_manager_id,
        null as billto_key,
        sf_project.intacct_client_site_id_c as client_site_id,
        sf_account.client_manager_c as client_manager_id,
        sf_contact.name as client_manager_name,
        null as contact_key,
        null as customer_id,
        null as customer_key,
        sf_project.business_area_c as department_id,
        null as estimate_id,
        sf_project.pse_group_c as group_id,
        cast(sf_project.pse_region_c as string) as location_id,
        cast(sf_project.intacct_location_id_c as string) as location_id_intacct,
        null as manager_key,
        null as entity_id,
        sf_project.pse_opportunity_c as opportunity_id,
        sf_project.owner_id as owner_id,
        null as parent_key,
        opportunity.portal_project_id_c as portal_project_id,
        sf_project.pse_practice_c as practice_id,
        practice.intacct_id_c as practice_id_intacct,
        null as project_dept_key,
        cast(sf_project.intacct_project_id_c as string) as project_id,
        null as project_location_key,
        sf_project.pse_project_manager_c as project_manager_id,
        null as project_type_key,
        sf_project.purchase_order_c as purchase_order_id,
        null as root_parent_id,
        null as root_parent_key,
        null as ship_to_key,
        sf_project.created_by_id as src_created_by_id,
        sf_project.last_modified_by_id as src_modified_by_id,
        null as term_key,
        null as qty_actual,
        sf_project.total_billable_amount_c as amt_total_billable,
        sf_project.total_budget_c as amt_total_budget,
        null as assistant_project_manager_name,
        null as billing_over_max,
        sf_project.pse_billing_type_c as billing_type,
        sf_project.pse_allow_expenses_without_assignment_c as bln_allow_expenses_without_assignments,
        sf_project.pse_allow_timecards_without_assignment_c as bln_allow_time_without_assignments,
        sf_project.pse_daily_timecard_notes_required_c as bln_daily_timecard_notes_required,
        sf_project.pse_exclude_from_project_planner_c as bln_exclude_from_project_planner,
        sf_project.pse_is_active_c as bln_is_active,
        sf_project.pse_is_billable_c as bln_is_billable,
        null as bln_is_billable_ap_po,
        null as bln_is_billable_expense,
        sf_project.pse_closed_for_expense_entry_c as bln_pse_closed_for_expense_entry,
        sf_project.pse_closed_for_time_entry_c as bln_pse_closed_for_time_entry,
        null as bln_top_concern,
        null as bln_travel_prohibited,
        null as concern_type,
        null as contact_name,
        opportunity.contract_type_c as contract_type,
        sf_project.pse_expense_costs_c as cost_expense,
        null as cost_total_awarded,
        sf_project.currency_iso_code as currency_iso_code,
        null as customer_name,
        null as department_name,
        sf_project.pse_end_date_c as dte_src_end,
        sf_project.pse_start_date_c as dte_src_start,
        null as dts_int_last_assignment_sync,
        null as dts_int_last_phase_code_sync,
        null as dts_int_last_project_sync,
        null as dts_last_resource_plan_review,
        null as dts_pmo_data_migration,
        null as dts_sfc_last_assignment_sync,
        null as dts_sfc_last_phase_code_sync,
        null as dts_sfc_last_project_sync,
        null as dts_sfc_last_task_sync,
        sf_project.created_date as dts_src_created,
        sf_project.last_modified_date as dts_src_modified,
        sf_pse_grp.name as group_name,
        null as invoice_currency,
        null as last_resource_plan_review_by,
        null as last_synced_status,
        null as location_name,
        null as memo,
        null as parent_name,
        null as pmo_comments,
        null as pnm_notes,
        null as pnm_revision,
        null as amt_po,
        null as po_number,
        opportunity.portal_project_code_c as portal_project_code,
        sf_project.int_project_category_c as project_category,
        sf_project.int_description_c as project_description,
        sf_project.name as project_name,
        sf_project.pse_stage_c as project_status,
        sf_project.pse_project_type_c as project_type,
        null as risk_rating,
        null as root_parent_name,
        null as sharepoint_url,
        null as status,
        null as term_name,
        sf_project.total_earned_value_c as total_earned_value,
        sf_project.pse_total_number_of_tasks_c as total_number_of_tasks,
        null as travel_rate
    from sf_project
    left join opportunity on opportunity.id = sf_project.pse_opportunity_c
    left join sf_pse_grp on sf_pse_grp.id = sf_project.pse_group_c
    left join practice on practice.id = sf_project.pse_practice_c
    left join sf_account on sf_account.id = sf_project.pse_account_c
    left join sf_contact on sf_contact.id = sf_account.client_manager_c
),

psatools as (
    select 
        'psa' as src_sys_key,
        current_timestamp as dts_created_at,
        '{{ this.name }}' as created_by,
        current_timestamp as dts_updated_at,
        '{{ this.name }}' as updated_by,
        current_timestamp as dts_eff_start,
        '9999-12-31' as dts_eff_end,
        true as bln_current,
        id as key,
        md5(id) as hash_key,
        int_record_no as link,
        md5(int_record_no) as hash_link,
        null as key_entity,
        null as hash_key_entity,
        sfc_account_id as account_id,
        assistant_project_manager_id as assistant_project_manager_id,
        null as billto_key,
        int_client_site_id as client_site_id,
        client_manager_id as client_manager_id,
        null as client_manager_name,
        null as contact_key,
        int_customer_id as customer_id,
        null as customer_key,
        practice_area_id as department_id,
        estimate_id as estimate_id,
        null as group_id,
        location_id as location_id,
        int_location_id as location_id_intacct,
        null as manager_key,
        null as entity_id,
        sfc_opportunity_id as opportunity_id,
        null as owner_id,
        null as parent_key,
        id as portal_project_id,
        null as practice_id,
        null as practice_id_intacct,
        null as project_dept_key,
        project_code as project_id,
        null as project_location_key,
        project_manager_id as project_manager_id,
        null as project_type_key,
        null as purchase_order_id,
        null as root_parent_id,
        null as root_parent_key,
        null as ship_to_key,
        null as src_created_by_id,
        null as src_modified_by_id,
        null as term_key,
        null as qty_actual,
        null as amt_total_billable,
        null as amt_total_budget,
        assistant_manager_name as assistant_project_manager_name,
        null as billing_over_max,
        billing_type_id as billing_type,
        allow_expenses_without_assignments as bln_allow_expenses_without_assignments,
        allow_time_without_assignments as bln_allow_time_without_assignments,
        timecard_requires_daily_notes as bln_daily_timecard_notes_required,
        exclude_from_project_planner as bln_exclude_from_project_planner,
        null as bln_is_active,
        null as bln_is_billable,
        is_billable_ap_po as bln_is_billable_ap_po,
        is_billable_expense as bln_is_billable_expense,
        null as bln_pse_closed_for_expense_entry,
        null as bln_pse_closed_for_time_entry,
        is_top_concern as bln_top_concern,
        is_travel_prohibited as bln_travel_prohibited,
        concern_type as concern_type,
        int_contact_name as contact_name,
        null as contract_type,
        null as cost_expense,
        null as cost_total_awarded,
        int_currency as currency_iso_code,
        null as customer_name,
        null as department_name,
        end_date as dte_src_end,
        start_date as dte_src_start,
        int_last_assignment_sync as dts_int_last_assignment_sync,
        int_last_phase_code_sync as dts_int_last_phase_code_sync,
        int_last_project_sync as dts_int_last_project_sync,
        last_resource_plan_review_date as dts_last_resource_plan_review,
        pmo_data_migration_date as dts_pmo_data_migration,
        sfc_last_assignment_sync as dts_sfc_last_assignment_sync,
        sfc_last_phase_code_sync as dts_sfc_last_phase_code_sync,
        sfc_last_project_sync as dts_sfc_last_project_sync,
        sfc_last_task_sync as dts_sfc_last_task_sync,
        created_date as dts_src_created,
        null as dts_src_modified,
        null as group_name,
        null as invoice_currency,
        last_resource_plan_review_by as last_resource_plan_review_by,
        last_synced_status as last_synced_status,
        null as location_name,
        int_memo as memo,
        null as parent_name,
        pmo_comments as pmo_comments,
        pnm_notes as pnm_notes,
        pnm_revision as pnm_revision,
        int_po_amount as amt_po,
        int_po_number as po_number,
        null as portal_project_code,
        project_category as project_category,
        description as project_description,
        name as project_name,
        project_status as project_status,
        project_type as project_type,
        risk_rating as risk_rating,
        null as root_parent_name,
        sharepoint_url as sharepoint_url,
        null as status,
        term_id as term_name,
        null as total_earned_value,
        null as total_number_of_tasks,
        travel_rate as travel_rate
    from psatools_projects
),

final as (
    select * from sage_intacct
    union all
    select * from salesforce
    union all
    select * from psatools
)

select
    src_sys_key,
    dts_created_at,
    created_by,
    dts_updated_at,
    updated_by,
    dts_eff_start,
    dts_eff_end,
    bln_current,
    key,
    hash_key,
    link,
    hash_link,
    key_entity,
    hash_key_entity,
    account_id,
    assistant_project_manager_id,
    billto_key,
    client_site_id,
    client_manager_id,
    client_manager_name,
    contact_key,
    customer_id,
    customer_key,
    department_id,
    estimate_id,
    group_id,
    location_id,
    location_id_intacct,
    manager_key,
    entity_id,
    opportunity_id,
    owner_id,
    parent_key,
    portal_project_id,
    practice_id,
    practice_id_intacct,
    project_dept_key,
    project_id,
    project_location_key,
    project_manager_id,
    project_type_key,
    purchase_order_id,
    root_parent_id,
    root_parent_key,
    ship_to_key,
    src_created_by_id,
    src_modified_by_id,
    term_key,
    cast(qty_actual as number(38, 2)) as qty_actual,
    amt_total_billable,
    amt_total_budget,
    assistant_project_manager_name,
    billing_over_max,
    billing_type,
    bln_allow_expenses_without_assignments,
    bln_allow_time_without_assignments,
    bln_daily_timecard_notes_required,
    bln_exclude_from_project_planner,
    bln_is_active,
    bln_is_billable,
    bln_is_billable_ap_po,
    bln_is_billable_expense,
    bln_pse_closed_for_expense_entry,
    bln_pse_closed_for_time_entry,
    bln_top_concern,
    bln_travel_prohibited,
    concern_type,
    contact_name,
    contract_type,
    cost_expense,
    cast(cost_total_awarded as number(38, 2)) as cost_total_awarded,
    currency_iso_code,
    customer_name,
    department_name,
    dte_src_end,
    dte_src_start,
    dts_int_last_assignment_sync,
    dts_int_last_phase_code_sync,
    dts_int_last_project_sync,
    dts_last_resource_plan_review,
    dts_pmo_data_migration,
    dts_sfc_last_assignment_sync,
    dts_sfc_last_phase_code_sync,
    dts_sfc_last_project_sync,
    dts_sfc_last_task_sync,
    dts_src_created,
    dts_src_modified,
    group_name,
    invoice_currency,
    last_resource_plan_review_by,
    last_synced_status,
    location_name,
    memo,
    parent_name,
    pmo_comments,
    pnm_notes,
    pnm_revision,
   cast (  amt_po as number(38, 17)) as amt_po,
    po_number,
    portal_project_code,
    project_category,
    project_description,
    project_name,
    project_status,
    project_type,
    risk_rating,
    root_parent_name,
    sharepoint_url,
    status,
    term_name,
    total_earned_value,
    cast(total_number_of_tasks as number(38, 0)) as total_number_of_tasks,
    travel_rate
from final
