{{
    config(
        materialized="table",
        schema="consolidation",
        alias="project_phase_code"
    )
}}

with
    int as (
        select 
            'int' as src_sys_key,
            cast(current_timestamp as timestamp_tz) as dts_created_at,
            '{{ this.name }}' as created_by,
            cast(current_timestamp as timestamp_tz) as dts_updated_at,
            '{{ this.name }}' as updated_by,
            cast(current_timestamp as timestamp_tz) as dts_eff_start,
            cast('9999-12-31' as timestamp_tz ) as dts_eff_end,
            true as bln_current,
            cast(int_phase_codes.recordno as string) as key,
            md5(int_phase_codes.recordno) as hash_key,
            cast(int_phase_codes.recordno as string) as link,
            md5(int_phase_codes.recordno) as hash_link,
            cast(int_phase_codes.customerkey as string) as key_customer,
            md5(int_phase_codes.customerkey) as hash_key_customer,
            cast(int_phase_codes.itemkey as string) as key_item,
            md5(int_phase_codes.itemkey) as hash_key_item,
            cast(int_phase_codes.rootparentkey as string) as key_parent,
            md5(int_phase_codes.rootparentkey) as hash_key_parent,
            cast(int_phase_codes.projectkey as string) as key_project,
            md5(int_phase_codes.projectkey) as hash_key_project,
            null as key_approver,
            null as hash_key_approver,
            null as key_owner,
            null as hash_key_owner,
            null as key_practice_area,
            null as hash_key_practice_area,
            null as key_product,
            null as hash_key_product,
            null as key_milestone,
            null as hash_key_milestone,
            cast(int_phase_codes.customerid as string) as customer_id,
            cast(int_phase_codes.recordno as string) as int_id,
            cast(int_phase_codes.itemid as string) as item_id,
            cast(int_phase_codes.rootparentid as string) as parent_id,
            cast(int_phase_codes.projectid as string) as project_id,
            null as pts_id,
            null as pts_record_id,
            null as record_type_id,
            null as sfc_id,
            null as sfc_task_id,
            cast(int_phase_codes.createdby as string) as src_created_by_id,
            cast(int_phase_codes.modifiedby as string) as src_modified_by_id,
            cast(int_phase_codes.taskid as string) as task_id,
            null as amt_billable_entered,
            null as amt_billable_in_financials,
            null as amt_billable_submitted,
            null as amt_milestone,
            null as bln_closed_for_expense_entry,
            null as bln_closed_for_time_entry,
            int_phase_codes.billable as bln_is_billable,
            null as bln_is_custom,
            null as bln_is_deleted,
            int_phase_codes.utilized as bln_is_utilized,
            null as budget_calculated,
            null as budget_override,
            null as cost_milestone,
            null as cost_variance,
            null as currency_iso_code,
            int_phase_codes.customername as customer_name,
            int_phase_codes.description as description,
            cast(int_phase_codes.aenddate as date) as dte_end,
            cast(int_phase_codes.projectenddate as date) as dte_project_end,
            cast(int_phase_codes.abegindate as date) as dte_start,
            cast(int_phase_codes.projectbegindate as date) as dte_start_project,
            null as dts_int_last_sync,
            null as dts_sfc_phase_code_last_sync,
            null as dts_sfc_task_last_sync,
            cast(int_phase_codes.whencreated as timestamp_tz) as dts_src_created,
            cast(int_phase_codes.whenmodified as timestamp_tz) as dts_src_modified,
            null as dts_system_modstamp,
            null as hours_actual,
            null as hours_actual_timecard,
            null as hours_billable_entered,
            null as hours_planned,
            int_phase_codes.itemname as item_name,
            int_phase_codes.name as name,
            null as original_additional_budget,
            null as original_additional_hours,
            null as original_budget,
            null as original_hours,
            int_phase_codes.rootparentname as parent_name,
            int_phase_codes.projectname as project_name,
            cast(int_phase_codes.actualqty as number(38,17)) as qty_actual,
            cast(int_phase_codes.approvedqty as number(38,17)) as qty_approved,
            cast(int_phase_codes.billable_actualqty as number(38,17)) as qty_billable_actual,
            cast(int_phase_codes.billable_approvedqty as number(38,17)) as qty_billable_approved,
            int_phase_codes.record_url as record_url,
            null as scope_change_total_budget,
            null as scope_change_total_hours,
            int_phase_codes.taskstatus as status,
            null as task_count,
            null as total_earned_value,
            null as type
        from {{ source('sage_intacct', 'task') }} as int_phase_codes where _fivetran_deleted = false
    ),
    sfc_milestones as (
        select
            'sfc_milestones' as src_sys_key,
            cast(current_timestamp as timestamp_tz) as dts_created_at,
            '{{ this.name }}' as created_by,
            cast(current_timestamp as timestamp_tz) as dts_updated_at,
            '{{ this.name }}' as updated_by,
            cast(current_timestamp as timestamp_tz) as dts_eff_start,
            cast('9999-12-31' as timestamp_tz ) as dts_eff_end,
            true as bln_current,
            sfc_milestones_phase_codes.id as key,
            md5(sfc_milestones_phase_codes.id) as hash_key,
            sfc_milestones_phase_codes.intacct_record_no_c as link,
            md5(sfc_milestones_phase_codes.intacct_record_no_c) as hash_link,
            null as key_customer,
            null as hash_key_customer,
            null as key_item,
            null as hash_key_item,
            null as key_parent,
            null as hash_key_parent,
            cast(sfc_milestones_phase_codes.pse_project_c as string) as key_project,
            md5(sfc_milestones_phase_codes.pse_project_c) as hash_key_project,
            cast(sfc_milestones_phase_codes.pse_approver_c as string) as key_approver,
            md5(sfc_milestones_phase_codes.pse_approver_c) as hash_key_approver,
            cast(sfc_milestones_phase_codes.owner_id as string) as key_owner,
            md5(sfc_milestones_phase_codes.owner_id) as hash_key_owner,
            cast(sfc_milestones_phase_codes.business_area_c as string) as key_practice_area,
            md5(sfc_milestones_phase_codes.business_area_c) as hash_key_practice_area,
            null as key_product,
            null as hash_key_product,
            null as key_milestone,
            null as hash_key_milestone,
            null as customer_id,
            null as int_id,
            null as item_id,
            null as parent_id,
            null as project_id,
            null as pts_id,
            null as pts_record_id,
            cast(sfc_milestones_phase_codes.record_type_id as string) as record_type_id,
            cast(sfc_milestones_phase_codes.id as string) as sfc_id,
            null as sfc_task_id,
            cast(sfc_milestones_phase_codes.created_by_id as string) as src_created_by_id,
            cast(sfc_milestones_phase_codes.last_modified_by_id as string) as src_modified_by_id,
            cast(sfc_milestones_phase_codes.intacct_id_c as string) as task_id,
            sfc_milestones_phase_codes.billable_amount_entered_c as amt_billable_entered,
            sfc_milestones_phase_codes.pse_billable_amount_in_financials_c as amt_billable_in_financials,
            sfc_milestones_phase_codes.pse_billable_amount_submitted_c as amt_billable_submitted,
            sfc_milestones_phase_codes.pse_milestone_amount_c as amt_milestone,
            sfc_milestones_phase_codes.pse_closed_for_expense_entry_c as bln_closed_for_expense_entry,
            sfc_milestones_phase_codes.pse_closed_for_time_entry_c as bln_closed_for_time_entry,
            null as bln_is_billable,
            null as bln_is_custom,
            sfc_milestones_phase_codes.is_deleted as bln_is_deleted,
            null as bln_is_utilized,
            null as budget_calculated,
            null as budget_override,
            sfc_milestones_phase_codes.pse_milestone_cost_c as cost_milestone,
            sfc_milestones_phase_codes.cost_variance_c as cost_variance,
            sfc_milestones_phase_codes.currency_iso_code as currency_iso_code,
            null as customer_name,
            sfc_milestones_phase_codes.pse_description_c as description,
            cast(sfc_milestones_phase_codes.pse_target_date_c as date) as dte_end,
            null as dte_project_end,
            cast(sfc_milestones_phase_codes.pse_start_date_c  as date) as dte_start,
            null as dte_start_project,
            null as dts_int_last_sync,
            null as dts_sfc_phase_code_last_sync,
            null as dts_sfc_task_last_sync,
            cast(sfc_milestones_phase_codes.created_date as timestamp_tz) as dts_src_created,
            cast(sfc_milestones_phase_codes.last_modified_date as timestamp_tz) as dts_src_modified,
            cast(sfc_milestones_phase_codes.system_modstamp as timestamp_tz) as dts_system_modstamp,
            null as hours_actual,
            null as hours_actual_timecard,
            cast(sfc_milestones_phase_codes.billable_hours_entered_c as number(38,17)) as hours_billable_entered,
            null as hours_planned,
            null as item_name,
            sfc_milestones_phase_codes.name as name,
            sfc_milestones_phase_codes.original_additional_budget_c as original_additional_budget,
            cast(sfc_milestones_phase_codes.original_additional_hrs_or_units_c as number(38,17)) as original_additional_hours,
            sfc_milestones_phase_codes.original_budget_c as original_budget,
            cast(sfc_milestones_phase_codes.original_hrs_or_units_c as number(38,17)) as original_hours,
            null as parent_name,
            null as project_name,
            null as qty_actual,
            null as qty_approved,
            null as qty_billable_actual,
            null as qty_billable_approved,
            null as record_url,
            sfc_milestones_phase_codes.scope_change_total_budget_c as scope_change_total_budget,
            cast(sfc_milestones_phase_codes.scope_change_total_hrs_or_units_c as number(38,17)) as scope_change_total_hours,
            sfc_milestones_phase_codes.pse_status_c as status,
            cast(sfc_milestones_phase_codes.pse_total_number_of_tasks_c as number(38,17)) as task_count,
            sfc_milestones_phase_codes.total_earned_value_c as total_earned_value,
            sfc_milestones_phase_codes.type_c as type
        from {{ source('salesforce', 'pse_milestone_c') }} as sfc_milestones_phase_codes where _fivetran_deleted = false and is_deleted = false
    ),
    sfc_tasks as (
        select 
            'sfc_project_task' as src_sys_key,
            cast(current_timestamp as timestamp_tz) as dts_created_at,
            '{{ this.name }}' as created_by,
            cast(current_timestamp as timestamp_tz) as dts_updated_at,
            '{{ this.name }}' as updated_by,
            cast(current_timestamp as timestamp_tz) as dts_eff_start,
            cast('9999-12-31' as timestamp_tz ) as dts_eff_end,
            true as bln_current,
            sfc_tasks.id as key,
            md5(sfc_tasks.id) as hash_key,
            sfc_tasks.intacct_record_no_c as link,
            md5(sfc_tasks.intacct_record_no_c) as hash_link,
            null as key_customer,
            null as hash_key_customer,
            null as key_item,
            null as hash_key_item,
            null as key_parent,
            null as hash_key_parent,
            sfc_tasks.pse_project_c as key_project,
            md5(sfc_tasks.pse_project_c) as hash_key_project,
            null as key_approver,
            null as hash_key_approver,
            sfc_tasks.owner_id as key_owner,
            md5(sfc_tasks.owner_id) as hash_key_owner,
            null as key_practice_area,
            null as hash_key_practice_area,
            null as key_product,
            null as hash_key_product,
            sfc_tasks.pse_milestone_c as key_milestone,
            md5(sfc_tasks.pse_milestone_c) as hash_key_milestone,
            null as customer_id,
            null as int_id,
            null as item_id,
            null as parent_id,
            null as project_id,
            null as pts_id,
            null as pts_record_id,
            null as record_type_id,
            null as sfc_id,
            null as sfc_task_id,
            cast(sfc_tasks.created_by_id as string) as src_created_by_id,
            cast(sfc_tasks.last_modified_by_id  as string)as src_modified_by_id,
            cast(sfc_tasks.intacct_id_c as string) as task_id,
            null as amt_billable_entered,
            null as amt_billable_in_financials,
            null as amt_billable_submitted,
            null as amt_milestone,
            null as bln_closed_for_expense_entry,
            sfc_tasks.pse_closed_for_time_entry_c as bln_closed_for_time_entry,
            null as bln_is_billable,
            null as bln_is_custom,
            null as bln_is_deleted,
            null as bln_is_utilized,
            null as budget_calculated,
            null as budget_override,
            null as cost_milestone,
            sfc_tasks.cost_variance_c as cost_variance,
            sfc_tasks.currency_iso_code as currency_iso_code,
            null as customer_name,
            sfc_tasks.pse_description_c as description,
            cast(sfc_tasks.pse_end_date_time_c as date) as dte_end,
            null as dte_project_end,
            cast(sfc_tasks.pse_start_date_time_c as date) as dte_start,
            null as dte_start_project,
            null as dts_int_last_sync,
            null as dts_sfc_phase_code_last_sync,
            null as dts_sfc_task_last_sync,
            cast(sfc_tasks.created_date as timestamp_tz) as dts_src_created,
            cast(sfc_tasks.last_modified_date as timestamp_tz) as dts_src_modified,
            cast(sfc_tasks.system_modstamp as timestamp_tz) as dts_system_modstamp,
            cast(sfc_tasks.pse_actual_hours_c as number(38,17)) as hours_actual,
            cast(sfc_tasks.pse_timecard_actual_hours_c as number(38,17)) as hours_actual_timecard,
            null as hours_billable_entered,
            null as hours_planned,
            null as item_name,
            sfc_tasks.name as name,
            null as original_additional_budget,
            null as original_additional_hours,
            sfc_tasks.original_proposal_budget_c as original_budget,
            cast(sfc_tasks.original_proposal_hrs_or_units_c as number(38,17)) as original_hours,
            null as parent_name,
            null as project_name,
            null as qty_actual,
            null as qty_approved,
            null as qty_billable_actual,
            null as qty_billable_approved,
            null as record_url,
            null as scope_change_total_budget,
            null as scope_change_total_hours,
            sfc_tasks.pse_status_c as status,
            null as task_count,
            null as total_earned_value,
            sfc_tasks.type_c as type,
        from {{ source('salesforce', 'pse_project_task_c') }} as sfc_tasks where _fivetran_deleted = false and is_deleted = false and is_project_task_c = false
    ),
    pts as (
        select 
            'pts' as src_sys_key,
            cast(current_timestamp as timestamp_tz) as dts_created_at,
            '{{ this.name }}' as created_by,
            cast(current_timestamp as timestamp_tz) as dts_updated_at,
            '{{ this.name }}' as updated_by,
            cast(current_timestamp as timestamp_tz) as dts_eff_start,
            cast('9999-12-31' as timestamp_tz ) as dts_eff_end,
            true as bln_current,
            cast(pts.record_id as string) as key,
            md5(pts.record_id) as hash_key,
            cast(pts.int_record_no as string) as link,
            md5(pts.int_record_no) as hash_link,
            null as key_customer,
            null as hash_key_customer,
            null as key_item,
            null as hash_key_item,
            null as key_parent,
            null as hash_key_parent,
            cast(pts.project_id as string) as key_project,
            md5(pts.project_id) as hash_key_project,
            null as key_approver,
            null as hash_key_approver,
            null as key_owner,
            null as hash_key_owner,
            cast(pts.practice_area_id as string) as key_practice_area,
            md5(pts.practice_area_id) as hash_key_practice_area,
            cast(pts.product_id as string) as key_product,
            md5(pts.product_id) as hash_key_product,
            null as key_milestone,
            null as hash_key_milestone,
            null as customer_id,
            cast(pts.int_record_no as string) as int_id,
            cast(pts.int_item_id as string) as item_id,
            null as parent_id,
            null as project_id,
            cast(pts.id as string) as pts_id,
            cast(pts.record_id as string) as pts_record_id,
            null as record_type_id,
            cast(pts.sfc_phase_code_id as string) as sfc_id,
            cast(pts.sfc_task_id as string) as sfc_task_id,
            null as src_created_by_id,
            null as src_modified_by_id,
            cast(pts.int_task_id as string) as task_id,
            null as amt_billable_entered,
            null as amt_billable_in_financials,
            null as amt_billable_submitted,
            null as amt_milestone,
            null as bln_closed_for_expense_entry,
            pts.closed_for_time_entry as bln_closed_for_time_entry,
            pts.is_billable as bln_is_billable,
            pts.is_custom as bln_is_custom,
            null as bln_is_deleted,
            pts.utilized as bln_is_utilized,
            cast(pts.calculated_budget as number(38, 17))  as budget_calculated,
            cast(pts.budget_override as number(38, 17))  as budget_override,
            null as cost_milestone,
            null as cost_variance,
            null as currency_iso_code,
            null as customer_name,
            pts.description as description,
            null as dte_end,
            null as dte_project_end,
            null as dte_start,
            null as dte_start_project,
            cast(pts.int_last_phase_code_sync as timestamp_tz) as dts_int_last_sync,
            cast(pts.sfc_last_phase_code_sync as timestamp_tz) as dts_sfc_phase_code_last_sync,
            cast(pts.sfc_last_task_sync as timestamp_tz) as dts_sfc_task_last_sync,
            null as dts_src_created,
            null as dts_src_modified,
            null as dts_system_modstamp,
            null as hours_actual,
            null as hours_actual_timecard,
            null as hours_billable_entered,
            cast(pts.planned_hours as number(38, 17)) as hours_planned,
            null as item_name,
            pts.name as name,
            null as original_additional_budget,
            null as original_additional_hours,
            cast(ifnull(pts.budget_override, calculated_budget) as number(38,17)) as original_budget,
            null as original_hours,
            null as parent_name,
            null as project_name,
            null as qty_actual,
            null as qty_approved,
            null as qty_billable_actual,
            null as qty_billable_approved,
            null as record_url,
            null as scope_change_total_budget,
            null as scope_change_total_hours,
            pts.status as status,
            null as task_count,
            null as total_earned_value,
            pts.type as type,
        from {{ source('psatools', 'projects_phase_codes') }} as pts where _fivetran_deleted = false
    ),
    final as (
        select * from int
        union (select * from sfc_milestones)
        union (select * from sfc_tasks)
        union (select * from pts)
    )
    select * from final