version: 2

models:
  - name: project
    description: Model for consolidated project data
    config:
      contract:
        enforced: true
    tests:
      - project_source_count_match_psa
      - project_source_count_match_sage
      - project_source_count_match_sf
    columns:
      - name: SRC_SYS_KEY
        data_type: VARCHAR(250)
      - name: DTS_CREATED_AT
        data_type: TIMESTAMP_TZ(9)
      - name: CREATED_BY
        data_type: VARCHAR(250)
      - name: DTS_UPDATED_AT
        data_type: TIMESTAMP_TZ(9)
      - name: UPDATED_BY
        data_type: VARCHAR(250)
      - name: DTS_EFF_START
        data_type: TIMESTAMP_TZ(9)
      - name: DTS_EFF_END
        data_type: TIMESTAMP_TZ(9)
      - name: BLN_CURRENT
        data_type: BOOLEAN
      - name: KEY
        data_type: VARCHAR(5000)
        tests:
          - not_null
          - unique
      - name: HASH_KEY
        data_type: VARCHAR(32)
        tests:
          - not_null
          - unique
      - name: LINK
        data_type: VARCHAR(5000)
      - name: HASH_LINK
        data_type: VARCHAR(32)
      - name: KEY_ENTITY
        data_type: VARCHAR(5000)
      - name: HASH_KEY_ENTITY
        data_type: VARCHAR(32)
      - name: ACCOUNT_ID
        data_type: VARCHAR(5000)
      - name: ASSISTANT_PROJECT_MANAGER_ID
        data_type: VARCHAR(5000)
      - name: BILLTO_KEY
        data_type: NUMBER(38,0)
      - name: CLIENT_SITE_ID
        data_type: VARCHAR(5000)
      - name: CONTACT_KEY
        data_type: NUMBER(38,0)
      - name: CUSTOMER_ID
        data_type: VARCHAR(5000)
      - name: CUSTOMER_KEY
        data_type: NUMBER(38,0)
      - name: DEPARTMENT_ID
        data_type: VARCHAR(5000)
      - name: ESTIMATE_ID
        data_type: VARCHAR(5000)
      - name: GROUP_ID
        data_type: VARCHAR(100)
      - name: LOCATION_ID
        data_type: VARCHAR(5000)
      - name: LOCATION_ID_INTACCT
        data_type: VARCHAR(5000)
      - name: MANAGER_KEY
        data_type: NUMBER(38,0)
      - name: ENTITY_ID
        data_type: VARCHAR(5000)
      - name: OPPORTUNITY_ID
        data_type: VARCHAR(5000)
      - name: OWNER_ID
        data_type: VARCHAR(5000)
      - name: PARENT_KEY
        data_type: NUMBER(38,0)
      - name: PORTAL_PROJECT_ID
        data_type: VARCHAR(5000)
      - name: PRACTICE_ID
        data_type: VARCHAR(100)
      - name: PRACTICE_ID_INTACCT
        data_type: VARCHAR(5000)
      - name: PROJECT_DEPT_KEY
        data_type: NUMBER(38,0)
      - name: PROJECT_ID
        data_type: VARCHAR(5000)
      - name: PROJECT_LOCATION_KEY
        data_type: NUMBER(38,0)
      - name: PROJECT_MANAGER_ID
        data_type: VARCHAR(5000)
      - name: PROJECT_TYPE_KEY
        data_type: NUMBER(38,0)
      - name: PURCHASE_ORDER_ID
        data_type: VARCHAR(5000)
      - name: ROOT_PARENT_ID
        data_type: VARCHAR(5000)
      - name: ROOT_PARENT_KEY
        data_type: NUMBER(38,0)
      - name: SHIP_TO_KEY
        data_type: NUMBER(38,0)
      - name: SRC_CREATED_BY_ID
        data_type: VARCHAR(250)
      - name: SRC_MODIFIED_BY_ID
        data_type: VARCHAR(250)
      - name: TERM_KEY
        data_type: NUMBER(38,0)
      - name: QTY_ACTUAL
        data_type: NUMBER(38,17)
      - name: AMT_TOTAL_BILLABLE
        data_type: NUMBER(38,17)
      - name: AMT_TOTAL_BUDGET
        data_type: NUMBER(38,17)
      - name: ASSISTANT_PROJECT_MANAGER_NAME
        data_type: VARCHAR(5000)
      - name: BILLING_OVER_MAX
        data_type: VARCHAR(5000)
      - name: BILLING_TYPE
        data_type: VARCHAR(5000)
      - name: BLN_ALLOW_EXPENSES_WITHOUT_ASSIGNMENTS
        data_type: BOOLEAN
      - name: BLN_ALLOW_TIME_WITHOUT_ASSIGNMENTS
        data_type: BOOLEAN
      - name: BLN_DAILY_TIMECARD_NOTES_REQUIRED
        data_type: BOOLEAN
      - name: BLN_EXCLUDE_FROM_PROJECT_PLANNER
        data_type: BOOLEAN
      - name: BLN_IS_ACTIVE
        data_type: BOOLEAN
      - name: BLN_IS_BILLABLE
        data_type: BOOLEAN
      - name: BLN_IS_BILLABLE_AP_PO
        data_type: BOOLEAN
      - name: BLN_IS_BILLABLE_EXPENSE
        data_type: BOOLEAN
      - name: BLN_PSE_CLOSED_FOR_EXPENSE_ENTRY
        data_type: BOOLEAN
      - name: BLN_PSE_CLOSED_FOR_TIME_ENTRY
        data_type: BOOLEAN
      - name: BLN_TOP_CONCERN
        data_type: BOOLEAN
      - name: BLN_TRAVEL_PROHIBITED
        data_type: BOOLEAN
      - name: CONCERN_TYPE
        data_type: VARCHAR(5000)
      - name: CONTACT_NAME
        data_type: VARCHAR(5000)
      - name: CONTRACT_TYPE
        data_type: VARCHAR(5000)
      - name: COST_EXPENSE
        data_type: NUMBER(38,17)
      - name: COST_TOTAL_AWARDED
        data_type: NUMBER(38,17)
      - name: CURRENCY_ISO_CODE
        data_type: VARCHAR(20)
      - name: CUSTOMER_NAME
        data_type: VARCHAR(5000)
      - name: DEPARTMENT_NAME
        data_type: VARCHAR(5000)
      - name: DTE_SRC_END
        data_type: DATE
      - name: DTE_SRC_START
        data_type: DATE
      - name: DTS_INT_LAST_ASSIGNMENT_SYNC
        data_type: TIMESTAMP_NTZ(9)
      - name: DTS_INT_LAST_PHASE_CODE_SYNC
        data_type: TIMESTAMP_NTZ(9)
      - name: DTS_INT_LAST_PROJECT_SYNC
        data_type: TIMESTAMP_NTZ(9)
      - name: DTS_LAST_RESOURCE_PLAN_REVIEW
        data_type: TIMESTAMP_NTZ(9)
      - name: DTS_PMO_DATA_MIGRATION
        data_type: TIMESTAMP_NTZ(9)
      - name: DTS_SFC_LAST_ASSIGNMENT_SYNC
        data_type: TIMESTAMP_NTZ(9)
      - name: DTS_SFC_LAST_PHASE_CODE_SYNC
        data_type: TIMESTAMP_NTZ(9)
      - name: DTS_SFC_LAST_PROJECT_SYNC
        data_type: TIMESTAMP_NTZ(9)
      - name: DTS_SFC_LAST_TASK_SYNC
        data_type: TIMESTAMP_NTZ(9)
      - name: DTS_SRC_CREATED
        data_type: TIMESTAMP_TZ(9)
      - name: DTS_SRC_MODIFIED
        data_type: TIMESTAMP_TZ(9)
      - name: GROUP_NAME
        data_type: VARCHAR(5000)
      - name: INVOICE_CURRENCY
        data_type: VARCHAR(20)
      - name: LAST_RESOURCE_PLAN_REVIEW_BY
        data_type: VARCHAR(5000)
      - name: LAST_SYNCED_STATUS
        data_type: VARCHAR(5000)
      - name: LOCATION_NAME
        data_type: VARCHAR(5000)
      - name: MEMO
        data_type: VARCHAR(5000)
      - name: PARENT_NAME
        data_type: VARCHAR(5000)
      - name: PMO_COMMENTS
        data_type: VARCHAR(5000)
      - name: PNM_NOTES
        data_type: VARCHAR(5000)
      - name: PNM_REVISION
        data_type: NUMBER(38,0)
      - name: AMT_PO
        data_type: NUMBER(38,17)
      - name: PO_NUMBER
        data_type: VARCHAR(5000)
      - name: PORTAL_PROJECT_CODE
        data_type: VARCHAR(5000)
      - name: PROJECT_CATEGORY
        data_type: VARCHAR(5000)
      - name: PROJECT_DESCRIPTION
        data_type: VARCHAR(5000)
      - name: PROJECT_NAME
        data_type: VARCHAR(5000)
      - name: PROJECT_STATUS
        data_type: VARCHAR(5000)
      - name: PROJECT_TYPE
        data_type: VARCHAR(5000)
      - name: RISK_RATING
        data_type: VARCHAR(5000)
      - name: ROOT_PARENT_NAME
        data_type: VARCHAR(5000)
      - name: SHAREPOINT_URL
        data_type: VARCHAR(5000)
      - name: STATUS
        data_type: VARCHAR(5000)
      - name: TERM_NAME
        data_type: VARCHAR(5000)
      - name: TOTAL_EARNED_VALUE
        data_type: NUMBER(38,17)
      - name: TOTAL_NUMBER_OF_TASKS
        data_type: NUMBER(38,17)
      - name: TRAVEL_RATE
        data_type: NUMBER(38,17)
