{{
    config(
        materialized="table",
        schema="consolidation",
        alias="sales_proposal"
    )
}}

with
    sfc_proposal as (select * from {{ source("salesforce", "quote") }} where _fivetran_deleted = false),

final as (
    select
        'sfc' as src_sys_key,
        cast(current_timestamp as timestamp_tz) as dts_created_at,
        '{{ this.name }}' as created_by,
        cast(current_timestamp as timestamp_tz) as dts_updated_at,
        '{{ this.name }}' as updated_by,
        cast(current_timestamp as timestamp_tz) as dts_eff_start,
        cast('9999-12-31' as timestamp_tz ) as dts_eff_end,
        true as bln_current,
        id as key,
        md5(id) as hash_key,
        id as link,
        md5(id) as hash_link,
        account_id as key_account_id,
        md5(account_id) as hash_key_account_id,
        account_owner_c as key_account_owner,
        md5(account_owner_c) as hash_key_account_owner,
        approver_1_c as key_approver_1,
        md5(approver_1_c) as hash_key_approver_1,
        approver_2_c as key_approver_2,
        md5(approver_2_c) as hash_key_approver_2,
        approver_3_c as key_approver_3,
        md5(approver_3_c) as hash_key_approver_3,
        approver_4_c as key_approver_4,
        md5(approver_4_c) as hash_key_approver_4,
        approver_5_c as key_approver_5,
        md5(approver_5_c) as hash_key_approver_5,
        approver_6_c as key_approver_6,
        md5(approver_6_c) as hash_key_approver_6,
        approver_7_c as key_approver_7,
        md5(approver_7_c) as hash_key_approver_7,
        approver_8_c as key_approver_8,
        md5(approver_8_c) as hash_key_approver_8,
        approver_9_c as key_approver_9,
        md5(approver_9_c) as hash_key_approver_9,
        approver_10_c as key_approver_10,
        md5(approver_10_c) as hash_key_approver_10,
        contact_id as key_contact,
        md5(contact_id) as hash_key_contact,
        opportunity_id as key_opportunity,
        md5(opportunity_id) as hash_key_opportunity,
        owner_id as key_owner_id,
        md5(owner_id) as hash_key_owner_id,
        pricebook_2_id as key_pricebook,
        md5(pricebook_2_id) as hash_key_pricebook,
        project_c as key_project,
        md5(project_c) as hash_key_project,
        regional_manager_c as key_regional_manager,
        md5(regional_manager_c) as hash_key_regional_manager,
        reviewer_1_c as key_reviewer_1,
        md5(reviewer_1_c) as hash_key_reviewer_1,
        reviewer_2_c as key_reviewer_2,
        md5(reviewer_2_c) as hash_key_reviewer_2,
        reviewer_3_c as key_reviewer_3,
        md5(reviewer_3_c) as hash_key_reviewer_3,
        reviewer_4_c as key_reviewer_4,
        md5(reviewer_4_c) as hash_key_reviewer_4,
        reviewer_5_c as key_reviewer_5,
        md5(reviewer_5_c) as hash_key_reviewer_5,
        vice_president_c as key_vice_president,
        md5(vice_president_c) as hash_key_vice_president,
        estimate_id_c as estimate_id,
        created_by_id as src_created_by_id,
        last_modified_by_id as src_modified_by_id,
        grand_total as amt_grand_total,
        po_amount_awarded_c as amt_po_awarded,
        is_syncing as bln_is_syncing,
        business_areas_c as business_areas,
        currency_iso_code as currency_iso_code,
        description as description,
        created_date as dts_src_created,
        last_modified_date as dts_src_modified,
        system_modstamp as dts_system_modstamp,
        internal_approval_date_c as dte_internal_approval,
        name as name,
        pst_assist_c as pst_assist,
        quote_number as quote_number,
        status as status,
        type_of_request_c as type_of_request
    from sfc_proposal
) select * from final
