{{
    config(
        materialized="table",
        schema="consolidation",
        alias="sales_user"
    )
}}

with
    sfc_users as (
        select * from {{ source("salesforce", "user") }} where _fivetran_deleted = false
    ),
    final as (
        select 
            'sfc' as src_sys_key,
            cast(current_timestamp as timestamp_tz) as dts_created_at,
            '{{ this.name }}' as created_by,
            cast(current_timestamp as timestamp_tz) as dts_updated_at,
            '{{ this.name }}' as updated_by,
            cast(current_timestamp as timestamp_tz) as dts_eff_start,
            cast('9999-12-31' as timestamp_tz ) as dts_eff_end,
            true as bln_current,
            sfc.id as key,
            md5(sfc.id) as hash_key,
            sfc.id as link,
            md5(sfc.id) as hash_link,
            sfc.delegated_approver_id as key_delegated_approver,
            md5(sfc.delegated_approver_id) as hash_key_delegated_approver,
            sfc.manager_id as key_supervisor,
            md5(sfc.manager_id) as hash_key_supervisor,
            sfc.cx_client_c as cx_client_id,
            sfc.cx_project_c as cx_project_id,
            sfc.created_by_id as src_created_by_id,
            sfc.last_modified_by_id as src_modified_by_id,
            sfc.last_modified_by_id as user_role_id,
            sfc.ukg_employee_id_c as ukg_employee_id_c,
            sfc.ukg_person_id_c as ukg_person_id,
            sfc.alias as alias,
            cast(sfc.amr_closed_won_goal_c as number(28,17)) as amt_amr_closed_won_goal,
            cast(sfc.closed_won_goal_c as number(28,17)) as amt_closed_won_goal,
            cast(sfc.cqv_aut_closed_won_goal_c as number(28,17)) as amt_cqv_aut_closed_won_goal,
            cast(sfc.dc_closed_won_goal_c as number(28,17)) as amt_dc_closed_won_goal,
            cast(sfc.hps_closed_won_goal_c as number(28,17)) as amt_hps_closed_won_goal,
            cast(sfc.pmt_closed_won_goal_c as number(28,17)) as amt_pmt_closed_won_goal,
            cast(sfc.ppm_closed_won_goal_c as number(28,17)) as amt_ppm_closed_won_goal,
            cast(sfc.qcr_closed_won_goal_c as number(28,17)) as amt_qcr_closed_won_goal,
            cast(sfc.submitted_proposal_goal_c as number(28,17)) as amt_submitted_proposal_goal,
            cast(sfc.total_price_submitted_c as number(28,17)) as amt_total_price_submitted,
            cast(sfc.total_price_won_c as number(28,17)) as amt_total_price_won,
            sfc.cx_internal_c as bln_cx_internal,
            sfc.forecast_enabled as bln_forecast_enabled,
            sfc.has_sales_quota_c as bln_has_sales_quota,
            sfc.has_user_verified_email as bln_has_user_verified_email,
            sfc.has_user_verified_phone as bln_has_user_verified_phone,
            sfc.is_active as bln_is_active,
            sfc.is_profile_photo_active as bln_is_profile_photo_active,
            sfc.receives_admin_info_emails as bln_receives_admin_info_emails,
            sfc.receives_info_emails as bln_receives_info_emails,
            sfc.business_area_c as business_area,
            sfc.community_nickname as community_nickname,
            sfc.company_name as company_name,
            sfc.country as country,
            sfc.country_code as country_code,
            sfc.currency_iso_code as currency_iso_code,
            sfc.cx_client_name_c as cx_client_name,
            sfc.cx_project_name_c as cx_project_name,
            sfc.db_region_c as db_region,
            sfc.default_currency_iso_code as default_currency_iso_code,
            sfc.default_group_notification_frequency as default_group_notification_frequency,
            sfc.department as department,
            sfc.digest_frequency as digest_frequency,
            sfc.division as division,
            sfc.last_login_date as dts_last_login_date,
            sfc.password_expiration_date as dts_password_expiration_date,
            sfc.created_date as dts_src_created,
            sfc.last_modified_date as dts_src_modified,
            sfc.system_modstamp as dts_system_modstamp,
            sfc.email as email,
            sfc.email_encoding_key as email_encoding_key,
            sfc.employee_number as employee_number,
            sfc.end_day as end_day,
            sfc.federation_identifier as federation_identifier,
            sfc.first_name as first_name,
            sfc.language_locale_key as language_locale_key,
            sfc.last_name as last_name,
            sfc.locale_sid_key as locale_sid_key,
            sfc.middle_name as middle_name,
            sfc.mobile_phone as mobile_phone,
            sfc.name as name,
            sfc.phone as phone,
            sfc.profile_id as profile_id,
            sfc.signature as signature,
            sfc.start_day as start_day,
            sfc.state as state,
            sfc.state_code as state_code,
            sfc.time_zone_sid_key as time_zone_sid_key,
            sfc.title as title,
            sfc.ukg_employee_number_c as ukg_employee_number,
            sfc.user_type as user_type,
            sfc.username as user_name
        from sfc_users sfc
    )

select * from final