{{
    config(
        materialized="table",
        schema="consolidation",
        alias="sales_account"
    )
}}

with
    sfc_account as (select * from {{ source("salesforce", "account") }} where _fivetran_deleted = false),

final as (
    select
        'sfc' as src_sys_key,
        cast(current_timestamp as timestamp_tz) as dts_created_at,
        '{{ this.name }}' as created_by,
        cast(current_timestamp as timestamp_tz) as dts_updated_at,
        '{{ this.name }}' as updated_by,
        cast(current_timestamp as timestamp_tz) as dts_eff_start,
        cast('9999-12-31' as timestamp_tz ) as dts_eff_end,
        true as bln_current,
        id as key,
        md5(id) as hash_key,
        id as link,
        md5(id) as hash_link,
        client_manager_c as key_client_manager,
        md5(client_manager_c) as hash_key_client_manager,
        key_account_manager_c as key_account_manager,
        md5(key_account_manager_c) as hash_key_account_manager,
        location_new_c as key_location,
        md5(location_new_c) as hash_key_location,
        owner_id as key_owner,
        md5(owner_id) as hash_key_owner,
        parent_id as key_parent_account,
        md5(parent_id) as hash_key_parent_account,
        practice_c as key_practice,
        md5(practice_c) as hash_key_practice,
        account_coordinator_c as key_account_coordinator,
        md5(account_coordinator_c) as hash_key_account_coordinator,
        rate_card_set_c as key_rate_card_set,
        md5(rate_card_set_c) as hash_key_rate_card_set,
        external_id_c as external_id,
        intacct_customer_id_c as intacct_customer_id,
        intact_id_c as intacct_id,
        created_by_id as src_created_by_id,
        last_modified_by_id as src_modified_by_id,
        account_source as account_source,
        cast(annual_revenue as number(38, 2)) as annual_revenue,
        billing_city as billing_city,
        billing_country as billing_country,
        billing_country_code as billing_country_code,
        billing_postal_code as billing_postal_code,
        billing_state as billing_state,
        billing_state_code as billing_state_code,
        billing_street as billing_street,
        is_confidential_account_c as bln_is_confidential_account,
        is_key_account_c as bln_is_key_account,
        msa_in_place_c as bln_msa_in_place,
        currency_iso_code as currency_iso_code,
        description as description,
        division_c as division,
        last_activity_date as dte_last_activity,
        created_date as dts_src_created,
        last_modified_date as dts_src_modified,
        system_modstamp as dts_system_modstamp,
        fax as fax,
        grade_c as grade,
        industry as industry,
        kare_c as kare_designation,
        name as name,
        number_of_employees as number_of_employees,
        payment_terms_c as payment_terms,
        phone as phone,
        rating as rating,
        type as type,
        website as website,
    from sfc_account
) select * from final
