{{
    config(
        materialized="table",
        schema="consolidation",
        alias="sales_opportunity"
    )
}}

with
    sfc_opportunity as (select * from {{ source("salesforce", "opportunity") }} where _fivetran_deleted = false),

final as (
    select
        'sfc' as src_sys_key,
        cast(current_timestamp as timestamp_tz) as dts_created_at,
        '{{ this.name }}' as created_by,
        cast(current_timestamp as timestamp_tz) as dts_updated_at,
        '{{ this.name }}' as updated_by,
        cast(current_timestamp as timestamp_tz) as dts_eff_start,
        cast('9999-12-31' as timestamp_tz ) as dts_eff_end,
        true as bln_current,
        id as key,
        md5(id) as hash_key,
        id as link,
        md5(id) as hash_link,
        account_id as key_account,
        md5(account_id) as hash_key_account,
        estimate_id_c as key_estimate,
        md5(estimate_id_c) as hash_key_estimate,
        identified_by_c as key_identified_by,
        md5(identified_by_c) as hash_key_identified_by,
        owner_id as key_owner,
        md5(owner_id) as hash_key_owner,
        pricebook_2_id as key_price_book_entry,
        md5(pricebook_2_id) as hash_key_price_book_entry,
        project_c as key_project,
        md5(project_c) as hash_key_project,
        pse_parent_opportunity_c as key_parent_opportunity,
        md5(pse_parent_opportunity_c) as hash_key_parent_opportunity,
        pse_practice_c as key_practice,
        md5(pse_practice_c) as hash_key_practice,
        pse_region_c as key_location,
        md5(pse_region_c) as hash_key_location,
        rate_card_set_c as key_rate_card_set,
        md5(rate_card_set_c) as hash_key_rate_card_set,
        synced_quote_id as key_proposal,
        md5(synced_quote_id) as hash_key_proposal,
        campaign_id as campaign_id,
        contact_id as contact_id,
        estimate_id_c as estimate_id,
        external_id_c as external_id,
        last_amount_changed_history_id as last_amount_changed_history_id,
        last_close_date_changed_history_id as last_close_date_changed_history_id,
        portal_project_id_c as portal_project_id_c,
        created_by_id as src_created_by_id,
        last_modified_by_id as src_modified_by_id,
        amount as amt,
        child_opportunities_amount_c as amt_child_opportunities,
        child_po_amount_awarded_c as amt_child_po_awarded,
        contingency_budget_c as amt_contingency_budget,
        expected_revenue as amt_expected_revenue,
        labor_budget_c as amt_labor_budget,
        other_budget_c as amt_other_budget,
        po_amount_awarded_c as amt_po_awarded,
        subcontractor_budget_c as amt_subcontractor_budget,
        travel_budget_c as amt_travel_budget,
        budget_confirmed_c as bln_budget_confirmed,
        currency_confirmed_c as bln_currency_confirmed,
        bypass_po_or_loi_c as bln_has_bypass_po_or_loi,
        letter_of_intent_received_c as bln_has_letter_of_intent_received,
        has_open_activity as bln_has_open_activity,
        has_opportunity_line_item as bln_has_opportunity_line_item,
        has_overdue_task as bln_has_overdue_task,
        signed_purchase_order_c as bln_has_signed_purchase_order,
        signed_sla_c as bln_has_signed_sla,
        pse_is_change_request_c as bln_is_change_request,
        is_closed as bln_is_closed,
        converted_c as bln_is_converted,
        is_covid_19_vaccine_c as bln_is_covid_19_vaccine,
        created_from_lead_c as bln_is_created_from_lead,
        mvp_c as bln_is_mvp,
        is_on_hold_c as bln_is_on_hold,
        is_won as bln_is_won,
        bv_cai_proposal_no_c as bv_cai_proposal_no,
        cai_team_engaged_in_pursuit_c as cai_team_engaged_in_pursuit,
        closed_won_reason_c as closed_won_reason,
        contract_type_c as contract_type,
        currency_iso_code as currency_iso_code,
        description as description,
        close_date as dte_close,
        customer_po_awarded_date_c as dte_customer_po_awarded,
        estimated_project_end_date_c as dte_estimated_project_end,
        estimated_project_start_date_c as dte_estimated_project_start,
        last_activity_date as dte_last_activity,
        proposal_submitted_date_c as dte_proposal_submitted,
        stage_last_updated_c as dte_stage_last_updated,
        cast (last_stage_change_date as timestamp_tz) as dts_last_stage_change,
        cast (created_date as timestamp_tz) as dts_src_created,
        cast (last_modified_date as timestamp_tz) as dts_src_modified,
        cast (system_modstamp as timestamp_tz) as dts_system_modstamp,
        cast ( duration_closed_won_c as number(38,0)) as duration_closed_won,
        cast (duration_interview_presentation_c as number(38,0)) as duration_interview_presentation,
        cast (duration_negotiation_review_c as number(38,0)) as duration_negotiation_review,
        cast (duration_proposal_approved_c as number(38,0)) as duration_proposal_approved,
        cast (duration_proposal_development_c as number(38,0)) as duration_proposal_development,
        cast (duration_proposal_submitted_c as number(38,0)) as duration_proposal_submitted,
        cast (duration_prospecting_qualification_c as number(38,0)) as duration_prospecting_qualification,
        cast (duration_solution_development_c as number(38,0)) as duration_solution_development,
        fiscal as fiscal,
        fiscal_quarter as fiscal_quarter,
        fiscal_year as fiscal_year,
        forecast_category as forecast_category,
        forecast_category_name as forecast_category_name,
        kare_c as kare,
        lead_source as lead_source,
        loss_reason_c as loss_reason_c,
        loss_reason_description_c as loss_reason_description_c,
        name as name,
        next_step as next_step,
        or_oe_c as or_oe_c,
        portal_project_code_c as portal_project_code_c,
        cast (probability as number(38,0)) as probability,
        scope_type_c as scope_type_c,
        stage_name as stage_name,
        subtype_c as subtype_c,
        cast (total_opportunity_quantity as number(38,0)) as total_opportunity_quantity,
        type_c as type_c,
    from sfc_opportunity
) select * from final
