{{ config(
    materialized='table',
) }}

with 
    sf_timesheetentry as (select * from {{ ref('int_sf_timesheetentry') }}),
    si_timesheetentry as (select * from {{ source('sage_intacct', 'timesheetentry') }} where _fivetran_deleted = false),
    si_timesheet      as (select * from {{ source('sage_intacct', 'timesheet') }} where _fivetran_deleted = false),
    sf_contact        as (select * from {{ source('salesforce', 'contact') }} where _fivetran_deleted = false),
    sf_project        as (select * from {{ source('salesforce', 'pse_proj_c') }} where _fivetran_deleted = false),
    sf_project_task   as (select * from {{ source('salesforce', 'pse_project_task_c') }} where _fivetran_deleted = false),
    si_filtered       as (
                            select 
                                * 
                            from si_timesheetentry
                            qualify row_number() over (
                                partition by projectid, employeeid, entrydate, taskkey 
                                order by whenmodified desc
                            ) = 1
                        ),

sage_intacct as (
    select
        'sin' as src_sys_key,
        current_timestamp as dts_created_at,
        '{{ this.model }}' as created_by,
        current_timestamp as dts_updated_at,
        '{{ this.model }}' as updated_by,
        current_timestamp as dts_eff_start,
        '9999-12-31' as dts_eff_end,
        true as bln_current,
        si_timesheetentry.recordno as key,
        md5(si_timesheetentry.recordno) as hash_key,
        si_timesheetentry.recordno as link,
        md5(si_timesheetentry.recordno) as hash_link,
        cast(si_timesheetentry.timesheetkey as string) as key_timesheet,
        md5(si_timesheetentry.timesheetkey) as hash_key_timesheet,
        cast(si_timesheetentry.employeedimkey as string) as key_employee,
        md5(si_timesheetentry.employeedimkey) as hash_key_employee,
        cast(si_timesheet.megaentitykey as string) as key_entity,
        md5(si_timesheet.megaentitykey) as hash_key_entity,
        cast(si_timesheetentry.projectkey as string) as key_project,
        md5(si_timesheetentry.projectkey) as hash_key_project,
        si_timesheetentry.taskkey as key_task,
        cast(si_timesheetentry.taskkey as string) as hash_key_task,
        concat(si_timesheetentry.projectid, si_timesheetentry.employeeid, si_timesheetentry.taskid, si_timesheetentry.entrydate) as key_timesheet_entry,
        md5(concat(si_timesheetentry.projectid, si_timesheetentry.employeeid, si_timesheetentry.taskid, si_timesheetentry.entrydate)) as hash_key_timesheet_entry,
        si_timesheetentry.billuacctkey as billu_acct_key,
        si_timesheetentry.customerid as customer_id,
        si_timesheetentry.departmentid as department_id,
        si_timesheetentry.departmentkey as department_key,
        si_timesheetentry.employee_earningtypekey as employee_earning_type_key,
        si_timesheetentry.employeeid as employee_id_intacct,
        si_timesheetentry.itemid as item_id,
        cast(si_timesheetentry.itemkey as string) as item_key,
        cast(si_timesheetentry.laborglbatchkey as string) as labor_gl_batch_key,
        si_timesheetentry.locationid as location_id,
        cast(si_timesheetentry.locationkey as string) as location_key,
        cast(si_timesheetentry.nonbillnuacctkey as string) as non_billnu_acct_key,
        cast(si_timesheetentry.nonbilluacctkey as string) as non_billu_acct_key,
        si_timesheetentry.projectid as project_id,
        cast(si_timesheetentry.createdby as string) as src_created_by_id,
        cast(si_timesheetentry.modifiedby as string) as src_modified_by_id,
        cast(si_timesheetentry.statglbatchkey as string) as stat_gl_batch_key,
        cast(si_timesheetentry.statjournalkey as string) as stat_journal_key,
        si_timesheetentry.taskid as task_id,
        si_timesheetentry.laborglentryamount as amt_labor_gl_entry,
        si_timesheetentry.laborglentrytrxamount as amt_labor_glentry_trx,
        si_timesheetentry.statglentryamount as amt_stat_gl_entry,
        null as bill_rate,
        si_timesheetentry.billable as bln_billable,
        si_timesheetentry.billed as bln_billed,
        si_timesheetentry.customername as customer_name,
        si_timesheetentry.departmentname as department_name,
        si_timesheetentry.entrydate as dte_entry,
        si_timesheetentry.ts_glpostdate as dte_gl_post,
        si_timesheetentry.whencreated as dte_src_created,
        si_timesheetentry.ts_enddate as dte_src_end,
        si_timesheetentry.whenmodified as dte_src_modified,
        si_timesheetentry.ts_begindate as dte_src_start,
        si_timesheetentry.employeename as employee_name,
        si_timesheetentry.itemname as item_name,
        si_timesheetentry.laborglentrycostrate as labor_gl_entry_cost_rate,
        si_timesheetentry.laborglentrylineno as labor_gl_entry_line_no,
        si_timesheetentry.laborglentryoffsetlineno as labor_gl_entry_offset_line_no,
        si_timesheetentry.lineno as line_no,
        si_timesheetentry.locationname as location_name,
        si_timesheetentry.notes as notes,
        si_timesheetentry.projectname as project_name,
        si_timesheetentry.qty as qty,
        si_timesheetentry.approved_qty as qty_approved,
        si_timesheetentry.approved_billable_qty as qty_approved_billable,
        si_timesheetentry.approved_non_billable_qty as qty_approved_non_billable,
        si_timesheetentry.approved_non_utilized_qty as qty_approved_non_utilized,
        si_timesheetentry.approved_utilized_qty as qty_approved_utilized,
        si_timesheetentry.billable_qty as qty_billable,
        si_timesheetentry.non_billable_qty as qty_non_billable,
        si_timesheetentry.non_utilized_qty as qty_non_utilized,
        si_timesheetentry.utilized_qty as qty_utilized,
        si_timesheetentry.record_url as record_url,
        si_timesheetentry.statglentrylineno as stat_gl_entry_line_no,
        si_timesheetentry.state as state,
        si_timesheetentry.taskname as task_name
    from si_timesheetentry
    left join si_timesheet on si_timesheet.recordno = si_timesheetentry.timesheetkey
),

salesforce as (
    select
        'sfc' as src_sys_key,
        current_timestamp as dts_created_at,
        '{{ this.model }}' as created_by,
        current_timestamp as dts_updated_at,
        '{{ this.model }}' as updated_by,
        current_timestamp as dts_eff_start,
        '9999-12-31' as dts_eff_end,
        true as bln_current,
        sf_timesheetentry.id as key,
        md5(sf_timesheetentry.id) as hash_key,
        null as link,-- link will be in join
        null as hash_link, -- hash_link will be in join
        sf_timesheetentry.pse_timecard_c as key_timesheet,
        md5(sf_timesheetentry.pse_timecard_c) as hash_key_timesheet,
        sf_timesheetentry.pse_resource_c as key_employee,
        md5(sf_timesheetentry.pse_resource_c) as hash_key_employee,
        sf_contact.pse_group_c as key_entity,
        md5(sf_contact.pse_group_c) as hash_key_entity,
        sf_contact.pse_group_c as key_project,
        md5(sf_contact.pse_group_c) as hash_key_project,
        sf_project_task.intacct_record_no_c as key_task,
        md5(sf_project_task.intacct_record_no_c) as hash_key_task,
        null as key_timesheet_entry,
        null as hash_key_timesheet_entry,
        null as billu_acct_key,
        null as customer_id,
        null as department_id,
        null as department_key,
        null as employee_earning_type_key,
        sf_contact.pse_api_resource_correlation_id_c as employee_id_intacct,
        null as item_id,
        null as item_key,
        null as labor_gl_batch_key,
        null as location_id,
        null as location_key,
        null as non_billnu_acct_key,
        null as non_billu_acct_key,
        sf_project.intacct_project_id_c as project_id,
        sf_timesheetentry.created_by_id as src_created_by_id,
        sf_timesheetentry.last_modified_by_id as src_modified_by_id,
        null as stat_gl_batch_key,
        null as stat_journal_key,
        sf_project_task.intacct_id_c as task_id,
        null as amt_labor_gl_entry,
        null as amt_labor_glentry_trx,
        null as amt_stat_gl_entry,
        null as bill_rate,
        null as bln_billable,
        null as bln_billed,
        null as customer_name,
        sf_contact.department as department_name,
        null as dte_entry,
        null as dte_gl_post,
        sf_timesheetentry.created_date as dte_src_created,
        sf_timesheetentry.pse_end_date_c as dte_src_end,
        sf_timesheetentry.last_modified_date as dte_src_modified,
        sf_timesheetentry.header_start_date as dte_src_start,
        sf_contact.name as employee_name,
        null as item_name,
        null as labor_gl_entry_cost_rate,
        null as labor_gl_entry_line_no,
        null as labor_gl_entry_offset_line_no,
        null as line_no,
        null as location_name,
        sf_timesheetentry.notes as notes,
        sf_project.name as project_name,
        sf_timesheetentry.qty as qty,
        null as qty_approved,
        null as qty_approved_billable,
        null as qty_approved_non_billable,
        null as qty_approved_non_utilized,
        null as qty_approved_utilized,
        null as qty_billable,
        null as qty_non_billable,
        null as qty_non_utilized,
        null as qty_utilized,
        null as record_url,
        null as stat_gl_entry_line_no,
        null as state,
        sf_timesheetentry.name as task_name
    from sf_timesheetentry
    left join sf_contact on sf_contact.id = sf_timesheetentry.pse_resource_c
    left join sf_project on sf_project.id = sf_timesheetentry.pse_project_c
    left join sf_project_task on sf_project_task.id = sf_timesheetentry.pse_project_task_c
    left join si_filtered si 
        on sf_project.intacct_project_id_c = si.projectid
        and sf_contact.pse_api_resource_correlation_id_c = si.employeeid
        and sf_timesheetentry.task_start_date = si.entrydate
        and sf_project_task.intacct_record_no_c = si.taskkey
)

select * from sage_intacct
union all
select * from salesforce
