{{ 
    config(
        materialized="table",
        schema="consolidation",
        alias="employee_payroll_deductions"
    )
}}

with 
    deduction as (
        select * 
        from {{ source('ukg_pro', 'payroll_deduction_history') }}
        where _fivetran_deleted=false
    )

select
    'ukg' as src_sys_key,
    cast(current_timestamp as timestamp_tz) as dts_created_at,
    '{{ this.name }}' as created_by,
    cast(current_timestamp as timestamp_tz) as dts_updated_at,
    '{{ this.name }}' as updated_by,
    cast(current_timestamp as timestamp_tz) as dts_eff_start,
    cast('9999-12-31' as timestamp_tz ) as dts_eff_end,
    true as bln_current,
    cast(deduction.record_id as varchar(5000)) as key,
    md5(deduction.record_id) as hash_key,
    cast(deduction.record_id as varchar(5000)) as link,
    md5(deduction.record_id) as hash_link,
    deduction.company_id as key_company,
    md5(deduction.company_id) as hash_key_company,
    deduction.employee_id as key_employee,
    md5(deduction.employee_id) as hash_key_employee,
    deduction.check_id as check_id,
    deduction.deduction_code as deduction_code,
    deduction.pay_group as pay_group_id,
    deduction.payee_id as payee_id,
    deduction.tax_calculation_group_id as tax_calculation_group_id,
    deduction.timeclock_code as timeclock_code,
    deduction.wage_garnishment_wage_code as wage_garnishment_wage_code,
    cast(deduction.benefit_amount as number(38,17)) as amt_benefit,
    cast(deduction.current_arrears_amount as number(38,17)) as amt_current_arrears,
    cast(deduction.custom_amount_1 as number(38,17)) as amt_custom_1,
    cast(deduction.custom_amount_2 as number(38,17)) as amt_custom_2,
    cast(deduction.deduction_calculation_basis_amt as number(38,17)) as amt_deduction_calculation_basis,
    cast(deduction.employee_current_amount as number(38,17)) as amt_employee_current,
    cast(deduction.employee_goal_amount as number(38,17)) as amt_employee_goal,
    cast(deduction.employee_goal_to_date_amount as number(38,17)) as amt_employee_goal_to_date,
    cast(deduction.employee_original_amount as number(38,17)) as amt_employee_original,
    cast(deduction.employer_current_amount as number(38,17)) as amt_employer_current,
    cast(deduction.wage_garnishment_additional_arrearage_amount as number(38,17)) as amt_wage_garnishment_additional_arrearage,
    cast(deduction.wage_garnishment_disposable_income as number(38,17)) as amt_wage_garnishment_disposable_income,
    cast(deduction.wage_garnishment_amount_exempt as number(38,17)) as amt_wage_garnishment_exempt,
    cast(deduction.wage_garnishment_amount_exempt_from_levy as number(38,17)) as amt_wage_garnishment_exempt_from_levy,
    cast(deduction.wage_garnishment_amount_exemt_from_garn as number(38,17)) as amt_wage_garnishment_exemt_from_garn,
    cast(deduction.wage_garnishment_amount_subject_to_cs as number(38,17)) as amt_wage_garnishment_subject_to_cs,
    cast(deduction.wage_garnishment_amount_subject_to_garnishment as number(38,17)) as amt_wage_garnishment_subject_to_garnishment,
    cast(deduction.year_to_date_deferred_compensation_combined_amount as number(38,17)) as amt_year_to_date_deferred_compensation_combined,
    deduction.benefit_option as benefit_option,
    deduction.benefit_provider as benefit_provider,
    case when deduction.allow_partial_deduction = 'Y' then true else false end as bln_allow_partial_deduction,
    case when deduction.deduction_for_bonus_only = 'Y' then true else false end as bln_deduction_for_bonus_only,
    case when deduction.exclude_from_workers_compensation = 'Y' then true else false end as bln_exclude_from_workers_compensation,
    deduction.is_401_k as bln_is_401_k,
    deduction.is_403_b as bln_is_403_b,
    deduction.is_408_k as bln_is_408_k,
    deduction.is_408_p as bln_is_408_p,
    deduction.is_457 as bln_is_457,
    deduction.is_457_b as bln_is_457_b,
    deduction.is_457_f as bln_is_457_f,
    deduction.is_501_c as bln_is_501_c,
    deduction.is_d_125 as bln_is_d_125,
    deduction.is_deduction_off_set as bln_is_deduction_off_set,
    deduction.is_deferred_compensation as bln_is_deferred_compensation,
    deduction.is_dependent_care as bln_is_dependent_care,
    deduction.is_housing as bln_is_housing,
    deduction.is_non_qualified_plan as bln_is_non_qualified_plan,
    deduction.is_prorated as bln_is_prorated,
    deduction.is_public_employee_retirement as bln_is_public_employee_retirement,
    deduction.is_section_125 as bln_is_section_125,
    deduction.is_voided as bln_is_voided,
    case when deduction.is_voiding_record = 'Y' then true else false end as bln_is_voiding_record,
    cast(deduction.wage_garnishment_minimum_wage_factor as number(38,17)) as wage_garnishment_minimum_wage_factor,
    deduction.child_support_type as child_support_type,
    deduction.deduction_plan_type as deduction_plan_type,
    deduction.deduction_type as deduction_type,
    cast(deduction.deferred_compensation_cap as number(38,17)) as deferred_compensation_cap,
    cast(deduction.deferred_compensation_regular_cap as number(38,17)) as deferred_compensation_regular_cap,
    deduction.custom_date as dte_custom,
    deduction.employee_deduction_last_paid as dte_employee_deduction_last_paid,
    deduction.pay_date as dte_pay,
    deduction.employee_calculaiton_rule as employee_calculation_rule,
    cast(deduction.employee_calculation_rate_or_percent as number(38,17)) as employee_calculation_rate_or_percent,
    deduction.employee_goal_rule as employee_goal_rule,
    deduction.employee_number as employee_number,
    cast(deduction.employer_annual_cap_calculation_rule as varchar(5000)) as employer_annual_cap_calculation_rule,
    cast(deduction.employer_calculation_rate_or_percent as number(38,17)) as employer_calculation_rate_or_percent,
    deduction.employer_calculation_rule as employer_calculation_rule,
    deduction.employer_period_cap_calculation_rule as employer_period_cap_calculation_rule,
    deduction.general_ledger_expense_account as general_ledger_expense_account,
    deduction.general_ledger_pay_account as general_ledger_pay_account,
    deduction.period_control as period_control,
    deduction.tax_category as tax_category,
    deduction.vendor as vendor,
    case when deduction.wage_garnishment_allocate_as_arrears = 'Y' then true else false end as bln_wage_garnishment_allocate_as_arrears,
    deduction.wage_garnishment_deduction_tax_category as wage_garnishment_deduction_tax_category,
from deduction