{{
    config(
        materialized="table",
        schema="consolidation",
        alias="invoice_item"
    )
}}

with 
    invoice_items as (select * from {{ source('sage_intacct', 'ar_invoice_item') }})

select 
    'int' as src_sys_key,
    cast(current_timestamp as timestamp_tz) as dts_created_at,
    '{{ this.name }}' as created_by,
    cast(current_timestamp as timestamp_tz) as dts_updated_at,
    '{{ this.name }}' as updated_by,
    cast(current_timestamp as timestamp_tz) as dts_eff_start,
    cast('9999-12-31' as timestamp_tz ) as dts_eff_end,
    true as bln_current,
    inv.recordno as key,
    md5(inv.recordno) as hash_key,
    inv.recordno as link,
    md5(inv.recordno) as hash_link,
    inv.recordkey as key_invoice,
    md5(inv.recordkey) as hash_key_invoice,
    cast(inv.employeedimkey as varchar(5000)) as key_employee,
    md5(inv.employeedimkey) as hash_key_employee,
    cast(inv.parententry as varchar(5000)) as key_parent_entry,
    md5(inv.parententry) as hash_key_parent_entry,
    cast(inv.projectdimkey as varchar(5000)) as key_project,
    md5(inv.projectdimkey) as hash_key_project,
    inv.accountkey as account_key,
    inv.allocationkey as allocation_key,
    inv.baselocation as base_location,
    inv.createdbyloginid as created_by_login_id,
    inv.customerdimkey as customer_key,
    nullif(inv.customerid,'') as customer_id,
    nullif(inv.departmentid,'') as department_id,
    inv.detailkey as detail_key,
    nullif(inv.employeeid,'') as employee_id,
    inv.exch_rate_type_id as exch_rate_type_id,
    inv.gldimvat_code as gl_vat_code,
    inv.itemdimkey as item_key,
    nullif(inv.itemid,'') as item_id,
    nullif(inv.locationid,'') as location_id,
    inv.modifiedbyloginid as modified_by_login_id,
    inv.offsetaccountkey as offset_account_key,
    nullif(inv.projectid,'') as projectid,
    inv.createdby as src_created_by,
    inv.modifiedby as src_modified_by,
    inv.taskid as task_id,
    inv.taskdimkey as task_key,
    inv.vendordimkey as vendor_key,
    nullif(inv.vendorid,'') as vendor_id,
    inv.accounttitle as account_title,
    cast(inv.amount as number(38,17)) as amt,
    cast(inv.base_vat_amount as number(38,17)) as amt_base_vat,
    nullif(inv.manual_vat_amount,false) as bln_manual_vat_amount,
    cast(inv.net_of_vat_amount as number(38,17)) as amt_net_of_vat,
    cast(inv.net_of_vat_base_amount as number(38,17)) as amt_net_of_vat_base,
    cast(inv.non_reclaim_vat_amount as number(38,17)) as amt_non_reclaim_vat,
    cast(inv.non_reclaim_vat_base_amount as number(38,17)) as amt_non_reclaim_vat_base,
    inv.reclaim_vat_amount as qty_reclaim_vat_amount,
    inv.reclaim_vat_base_amount as qty_reclaim_vat_base,
    inv.amountretained as qty_retained,
    inv.reverse_txn_vat_amount as qty_reverse_txn_vat,
    inv.reverse_txn_vat_base_amount as qty_reverse_txn_vat_base,
    nullif(inv.subtotal,'') as subtotal,
    cast(inv.totalpaid as number(38,17)) as amt_total_paid,
    cast(inv.trx_amount as number(38,17)) as amt_trx,
    cast(inv.trx_totalpaid as number(38,17)) as amt_trx_total_paid,
    cast(inv.vat_amount as number(38,17)) as amt_vat,
    inv.basecurr as currency_iso_code_base,
    nullif(inv.india_cgst_ar,false) as bln_india_cgst_ar,
    nullif(inv.india_igst_ar,false) as bln_india_igst_ar,
    nullif(inv.india_rcm_ar,false) as bln_india_rcm_ar,
    nullif(inv.india_sgst_ar,false) as bln_india_sgst_ar,
    nullif(inv.isretainagerelease,false) as bln_is_retain_age_release,
    nullif(inv.issummarized,false) as bln_is_summarized,
    nullif(inv.lineitem,false) as bln_line_item,
    nullif(inv.paymenttaxcapture,false) as bln_payment_tax_capture,
    nullif(inv.currency,'') as currency_iso_code,
    nullif(inv.customername,'') as customer_name,
    nullif(inv.departmentname,'') as department_name,
    inv.entry_date as dte_entry,
    inv.exch_rate_date as dte_exch_rate,
    inv.revrecstartdate as dte_rev_rec_start,
    inv.whencreated as dts_src_created,
    inv.whenmodified as dts_src_modified,
    nullif(inv.employeename,'') as employee_name,
    nullif(inv.entrydescription,'') as entry_description,
    cast(inv.exchange_rate as number(38,17)) as exchange_rate,
    inv.accountno as gl_account_no,
    inv.offsetglaccountno as gl_account_no_offset,
    inv.offsetglaccounttitle as gl_account_title_offset,
    inv.gldimline_tax_detail as gl_line_tax_detail,
    nullif(inv.itemname,'') as item_name,
    inv.line_no as line_no,
    nullif(inv.locationname,'') as location_name,
    inv.previous_offset_account as qty_previous_offset_account,
    inv.projectname as project_name,
    inv.totalselected as qty_total_selected,
    inv.trx_discountapplied as qty_trx_discount_applied,
    inv.trx_totalselected as qty_trx_total_selected,
    cast(inv.vat_rate as number(38,17)) as rate_vat,
    inv.reclaim as qty_reclaim,
    inv.recordtype as record_type,
    inv.record_url as record_url,
    inv.retainagepercentage as qty_retain_age_percentage,
    inv.state as status,
    nullif(inv.taskname,'') as task_name,
    nullif(inv.vendorname,'') as vendor_name
from invoice_items inv

