version: 2

sources:
  - name: salesforce
    database: prod_bi_raw
    schema: salesforce
    tables:
      - name: account
      - name: account_contact_relation
      - name: account_contact_role
      - name: account_team_member
      - name: approval
      - name: auth_session
      - name: calendar
      - name: campaign
      - name: campaign_member
      - name: contact
      - name: currency_type
      - name: custom_permission
      - name: cx_actor_c
      - name: cx_audit_trail_c
      - name: cx_client_c
      - name: cx_deliverable_action_c
      - name: cx_deliverable_c
      - name: cx_deliverable_template_c
      - name: cx_deliverable_type_c
      - name: cx_junction_deliverable_system_c
      - name: cx_junction_workflow_system_c
      - name: cx_project_c
      - name: cx_project_user_c
      - name: cx_sub_workstream_c
      - name: cx_system_c
      - name: cx_workflow_action_c
      - name: cx_workflow_c
      - name: cx_workstream_c
      - name: dashboard
      - name: dated_conversion_rate
      - name: duplicate_rule
      - name: event
      - name: expense_type_gla_mapping_c
      - name: fivetran_api_call
      - name: fivetran_dependent_picklist_relation
      - name: fivetran_formula
      - name: fivetran_formula_failure_reason
      - name: fivetran_formula_model
      - name: fivetran_picklist_field
      - name: fivetran_picklist_field_value
      - name: fivetran_query
      - name: forecasting_group_item
      - name: forecasting_item
      - name: forecasting_quota
      - name: lead
      - name: lead_source_junction_c
      - name: login_history
      - name: object_permissions
      - name: opportunity
      - name: opportunity_line_item
      - name: opportunity_team_member
      - name: permission_set
      - name: permission_set_assignment
      - name: permission_set_group
      - name: permission_set_license
      - name: permission_set_license_assign
      - name: phase_code_skill_c
      - name: pricebook_2
      - name: pricebook_entry
      - name: product_2
      - name: profile
      - name: project_experience_c
      - name: project_milestone_c
      - name: project_task_milestone_c
      - name: proposal_approval_c
      - name: pse_assignment_c
      - name: pse_assignment_milestone_c
      - name: pse_assignment_project_phase_c
      - name: pse_budget_c
      - name: pse_est_vs_actuals_c
      - name: pse_expense_c
      - name: pse_expense_limit_rate_c
      - name: pse_expense_report_c
      - name: pse_experience_c
      - name: pse_experience_skill_c
      - name: pse_grp_c
      - name: pse_milestone_c
      - name: pse_permission_control_c
      - name: pse_practice_actuals_c
      - name: pse_practice_c
      - name: pse_project_task_assignment_c
      - name: pse_project_task_c
      - name: pse_proj_c
      - name: pse_rate_card_c
      - name: pse_rate_card_set
      - name: pse_rate_card_set_junction_c
      - name: pse_region_c
      - name: pse_resource_request_c
      - name: pse_resource_skill_request_c
      - name: pse_schedule_c
      - name: pse_skill_c
      - name: pse_skill_certification_rating_c
      - name: pse_skill_certification_zone_c
      - name: pse_skill_set_c
      - name: pse_skill_set_skill_c
      - name: pse_task_time_c
      - name: pse_timecard
      - name: pse_timecard_header_c
      - name: pse_utilization_calculation_c
      - name: pse_utilization_detail_c
      - name: pse_utilization_engine_c
      - name: pse_work_calendar_c
      - name: purchase_order_c
      - name: quote
      - name: quote_line_item
      - name: resource_request_interest_c
      - name: responsibility_c
      - name: user
      - name: user_license
      - name: user_role
