{{
    config(
        materialized="table",
        schema="consolidation",
    )
}}

with
    cc_transaction as (
        select *
        from {{ source("sage_intacct", "cc_transaction") }}
        where _fivetran_deleted = false
    ),

    sage_intacct as (
        select
            'int' as src_sys_key,
            current_timestamp as dts_created_at,
            '{{ this.name }}' as created_by,
            current_timestamp as dts_updated_at,
            '{{ this.name }}' as updated_by,
            current_timestamp as dts_eff_start,
            '9999-12-31' as dts_eff_end,
            true as bln_current,
            recordno as key,
            md5(recordno) as hash_key,
            megaentitykey as key_entity,
            md5(recordno) as hash_key_entity,
            exch_rate_type_id as exchange_rate_type_id,
            megaentityid as entity_id,
            prbatchkey as pr_batch_key,
            recordid as record_id,
            createdby as src_created_by_id,
            modifiedby as src_modified_by_id,
            supdocid as sup_doc_id,
            totaldue as amt_total_due,
            totalentered as amt_total_entered,
            totalpaid as amt_total_paid,
            totalselected as amt_total_selected,
            trx_totaldue as amt_trx_total_due,
            trx_totalentered as amt_trx_total_entered,
            trx_totalpaid as amt_trx_total_paid,
            trx_totalselected as amt_trx_total_selected,
            basecurr as base_currency,
            cleared as bln_cleared,
            inclusivetax as bln_inclusive_tax,
            brex_expense_url as brex_expense_url,
            brex_receipt_url as brex_receipt_url,
            currency as currency,
            description as description,
            description_2 as description_2,
            exch_rate_date as dte_exchange_rate,
            auwhencreated as dts_au_when_created,
            whencreated as dts_src_created,
            whenpaid as dts_when_paid,
            megaentityname as entity_name,
            exchange_rate as exchange_rate,
            financialentity as financial_entity,
            prbatch_open as pr_batch_open,
            rawstate as raw_state,
            recordtype as record_type,
            record_url as record_url,
            state as state
        from cc_transaction
    )

select
    src_sys_key,
    cast(dts_created_at as timestamp_tz) as dts_created_at,
    created_by,
    cast(dts_updated_at as timestamp_tz) as dts_updated_at,
    updated_by,
    cast(dts_eff_start as timestamp_tz) as dts_eff_start,
    cast(dts_eff_end as timestamp_tz) as dts_eff_end,
    bln_current,
    key,
    hash_key,
    cast(key_entity as varchar(5000)) as key_entity,
    hash_key_entity,
    exchange_rate_type_id,
    entity_id,
    pr_batch_key,
    record_id,
    src_created_by_id,
    src_modified_by_id,
    sup_doc_id,
    cast(amt_total_due as number(38, 2)) as amt_total_due,
    cast(amt_total_entered as number(38, 2)) as amt_total_entered,
    cast(amt_total_paid as number(38, 2)) as amt_total_paid,
    cast(amt_total_selected as number(38, 2)) as amt_total_selected,
    cast(amt_trx_total_due as number(38, 2)) as amt_trx_total_due,
    cast(amt_trx_total_entered as number(38, 2)) as amt_trx_total_entered,
    cast(amt_trx_total_paid as number(38, 2)) as amt_trx_total_paid,
    amt_trx_total_selected,
    base_currency,
    bln_cleared,
    bln_inclusive_tax,
    brex_expense_url,
    brex_receipt_url,
    currency,
    description,
    description_2,
    dte_exchange_rate,
    cast(dts_au_when_created as timestamp_ntz) as dts_au_when_created,
    cast(dts_src_created as timestamp_ntz) as dts_src_created,
    cast(dts_when_paid as timestamp_ntz) as dts_when_paid,
    entity_name,
    cast(exchange_rate as number(38, 6)) as exchange_rate,
    financial_entity,
    pr_batch_open,
    raw_state,
    record_type,
    record_url,
    state
from sage_intacct
