name: Run dbt Build

on:
  push:
    branches:
      - feature/development_ci_cd
  workflow_dispatch:

jobs:
  dbt-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-snowflake

      - name: Set up dbt profile
        run: |
          mkdir -p ~/.dbt
          echo "$DBT_PROFILES_YML" > ~/.dbt/profiles.yml
          
  env:
    DBT_PROFILES_YML: ${{ secrets.DBT_PROFILES_YML }}
      - name: Run dbt build
        run: |
          dbt build
