name: Run dbt Build in Production

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *' 

jobs:
  dbt-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-snowflake

      - name: Decode Snowflake private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SNOWFLAKE_PK_BASE64 }}" | base64 -d > ~/.ssh/snowflake_key.pem
          chmod 600 ~/.ssh/snowflake_key.pem

      - name: Run dbt build
        run: dbt build --profiles-dir ./profiles --target prd
        working-directory: cai_bi

      - name: Send email on failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{ secrets.NOTIFICATION_MAIL_USERNAME }}
          password: ${{ secrets.NOTIFICATION_MAIL_PASSWORD }}
          subject: "🚨 dbt Build Failed in GitHub Actions (production)"
          to: itsupport@cagents.com,evan.gutzwiller@cagents.com 
          from: GitHub Actions <${{ secrets.NOTIFICATION_MAIL_USERNAME }}>
          body: |
            ❌ The dbt build failed in your GitHub Actions workflow.

            • Workflow: ${{ github.workflow }}
            • Job: ${{ github.job }}
            • Branch: ${{ github.ref }}
            • Commit: ${{ github.sha }}
            • Run URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
