with 
    eva as (select * from {{ source('salesforce', 'pse_est_vs_actuals_c') }} where is_deleted = false and _fivetran_deleted=false),
    rr as (select * from prod_bi_raw.salesforce.pse_resource_request_c where _fivetran_deleted=false)

select 
    'sfc' as src_sys_key,
    cast(current_timestamp as timestamp_tz) as dts_created_at,
    '{{ this.name }}' as created_by,
    cast(current_timestamp as timestamp_tz) as dts_updated_at,
    '{{ this.name }}' as updated_by,
    cast(current_timestamp as timestamp_tz) as dts_eff_start,
    cast('9999-12-31' as timestamp_tz ) as dts_eff_end,
    true as bln_current,
    eva.id as key,
    md5(eva.id) as hash_key,
    eva.id as link,
    md5(eva.id) as hash_link,
    eva.pse_assignment_c as key_assignment,
    md5(eva.pse_assignment_c) as hash_key_assignment,
    eva.pse_project_manager_c as key_project_manager,
    md5(eva.pse_project_manager_c) as hash_key_project_manager,
    eva.pse_project_c as key_project,
    md5(eva.pse_project_c) as hash_key_project,
    eva.pse_resource_request_c as key_resource_request,
    md5(eva.pse_resource_request_c) as hash_key_resource_request,
    eva.pse_resource_c as key_resource,
    md5(eva.pse_resource_c) as hash_key_resource,
    eva.pse_time_period_c as key_time_period,
    md5(eva.pse_time_period_c) as hash_key_time_period,
    rr.id as key_opportunity,
    md5(rr.id) as hash_key_opportunity,
    eva.owner_id as owner_id,
    eva.created_by_id as src_created_by,
    eva.last_modified_by_id as src_modified_by,
    eva.pse_time_period_type_c as time_period_type_id,
    cast(eva.pse_actual_days_c as number(38,17)) as actual_days,
    cast(eva.pse_actual_days_aggregated_c as number(38,17)) as actual_days_aggregated,
    cast(eva.pse_actual_hours_c as number(38,17)) as actual_hours,
    cast(eva.pse_actual_billable_amount_c as number(38,17)) as amt_actual_billable,
    eva.pse_timecards_submitted_c as bln_timecard_is_submitted,
    cast(eva.pse_project_currency_exchange_rate_c as number(38,17)) as currency_exchange_rate,
    eva.currency_iso_code as currency_iso_code,
    eva.pse_end_date_c as dte_end,
    eva.pse_start_date_c as dte_start,
    eva.system_modstamp as dte_system_modstamp,
    eva.created_date as dts_src_created,
    eva.last_modified_date as dts_src_modified,
    eva.name as name,
    cast(eva.pse_scheduled_billable_amount_c as number(38,17)) as planned_bill_amount,
    cast(eva.pse_resource_request_bill_rate_c as number(38,17)) as planned_bill_rate,
    cast(eva.pse_estimated_days_c as number(38,17)) as planned_days,
    cast(eva.pse_estimated_hours_c as number(38,17)) as planned_hours,
    cast(eva.pse_resource_request_days_c as number(38,17)) as requested_days,
    cast(eva.pse_resource_request_hours_c as number(38,17)) as requested_hours
from eva
left join rr on eva.pse_resource_request_c = rr.id